// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows

package iphelper

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	networkingwinsock "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networking/winsock"
	networkmanagementndis "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networkmanagement/ndis"
)

// Release with UnregisterInterfaceTimestampConfigChange.
// Invalid values: -1, 0.
type HIFTIMESTAMPCHANGE uintptr

// DNS_SERVER_PROPERTY_TYPE: https://learn.microsoft.com/windows/win32/api/netioapi/ne-netioapi-dns_server_property_type
type DNS_SERVER_PROPERTY_TYPE int32

const (
	DnsServerInvalidProperty DNS_SERVER_PROPERTY_TYPE = 0
	DnsServerDohProperty     DNS_SERVER_PROPERTY_TYPE = 1
	DnsServerDotProperty     DNS_SERVER_PROPERTY_TYPE = 2
)

type GET_ADAPTERS_ADDRESSES_FLAGS uint32

const (
	GAA_FLAG_SKIP_UNICAST                GET_ADAPTERS_ADDRESSES_FLAGS = 1
	GAA_FLAG_SKIP_ANYCAST                GET_ADAPTERS_ADDRESSES_FLAGS = 2
	GAA_FLAG_SKIP_MULTICAST              GET_ADAPTERS_ADDRESSES_FLAGS = 4
	GAA_FLAG_SKIP_DNS_SERVER             GET_ADAPTERS_ADDRESSES_FLAGS = 8
	GAA_FLAG_INCLUDE_PREFIX              GET_ADAPTERS_ADDRESSES_FLAGS = 16
	GAA_FLAG_SKIP_FRIENDLY_NAME          GET_ADAPTERS_ADDRESSES_FLAGS = 32
	GAA_FLAG_INCLUDE_WINS_INFO           GET_ADAPTERS_ADDRESSES_FLAGS = 64
	GAA_FLAG_INCLUDE_GATEWAYS            GET_ADAPTERS_ADDRESSES_FLAGS = 128
	GAA_FLAG_INCLUDE_ALL_INTERFACES      GET_ADAPTERS_ADDRESSES_FLAGS = 256
	GAA_FLAG_INCLUDE_ALL_COMPARTMENTS    GET_ADAPTERS_ADDRESSES_FLAGS = 512
	GAA_FLAG_INCLUDE_TUNNEL_BINDINGORDER GET_ADAPTERS_ADDRESSES_FLAGS = 1024
)

type GLOBAL_FILTER int32

const (
	GF_FRAGMENTS  GLOBAL_FILTER = 2
	GF_STRONGHOST GLOBAL_FILTER = 8
	GF_FRAGCACHE  GLOBAL_FILTER = 9
)

// ICMP4_TYPE: https://learn.microsoft.com/windows/win32/api/ipmib/ne-ipmib-icmp4_type
type ICMP4_TYPE int32

const (
	ICMP4_ECHO_REPLY        ICMP4_TYPE = 0
	ICMP4_DST_UNREACH       ICMP4_TYPE = 3
	ICMP4_SOURCE_QUENCH     ICMP4_TYPE = 4
	ICMP4_REDIRECT          ICMP4_TYPE = 5
	ICMP4_ECHO_REQUEST      ICMP4_TYPE = 8
	ICMP4_ROUTER_ADVERT     ICMP4_TYPE = 9
	ICMP4_ROUTER_SOLICIT    ICMP4_TYPE = 10
	ICMP4_TIME_EXCEEDED     ICMP4_TYPE = 11
	ICMP4_PARAM_PROB        ICMP4_TYPE = 12
	ICMP4_TIMESTAMP_REQUEST ICMP4_TYPE = 13
	ICMP4_TIMESTAMP_REPLY   ICMP4_TYPE = 14
	ICMP4_MASK_REQUEST      ICMP4_TYPE = 17
	ICMP4_MASK_REPLY        ICMP4_TYPE = 18
)

// ICMP6_TYPE: https://learn.microsoft.com/windows/win32/api/ipmib/ne-ipmib-icmp6_type
type ICMP6_TYPE int32

const (
	ICMP6_DST_UNREACH          ICMP6_TYPE = 1
	ICMP6_PACKET_TOO_BIG       ICMP6_TYPE = 2
	ICMP6_TIME_EXCEEDED        ICMP6_TYPE = 3
	ICMP6_PARAM_PROB           ICMP6_TYPE = 4
	ICMP6_ECHO_REQUEST         ICMP6_TYPE = 128
	ICMP6_ECHO_REPLY           ICMP6_TYPE = 129
	ICMP6_MEMBERSHIP_QUERY     ICMP6_TYPE = 130
	ICMP6_MEMBERSHIP_REPORT    ICMP6_TYPE = 131
	ICMP6_MEMBERSHIP_REDUCTION ICMP6_TYPE = 132
	ND_ROUTER_SOLICIT          ICMP6_TYPE = 133
	ND_ROUTER_ADVERT           ICMP6_TYPE = 134
	ND_NEIGHBOR_SOLICIT        ICMP6_TYPE = 135
	ND_NEIGHBOR_ADVERT         ICMP6_TYPE = 136
	ND_REDIRECT                ICMP6_TYPE = 137
	ICMP6_V2_MEMBERSHIP_REPORT ICMP6_TYPE = 143
)

type IF_ACCESS_TYPE int32

const (
	IF_ACCESS_LOOPBACK             IF_ACCESS_TYPE = 1
	IF_ACCESS_BROADCAST            IF_ACCESS_TYPE = 2
	IF_ACCESS_POINT_TO_POINT       IF_ACCESS_TYPE = 3
	IF_ACCESS_POINTTOPOINT         IF_ACCESS_TYPE = 3
	IF_ACCESS_POINT_TO_MULTI_POINT IF_ACCESS_TYPE = 4
	IF_ACCESS_POINTTOMULTIPOINT    IF_ACCESS_TYPE = 4
)

type INTERNAL_IF_OPER_STATUS int32

const (
	IF_OPER_STATUS_NON_OPERATIONAL INTERNAL_IF_OPER_STATUS = 0
	IF_OPER_STATUS_UNREACHABLE     INTERNAL_IF_OPER_STATUS = 1
	IF_OPER_STATUS_DISCONNECTED    INTERNAL_IF_OPER_STATUS = 2
	IF_OPER_STATUS_CONNECTING      INTERNAL_IF_OPER_STATUS = 3
	IF_OPER_STATUS_CONNECTED       INTERNAL_IF_OPER_STATUS = 4
	IF_OPER_STATUS_OPERATIONAL     INTERNAL_IF_OPER_STATUS = 5
)

type MIB_IF_ENTRY_LEVEL int32

const (
	MibIfEntryNormal                  MIB_IF_ENTRY_LEVEL = 0
	MibIfEntryNormalWithoutStatistics MIB_IF_ENTRY_LEVEL = 2
)

// MIB_IF_TABLE_LEVEL: https://learn.microsoft.com/windows/win32/api/netioapi/ne-netioapi-mib_if_table_level
type MIB_IF_TABLE_LEVEL int32

const (
	MibIfTableNormal                  MIB_IF_TABLE_LEVEL = 0
	MibIfTableRaw                     MIB_IF_TABLE_LEVEL = 1
	MibIfTableNormalWithoutStatistics MIB_IF_TABLE_LEVEL = 2
)

type MIB_IPFORWARD_TYPE int32

const (
	MIB_IPROUTE_TYPE_OTHER    MIB_IPFORWARD_TYPE = 1
	MIB_IPROUTE_TYPE_INVALID  MIB_IPFORWARD_TYPE = 2
	MIB_IPROUTE_TYPE_DIRECT   MIB_IPFORWARD_TYPE = 3
	MIB_IPROUTE_TYPE_INDIRECT MIB_IPFORWARD_TYPE = 4
)

type MIB_IPNET_TYPE int32

const (
	MIB_IPNET_TYPE_OTHER   MIB_IPNET_TYPE = 1
	MIB_IPNET_TYPE_INVALID MIB_IPNET_TYPE = 2
	MIB_IPNET_TYPE_DYNAMIC MIB_IPNET_TYPE = 3
	MIB_IPNET_TYPE_STATIC  MIB_IPNET_TYPE = 4
)

type MIB_IPSTATS_FORWARDING int32

const (
	MIB_IP_FORWARDING     MIB_IPSTATS_FORWARDING = 1
	MIB_IP_NOT_FORWARDING MIB_IPSTATS_FORWARDING = 2
)

// MIB_NOTIFICATION_TYPE: https://learn.microsoft.com/windows/win32/api/netioapi/ne-netioapi-mib_notification_type
type MIB_NOTIFICATION_TYPE int32

const (
	MibParameterNotification MIB_NOTIFICATION_TYPE = 0
	MibAddInstance           MIB_NOTIFICATION_TYPE = 1
	MibDeleteInstance        MIB_NOTIFICATION_TYPE = 2
	MibInitialNotification   MIB_NOTIFICATION_TYPE = 3
)

type MIB_TCP_STATE int32

const (
	MIB_TCP_STATE_CLOSED     MIB_TCP_STATE = 1
	MIB_TCP_STATE_LISTEN     MIB_TCP_STATE = 2
	MIB_TCP_STATE_SYN_SENT   MIB_TCP_STATE = 3
	MIB_TCP_STATE_SYN_RCVD   MIB_TCP_STATE = 4
	MIB_TCP_STATE_ESTAB      MIB_TCP_STATE = 5
	MIB_TCP_STATE_FIN_WAIT1  MIB_TCP_STATE = 6
	MIB_TCP_STATE_FIN_WAIT2  MIB_TCP_STATE = 7
	MIB_TCP_STATE_CLOSE_WAIT MIB_TCP_STATE = 8
	MIB_TCP_STATE_CLOSING    MIB_TCP_STATE = 9
	MIB_TCP_STATE_LAST_ACK   MIB_TCP_STATE = 10
	MIB_TCP_STATE_TIME_WAIT  MIB_TCP_STATE = 11
	MIB_TCP_STATE_DELETE_TCB MIB_TCP_STATE = 12
	MIB_TCP_STATE_RESERVED   MIB_TCP_STATE = 100
)

// NET_ADDRESS_FORMAT: https://learn.microsoft.com/windows/win32/api/iphlpapi/ne-iphlpapi-net_address_format
type NET_ADDRESS_FORMAT int32

const (
	NET_ADDRESS_FORMAT_UNSPECIFIED NET_ADDRESS_FORMAT = 0
	NET_ADDRESS_DNS_NAME           NET_ADDRESS_FORMAT = 1
	NET_ADDRESS_IPV4               NET_ADDRESS_FORMAT = 2
	NET_ADDRESS_IPV6               NET_ADDRESS_FORMAT = 3
)

type NET_FL_ISOLATION_MODE int32

const (
	NetFlIsolationModeNone NET_FL_ISOLATION_MODE = 0
	NetFlIsolationModeVlan NET_FL_ISOLATION_MODE = 1
	NetFlIsolationModeVsid NET_FL_ISOLATION_MODE = 2
)

type NET_FL_VIRTUAL_INTERFACE_ORIGIN int32

const (
	NetFlVirtualInterfaceOriginOid     NET_FL_VIRTUAL_INTERFACE_ORIGIN = 0
	NetFlVirtualInterfaceOriginApi     NET_FL_VIRTUAL_INTERFACE_ORIGIN = 1
	NetFlVirtualInterfaceOriginDefault NET_FL_VIRTUAL_INTERFACE_ORIGIN = 2
)

type PFADDRESSTYPE int32

const (
	PF_IPV4 PFADDRESSTYPE = 0
	PF_IPV6 PFADDRESSTYPE = 1
)

type PFFORWARD_ACTION int32

const (
	PF_ACTION_FORWARD PFFORWARD_ACTION = 0
	PF_ACTION_DROP    PFFORWARD_ACTION = 1
)

type PFFRAMETYPE int32

const (
	PFFT_FILTER PFFRAMETYPE = 1
	PFFT_FRAG   PFFRAMETYPE = 2
	PFFT_SPOOF  PFFRAMETYPE = 3
)

// TCPIP_OWNER_MODULE_INFO_CLASS: https://learn.microsoft.com/windows/win32/api/iprtrmib/ne-iprtrmib-tcpip_owner_module_info_class
type TCPIP_OWNER_MODULE_INFO_CLASS int32

const (
	TCPIP_OWNER_MODULE_INFO_BASIC TCPIP_OWNER_MODULE_INFO_CLASS = 0
)

// TCP_BOOLEAN_OPTIONAL: https://learn.microsoft.com/windows/win32/api/tcpestats/ne-tcpestats-tcp_boolean_optional
type TCP_BOOLEAN_OPTIONAL int32

const (
	TcpBoolOptDisabled  TCP_BOOLEAN_OPTIONAL = 0
	TcpBoolOptEnabled   TCP_BOOLEAN_OPTIONAL = 1
	TcpBoolOptUnchanged TCP_BOOLEAN_OPTIONAL = -1
)

// TCP_CONNECTION_OFFLOAD_STATE: https://learn.microsoft.com/windows/win32/api/tcpmib/ne-tcpmib-tcp_connection_offload_state
type TCP_CONNECTION_OFFLOAD_STATE int32

const (
	TcpConnectionOffloadStateInHost     TCP_CONNECTION_OFFLOAD_STATE = 0
	TcpConnectionOffloadStateOffloading TCP_CONNECTION_OFFLOAD_STATE = 1
	TcpConnectionOffloadStateOffloaded  TCP_CONNECTION_OFFLOAD_STATE = 2
	TcpConnectionOffloadStateUploading  TCP_CONNECTION_OFFLOAD_STATE = 3
	TcpConnectionOffloadStateMax        TCP_CONNECTION_OFFLOAD_STATE = 4
)

// TCP_ESTATS_TYPE: https://learn.microsoft.com/windows/win32/api/tcpestats/ne-tcpestats-tcp_estats_type
type TCP_ESTATS_TYPE int32

const (
	TcpConnectionEstatsSynOpts   TCP_ESTATS_TYPE = 0
	TcpConnectionEstatsData      TCP_ESTATS_TYPE = 1
	TcpConnectionEstatsSndCong   TCP_ESTATS_TYPE = 2
	TcpConnectionEstatsPath      TCP_ESTATS_TYPE = 3
	TcpConnectionEstatsSendBuff  TCP_ESTATS_TYPE = 4
	TcpConnectionEstatsRec       TCP_ESTATS_TYPE = 5
	TcpConnectionEstatsObsRec    TCP_ESTATS_TYPE = 6
	TcpConnectionEstatsBandwidth TCP_ESTATS_TYPE = 7
	TcpConnectionEstatsFineRtt   TCP_ESTATS_TYPE = 8
	TcpConnectionEstatsMaximum   TCP_ESTATS_TYPE = 9
)

type TCP_RTO_ALGORITHM int32

const (
	TcpRtoAlgorithmOther    TCP_RTO_ALGORITHM = 1
	TcpRtoAlgorithmConstant TCP_RTO_ALGORITHM = 2
	TcpRtoAlgorithmRsre     TCP_RTO_ALGORITHM = 3
	TcpRtoAlgorithmVanj     TCP_RTO_ALGORITHM = 4
	MIB_TCP_RTO_OTHER       TCP_RTO_ALGORITHM = 1
	MIB_TCP_RTO_CONSTANT    TCP_RTO_ALGORITHM = 2
	MIB_TCP_RTO_RSRE        TCP_RTO_ALGORITHM = 3
	MIB_TCP_RTO_VANJ        TCP_RTO_ALGORITHM = 4
)

// TCP_SOFT_ERROR: https://learn.microsoft.com/windows/win32/api/tcpestats/ne-tcpestats-tcp_soft_error
type TCP_SOFT_ERROR int32

const (
	TcpErrorNone              TCP_SOFT_ERROR = 0
	TcpErrorBelowDataWindow   TCP_SOFT_ERROR = 1
	TcpErrorAboveDataWindow   TCP_SOFT_ERROR = 2
	TcpErrorBelowAckWindow    TCP_SOFT_ERROR = 3
	TcpErrorAboveAckWindow    TCP_SOFT_ERROR = 4
	TcpErrorBelowTsWindow     TCP_SOFT_ERROR = 5
	TcpErrorAboveTsWindow     TCP_SOFT_ERROR = 6
	TcpErrorDataChecksumError TCP_SOFT_ERROR = 7
	TcpErrorDataLengthError   TCP_SOFT_ERROR = 8
	TcpErrorMaxSoftError      TCP_SOFT_ERROR = 9
)

// TCP_TABLE_CLASS: https://learn.microsoft.com/windows/win32/api/iprtrmib/ne-iprtrmib-tcp_table_class
type TCP_TABLE_CLASS int32

const (
	TCP_TABLE_BASIC_LISTENER           TCP_TABLE_CLASS = 0
	TCP_TABLE_BASIC_CONNECTIONS        TCP_TABLE_CLASS = 1
	TCP_TABLE_BASIC_ALL                TCP_TABLE_CLASS = 2
	TCP_TABLE_OWNER_PID_LISTENER       TCP_TABLE_CLASS = 3
	TCP_TABLE_OWNER_PID_CONNECTIONS    TCP_TABLE_CLASS = 4
	TCP_TABLE_OWNER_PID_ALL            TCP_TABLE_CLASS = 5
	TCP_TABLE_OWNER_MODULE_LISTENER    TCP_TABLE_CLASS = 6
	TCP_TABLE_OWNER_MODULE_CONNECTIONS TCP_TABLE_CLASS = 7
	TCP_TABLE_OWNER_MODULE_ALL         TCP_TABLE_CLASS = 8
)

// UDP_TABLE_CLASS: https://learn.microsoft.com/windows/win32/api/iprtrmib/ne-iprtrmib-udp_table_class
type UDP_TABLE_CLASS int32

const (
	UDP_TABLE_BASIC        UDP_TABLE_CLASS = 0
	UDP_TABLE_OWNER_PID    UDP_TABLE_CLASS = 1
	UDP_TABLE_OWNER_MODULE UDP_TABLE_CLASS = 2
)

// ARP_SEND_REPLY: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-arp_send_reply
type ARP_SEND_REPLY struct {
	DestAddress uint32
	SrcAddress  uint32
}

// DNS_DOH_SERVER_SETTINGS: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-dns_doh_server_settings
type DNS_DOH_SERVER_SETTINGS struct {
	Template foundation.PWSTR
	Flags    uint64
}

type DNS_DOT_SERVER_SETTINGS struct {
	Hostname foundation.PWSTR
	Flags    uint64
	Port     uint16
}

// DNS_INTERFACE_SETTINGS: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-dns_interface_settings
type DNS_INTERFACE_SETTINGS struct {
	Version             uint32
	Flags               uint64
	Domain              foundation.PWSTR
	NameServer          foundation.PWSTR
	SearchList          foundation.PWSTR
	RegistrationEnabled uint32
	RegisterAdapterName uint32
	EnableLLMNR         uint32
	QueryAdapterName    uint32
	ProfileNameServer   foundation.PWSTR
}

// DNS_INTERFACE_SETTINGS3: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-dns_interface_settings3
type DNS_INTERFACE_SETTINGS3 struct {
	Version                     uint32
	Flags                       uint64
	Domain                      foundation.PWSTR
	NameServer                  foundation.PWSTR
	SearchList                  foundation.PWSTR
	RegistrationEnabled         uint32
	RegisterAdapterName         uint32
	EnableLLMNR                 uint32
	QueryAdapterName            uint32
	ProfileNameServer           foundation.PWSTR
	DisableUnconstrainedQueries uint32
	SupplementalSearchList      foundation.PWSTR
	CServerProperties           uint32
	ServerProperties            *DNS_SERVER_PROPERTY
	CProfileServerProperties    uint32
	ProfileServerProperties     *DNS_SERVER_PROPERTY
}

type DNS_INTERFACE_SETTINGS4 struct {
	Version                     uint32
	Flags                       uint64
	Domain                      foundation.PWSTR
	NameServer                  foundation.PWSTR
	SearchList                  foundation.PWSTR
	RegistrationEnabled         uint32
	RegisterAdapterName         uint32
	EnableLLMNR                 uint32
	QueryAdapterName            uint32
	ProfileNameServer           foundation.PWSTR
	DisableUnconstrainedQueries uint32
	SupplementalSearchList      foundation.PWSTR
	CServerProperties           uint32
	ServerProperties            *DNS_SERVER_PROPERTY
	CProfileServerProperties    uint32
	ProfileServerProperties     *DNS_SERVER_PROPERTY
	EncryptedDnsAdapterFlags    uint32
}

type DNS_INTERFACE_SETTINGS_EX struct {
	SettingsV1                  DNS_INTERFACE_SETTINGS
	DisableUnconstrainedQueries uint32
	SupplementalSearchList      foundation.PWSTR
}

// DNS_SERVER_PROPERTY: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-dns_server_property
type DNS_SERVER_PROPERTY struct {
	Version     uint32
	ServerIndex uint32
	Type        DNS_SERVER_PROPERTY_TYPE
	Property    DNS_SERVER_PROPERTY_TYPES
}

// DNS_SERVER_PROPERTY_TYPES: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-dns_server_property_types
// DNS_SERVER_PROPERTY_TYPES is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DNS_SERVER_PROPERTY_TYPES struct {
	Data [1]uint64
}

type DNS_SETTINGS struct {
	Version    uint32
	Flags      uint64
	Hostname   foundation.PWSTR
	Domain     foundation.PWSTR
	SearchList foundation.PWSTR
}

type DNS_SETTINGS2 struct {
	Version      uint32
	Flags        uint64
	Hostname     foundation.PWSTR
	Domain       foundation.PWSTR
	SearchList   foundation.PWSTR
	SettingFlags uint64
}

// FIXED_INFO_W2KSP1: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-fixed_info_w2ksp1
type FIXED_INFO_W2KSP1 struct {
	HostName         [132]foundation.CHAR
	DomainName       [132]foundation.CHAR
	CurrentDnsServer *IP_ADDR_STRING
	DnsServerList    IP_ADDR_STRING
	NodeType         uint32
	ScopeId          [260]foundation.CHAR
	EnableRouting    uint32
	EnableProxy      uint32
	EnableDns        uint32
}

// ICMPV6_ECHO_REPLY_LH: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-icmpv6_echo_reply_lh
type ICMPV6_ECHO_REPLY_LH struct {
	Address       [26]byte
	Status        uint32
	RoundTripTime uint32
}

// ICMP_ECHO_REPLY: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-icmp_echo_reply
type ICMP_ECHO_REPLY struct {
	Address       uint32
	Status        uint32
	RoundTripTime uint32
	DataSize      uint16
	Reserved      uint16
	Data          unsafe.Pointer
	Options       IP_OPTION_INFORMATION
}

// ICMP_ECHO_REPLY32: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-icmp_echo_reply32
type ICMP_ECHO_REPLY32 struct {
	Address       uint32
	Status        uint32
	RoundTripTime uint32
	DataSize      uint16
	Reserved      uint16
	Data          unsafe.Pointer
	Options       IP_OPTION_INFORMATION32
}

// INTERFACE_HARDWARE_CROSSTIMESTAMP: https://learn.microsoft.com/windows/win32/api/iphlpapi/ns-iphlpapi-interface_hardware_crosstimestamp
type INTERFACE_HARDWARE_CROSSTIMESTAMP struct {
	SystemTimestamp1       uint64
	HardwareClockTimestamp uint64
	SystemTimestamp2       uint64
}

// INTERFACE_HARDWARE_TIMESTAMP_CAPABILITIES: https://learn.microsoft.com/windows/win32/api/iphlpapi/ns-iphlpapi-interface_hardware_timestamp_capabilities
type INTERFACE_HARDWARE_TIMESTAMP_CAPABILITIES struct {
	PtpV2OverUdpIPv4EventMessageReceive  foundation.BOOLEAN
	PtpV2OverUdpIPv4AllMessageReceive    foundation.BOOLEAN
	PtpV2OverUdpIPv4EventMessageTransmit foundation.BOOLEAN
	PtpV2OverUdpIPv4AllMessageTransmit   foundation.BOOLEAN
	PtpV2OverUdpIPv6EventMessageReceive  foundation.BOOLEAN
	PtpV2OverUdpIPv6AllMessageReceive    foundation.BOOLEAN
	PtpV2OverUdpIPv6EventMessageTransmit foundation.BOOLEAN
	PtpV2OverUdpIPv6AllMessageTransmit   foundation.BOOLEAN
	AllReceive                           foundation.BOOLEAN
	AllTransmit                          foundation.BOOLEAN
	TaggedTransmit                       foundation.BOOLEAN
}

// INTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES: https://learn.microsoft.com/windows/win32/api/iphlpapi/ns-iphlpapi-interface_software_timestamp_capabilities
type INTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES struct {
	AllReceive     foundation.BOOLEAN
	AllTransmit    foundation.BOOLEAN
	TaggedTransmit foundation.BOOLEAN
}

// INTERFACE_TIMESTAMP_CAPABILITIES: https://learn.microsoft.com/windows/win32/api/iphlpapi/ns-iphlpapi-interface_timestamp_capabilities
type INTERFACE_TIMESTAMP_CAPABILITIES struct {
	HardwareClockFrequencyHz uint64
	SupportsCrossTimestamp   foundation.BOOLEAN
	HardwareCapabilities     INTERFACE_HARDWARE_TIMESTAMP_CAPABILITIES
	SoftwareCapabilities     INTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES
}

// IP_ADAPTER_ADDRESSES_LH_Anonymous1_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_ADDRESSES_LH_Anonymous1_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_ADDRESSES_LH_Anonymous2_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_ADDRESSES_LH_Anonymous2_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_ADDRESSES_LH: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh
type IP_ADAPTER_ADDRESSES_LH struct {
	Anonymous1             uintptr
	Next                   *IP_ADAPTER_ADDRESSES_LH
	AdapterName            foundation.PSTR
	FirstUnicastAddress    *IP_ADAPTER_UNICAST_ADDRESS_LH
	FirstAnycastAddress    *IP_ADAPTER_ANYCAST_ADDRESS_XP
	FirstMulticastAddress  *IP_ADAPTER_MULTICAST_ADDRESS_XP
	FirstDnsServerAddress  *IP_ADAPTER_DNS_SERVER_ADDRESS_XP
	DnsSuffix              foundation.PWSTR
	Description            foundation.PWSTR
	FriendlyName           foundation.PWSTR
	PhysicalAddress        [8]byte
	PhysicalAddressLength  uint32
	Anonymous2             uintptr
	Mtu                    uint32
	IfType                 uint32
	OperStatus             networkmanagementndis.IF_OPER_STATUS
	Ipv6IfIndex            uint32
	ZoneIndices            [16]uint32
	FirstPrefix            *IP_ADAPTER_PREFIX_XP
	TransmitLinkSpeed      uint64
	ReceiveLinkSpeed       uint64
	FirstWinsServerAddress *IP_ADAPTER_WINS_SERVER_ADDRESS_LH
	FirstGatewayAddress    *IP_ADAPTER_GATEWAY_ADDRESS_LH
	Ipv4Metric             uint32
	Ipv6Metric             uint32
	Luid                   networkmanagementndis.NET_LUID_LH
	Dhcpv4Server           networkingwinsock.SOCKET_ADDRESS
	CompartmentId          networkmanagementndis.NET_IF_COMPARTMENT_ID
	NetworkGuid            win32.GUID
	ConnectionType         networkmanagementndis.NET_IF_CONNECTION_TYPE
	TunnelType             networkmanagementndis.TUNNEL_TYPE
	Dhcpv6Server           networkingwinsock.SOCKET_ADDRESS
	Dhcpv6ClientDuid       [130]byte
	Dhcpv6ClientDuidLength uint32
	Dhcpv6Iaid             uint32
	FirstDnsSuffix         *IP_ADAPTER_DNS_SUFFIX
}

// IP_ADAPTER_ADDRESSES_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_ADDRESSES_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_ADDRESSES_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_xp
type IP_ADAPTER_ADDRESSES_XP struct {
	Anonymous             uintptr
	Next                  *IP_ADAPTER_ADDRESSES_XP
	AdapterName           foundation.PSTR
	FirstUnicastAddress   *IP_ADAPTER_UNICAST_ADDRESS_XP
	FirstAnycastAddress   *IP_ADAPTER_ANYCAST_ADDRESS_XP
	FirstMulticastAddress *IP_ADAPTER_MULTICAST_ADDRESS_XP
	FirstDnsServerAddress *IP_ADAPTER_DNS_SERVER_ADDRESS_XP
	DnsSuffix             foundation.PWSTR
	Description           foundation.PWSTR
	FriendlyName          foundation.PWSTR
	PhysicalAddress       [8]byte
	PhysicalAddressLength uint32
	Flags                 uint32
	Mtu                   uint32
	IfType                uint32
	OperStatus            networkmanagementndis.IF_OPER_STATUS
	Ipv6IfIndex           uint32
	ZoneIndices           [16]uint32
	FirstPrefix           *IP_ADAPTER_PREFIX_XP
}

// IP_ADAPTER_ANYCAST_ADDRESS_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_ANYCAST_ADDRESS_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_ANYCAST_ADDRESS_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_anycast_address_xp
type IP_ADAPTER_ANYCAST_ADDRESS_XP struct {
	Anonymous uintptr
	Next      *IP_ADAPTER_ANYCAST_ADDRESS_XP
	Address   networkingwinsock.SOCKET_ADDRESS
}

// IP_ADAPTER_DNS_SERVER_ADDRESS_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_DNS_SERVER_ADDRESS_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_DNS_SERVER_ADDRESS_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_dns_server_address_xp
type IP_ADAPTER_DNS_SERVER_ADDRESS_XP struct {
	Anonymous uintptr
	Next      *IP_ADAPTER_DNS_SERVER_ADDRESS_XP
	Address   networkingwinsock.SOCKET_ADDRESS
}

// IP_ADAPTER_DNS_SUFFIX: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_dns_suffix
type IP_ADAPTER_DNS_SUFFIX struct {
	Next   *IP_ADAPTER_DNS_SUFFIX
	String [256]uint16
}

// IP_ADAPTER_GATEWAY_ADDRESS_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_GATEWAY_ADDRESS_LH_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_GATEWAY_ADDRESS_LH: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_gateway_address_lh
type IP_ADAPTER_GATEWAY_ADDRESS_LH struct {
	Anonymous uintptr
	Next      *IP_ADAPTER_GATEWAY_ADDRESS_LH
	Address   networkingwinsock.SOCKET_ADDRESS
}

// IP_ADAPTER_INDEX_MAP: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_adapter_index_map
type IP_ADAPTER_INDEX_MAP struct {
	Index uint32
	Name  [128]uint16
}

// IP_ADAPTER_INFO: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_info
type IP_ADAPTER_INFO struct {
	Next                *IP_ADAPTER_INFO
	ComboIndex          uint32
	AdapterName         [260]foundation.CHAR
	Description         [132]foundation.CHAR
	AddressLength       uint32
	Address             [8]byte
	Index               uint32
	Type                uint32
	DhcpEnabled         uint32
	CurrentIpAddress    *IP_ADDR_STRING
	IpAddressList       IP_ADDR_STRING
	GatewayList         IP_ADDR_STRING
	DhcpServer          IP_ADDR_STRING
	HaveWins            foundation.BOOL
	PrimaryWinsServer   IP_ADDR_STRING
	SecondaryWinsServer IP_ADDR_STRING
	LeaseObtained       int64
	LeaseExpires        int64
}

// IP_ADAPTER_MULTICAST_ADDRESS_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_MULTICAST_ADDRESS_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_MULTICAST_ADDRESS_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_multicast_address_xp
type IP_ADAPTER_MULTICAST_ADDRESS_XP struct {
	Anonymous uintptr
	Next      *IP_ADAPTER_MULTICAST_ADDRESS_XP
	Address   networkingwinsock.SOCKET_ADDRESS
}

// IP_ADAPTER_ORDER_MAP: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_adapter_order_map
type IP_ADAPTER_ORDER_MAP struct {
	NumAdapters  uint32
	AdapterOrder [1]uint32
}

// IP_ADAPTER_PREFIX_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_PREFIX_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_PREFIX_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_prefix_xp
type IP_ADAPTER_PREFIX_XP struct {
	Anonymous    uintptr
	Next         *IP_ADAPTER_PREFIX_XP
	Address      networkingwinsock.SOCKET_ADDRESS
	PrefixLength uint32
}

// IP_ADAPTER_UNICAST_ADDRESS_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_UNICAST_ADDRESS_LH_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_UNICAST_ADDRESS_LH: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_unicast_address_lh
type IP_ADAPTER_UNICAST_ADDRESS_LH struct {
	Anonymous          uintptr
	Next               *IP_ADAPTER_UNICAST_ADDRESS_LH
	Address            networkingwinsock.SOCKET_ADDRESS
	PrefixOrigin       networkingwinsock.NL_PREFIX_ORIGIN
	SuffixOrigin       networkingwinsock.NL_SUFFIX_ORIGIN
	DadState           networkingwinsock.NL_DAD_STATE
	ValidLifetime      uint32
	PreferredLifetime  uint32
	LeaseLifetime      uint32
	OnLinkPrefixLength byte
}

// IP_ADAPTER_UNICAST_ADDRESS_XP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_UNICAST_ADDRESS_XP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_UNICAST_ADDRESS_XP: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_unicast_address_xp
type IP_ADAPTER_UNICAST_ADDRESS_XP struct {
	Anonymous         uintptr
	Next              *IP_ADAPTER_UNICAST_ADDRESS_XP
	Address           networkingwinsock.SOCKET_ADDRESS
	PrefixOrigin      networkingwinsock.NL_PREFIX_ORIGIN
	SuffixOrigin      networkingwinsock.NL_SUFFIX_ORIGIN
	DadState          networkingwinsock.NL_DAD_STATE
	ValidLifetime     uint32
	PreferredLifetime uint32
	LeaseLifetime     uint32
}

// IP_ADAPTER_WINS_SERVER_ADDRESS_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type IP_ADAPTER_WINS_SERVER_ADDRESS_LH_Anonymous_e__Union struct {
	Data [1]uint64
}

// IP_ADAPTER_WINS_SERVER_ADDRESS_LH: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_adapter_wins_server_address_lh
type IP_ADAPTER_WINS_SERVER_ADDRESS_LH struct {
	Anonymous uintptr
	Next      *IP_ADAPTER_WINS_SERVER_ADDRESS_LH
	Address   networkingwinsock.SOCKET_ADDRESS
}

// IP_ADDRESS_PREFIX: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-ip_address_prefix
type IP_ADDRESS_PREFIX struct {
	Prefix       networkingwinsock.SOCKADDR_INET
	PrefixLength byte
}

// IP_ADDRESS_STRING: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_address_string
type IP_ADDRESS_STRING struct {
	String [16]foundation.CHAR
}

// IP_ADDR_STRING: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_addr_string
type IP_ADDR_STRING struct {
	Next      *IP_ADDR_STRING
	IpAddress IP_ADDRESS_STRING
	IpMask    IP_ADDRESS_STRING
	Context   uint32
}

// IP_INTERFACE_INFO: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_interface_info
type IP_INTERFACE_INFO struct {
	NumAdapters int32
	Adapter     [1]IP_ADAPTER_INDEX_MAP
}

// IP_INTERFACE_NAME_INFO_W2KSP1: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_interface_name_info_w2ksp1
type IP_INTERFACE_NAME_INFO_W2KSP1 struct {
	Index          uint32
	MediaType      uint32
	ConnectionType byte
	AccessType     byte
	DeviceGuid     win32.GUID
	InterfaceGuid  win32.GUID
}

// IP_MCAST_COUNTER_INFO: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_mcast_counter_info
type IP_MCAST_COUNTER_INFO struct {
	InMcastOctets  uint64
	OutMcastOctets uint64
	InMcastPkts    uint64
	OutMcastPkts   uint64
}

// IP_OPTION_INFORMATION: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_option_information
type IP_OPTION_INFORMATION struct {
	Ttl         byte
	Tos         byte
	Flags       byte
	OptionsSize byte
	OptionsData *byte
}

// IP_OPTION_INFORMATION32: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_option_information32
type IP_OPTION_INFORMATION32 struct {
	Ttl         byte
	Tos         byte
	Flags       byte
	OptionsSize byte
	OptionsData *byte
}

// IP_PER_ADAPTER_INFO_W2KSP1: https://learn.microsoft.com/windows/win32/api/iptypes/ns-iptypes-ip_per_adapter_info_w2ksp1
type IP_PER_ADAPTER_INFO_W2KSP1 struct {
	AutoconfigEnabled uint32
	AutoconfigActive  uint32
	CurrentDnsServer  *IP_ADDR_STRING
	DnsServerList     IP_ADDR_STRING
}

// IP_UNIDIRECTIONAL_ADAPTER_ADDRESS: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-ip_unidirectional_adapter_address
type IP_UNIDIRECTIONAL_ADAPTER_ADDRESS struct {
	NumAdapters uint32
	Address     [1]uint32
}

// MIBICMPINFO: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mibicmpinfo
type MIBICMPINFO struct {
	IcmpInStats  MIBICMPSTATS
	IcmpOutStats MIBICMPSTATS
}

// MIBICMPSTATS: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mibicmpstats
type MIBICMPSTATS struct {
	DwMsgs          uint32
	DwErrors        uint32
	DwDestUnreachs  uint32
	DwTimeExcds     uint32
	DwParmProbs     uint32
	DwSrcQuenchs    uint32
	DwRedirects     uint32
	DwEchos         uint32
	DwEchoReps      uint32
	DwTimestamps    uint32
	DwTimestampReps uint32
	DwAddrMasks     uint32
	DwAddrMaskReps  uint32
}

// MIBICMPSTATS_EX_XPSP1: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mibicmpstats_ex_xpsp1
type MIBICMPSTATS_EX_XPSP1 struct {
	DwMsgs        uint32
	DwErrors      uint32
	RgdwTypeCount [256]uint32
}

// MIB_ANYCASTIPADDRESS_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_anycastipaddress_row
type MIB_ANYCASTIPADDRESS_ROW struct {
	Address        networkingwinsock.SOCKADDR_INET
	InterfaceLuid  networkmanagementndis.NET_LUID_LH
	InterfaceIndex uint32
	ScopeId        networkingwinsock.SCOPE_ID
}

// MIB_ANYCASTIPADDRESS_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_anycastipaddress_table
type MIB_ANYCASTIPADDRESS_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_ANYCASTIPADDRESS_ROW
}

// MIB_BEST_IF: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_best_if
type MIB_BEST_IF struct {
	DwDestAddr uint32
	DwIfIndex  uint32
}

// MIB_BOUNDARYROW: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_boundaryrow
type MIB_BOUNDARYROW struct {
	DwGroupAddress uint32
	DwGroupMask    uint32
}

type MIB_FL_VIRTUAL_INTERFACE_ROW struct {
	Family                                 networkingwinsock.ADDRESS_FAMILY
	IfLuid                                 networkmanagementndis.NET_LUID_LH
	VirtualIfId                            uint32
	CompartmentGuid                        win32.GUID
	IsolationMode                          NET_FL_ISOLATION_MODE
	Origin                                 NET_FL_VIRTUAL_INTERFACE_ORIGIN
	VirtualIfLuid                          networkmanagementndis.NET_LUID_LH
	VirtualIfIndex                         uint32
	AllowLocalNd                           foundation.BOOLEAN
	AttachedFlsnpiClients                  uint32
	FlsnpiClientConfigErrors               uint32
	FlsnpiClientInjectErrors               uint64
	FlsnpiClientCloneErrors                uint64
	InFlsnpiIndicatedPackets               uint64
	InFlsnpiClientReturnedPackets          uint64
	InFlsnpiClientSilentlyDroppedPackets   uint64
	InFlsnpiClientDroppedPackets           uint64
	InFlsnpiClientInjectedPackets          uint64
	InFlsnpiClientClonedPackets            uint64
	OutFlsnpiIndicatedPackets              uint64
	OutFlsnpiClientReturnedPackets         uint64
	OutFlsnpiClientDroppedPackets          uint64
	OutFlsnpiClientSilentlyDroppedPackets  uint64
	OutFlsnpiClientInjectedPackets         uint64
	OutFlsnpiClientClonedPackets           uint64
	OutFlsnpiClientClonedPacketsForNbSplit uint64
}

type MIB_FL_VIRTUAL_INTERFACE_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_FL_VIRTUAL_INTERFACE_ROW
}

// MIB_ICMP: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_icmp
type MIB_ICMP struct {
	Stats MIBICMPINFO
}

// MIB_ICMP_EX_XPSP1: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_icmp_ex_xpsp1
type MIB_ICMP_EX_XPSP1 struct {
	IcmpInStats  MIBICMPSTATS_EX_XPSP1
	IcmpOutStats MIBICMPSTATS_EX_XPSP1
}

// MIB_IFNUMBER: https://learn.microsoft.com/windows/win32/api/ifmib/ns-ifmib-mib_ifnumber
type MIB_IFNUMBER struct {
	DwValue uint32
}

// MIB_IFROW: https://learn.microsoft.com/windows/win32/api/ifmib/ns-ifmib-mib_ifrow
type MIB_IFROW struct {
	WszName           [256]uint16
	DwIndex           uint32
	DwType            uint32
	DwMtu             uint32
	DwSpeed           uint32
	DwPhysAddrLen     uint32
	BPhysAddr         [8]byte
	DwAdminStatus     uint32
	DwOperStatus      INTERNAL_IF_OPER_STATUS
	DwLastChange      uint32
	DwInOctets        uint32
	DwInUcastPkts     uint32
	DwInNUcastPkts    uint32
	DwInDiscards      uint32
	DwInErrors        uint32
	DwInUnknownProtos uint32
	DwOutOctets       uint32
	DwOutUcastPkts    uint32
	DwOutNUcastPkts   uint32
	DwOutDiscards     uint32
	DwOutErrors       uint32
	DwOutQLen         uint32
	DwDescrLen        uint32
	BDescr            [256]byte
}

// MIB_IFSTACK_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ifstack_row
type MIB_IFSTACK_ROW struct {
	HigherLayerInterfaceIndex uint32
	LowerLayerInterfaceIndex  uint32
}

// MIB_IFSTACK_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ifstack_table
type MIB_IFSTACK_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_IFSTACK_ROW
}

// MIB_IFSTATUS: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_ifstatus
type MIB_IFSTATUS struct {
	DwIfIndex           uint32
	DwAdminStatus       uint32
	DwOperationalStatus uint32
	BMHbeatActive       foundation.BOOL
	BMHbeatAlive        foundation.BOOL
}

// MIB_IFTABLE: https://learn.microsoft.com/windows/win32/api/ifmib/ns-ifmib-mib_iftable
type MIB_IFTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IFROW
}

type MIB_IF_ROW2_InterfaceAndOperStatusFlags_e__Struct struct {
	Bitfield byte
}

// MIB_IF_ROW2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_if_row2
type MIB_IF_ROW2 struct {
	InterfaceLuid               networkmanagementndis.NET_LUID_LH
	InterfaceIndex              uint32
	InterfaceGuid               win32.GUID
	Alias                       [257]uint16
	Description                 [257]uint16
	PhysicalAddressLength       uint32
	PhysicalAddress             [32]byte
	PermanentPhysicalAddress    [32]byte
	Mtu                         uint32
	Type                        uint32
	TunnelType                  networkmanagementndis.TUNNEL_TYPE
	MediaType                   networkmanagementndis.NDIS_MEDIUM
	PhysicalMediumType          networkmanagementndis.NDIS_PHYSICAL_MEDIUM
	AccessType                  networkmanagementndis.NET_IF_ACCESS_TYPE
	DirectionType               networkmanagementndis.NET_IF_DIRECTION_TYPE
	InterfaceAndOperStatusFlags uintptr
	OperStatus                  networkmanagementndis.IF_OPER_STATUS
	AdminStatus                 networkmanagementndis.NET_IF_ADMIN_STATUS
	MediaConnectState           networkmanagementndis.NET_IF_MEDIA_CONNECT_STATE
	NetworkGuid                 win32.GUID
	ConnectionType              networkmanagementndis.NET_IF_CONNECTION_TYPE
	TransmitLinkSpeed           uint64
	ReceiveLinkSpeed            uint64
	InOctets                    uint64
	InUcastPkts                 uint64
	InNUcastPkts                uint64
	InDiscards                  uint64
	InErrors                    uint64
	InUnknownProtos             uint64
	InUcastOctets               uint64
	InMulticastOctets           uint64
	InBroadcastOctets           uint64
	OutOctets                   uint64
	OutUcastPkts                uint64
	OutNUcastPkts               uint64
	OutDiscards                 uint64
	OutErrors                   uint64
	OutUcastOctets              uint64
	OutMulticastOctets          uint64
	OutBroadcastOctets          uint64
	OutQLen                     uint64
}

// MIB_IF_TABLE2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_if_table2
type MIB_IF_TABLE2 struct {
	NumEntries uint32
	Table      [1]MIB_IF_ROW2
}

// MIB_INVERTEDIFSTACK_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_invertedifstack_row
type MIB_INVERTEDIFSTACK_ROW struct {
	LowerLayerInterfaceIndex  uint32
	HigherLayerInterfaceIndex uint32
}

// MIB_INVERTEDIFSTACK_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_invertedifstack_table
type MIB_INVERTEDIFSTACK_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_INVERTEDIFSTACK_ROW
}

// MIB_IPADDRROW_W2K: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipaddrrow_w2k
type MIB_IPADDRROW_W2K struct {
	DwAddr      uint32
	DwIndex     uint32
	DwMask      uint32
	DwBCastAddr uint32
	DwReasmSize uint32
	Unused1     uint16
	Unused2     uint16
}

// MIB_IPADDRROW_XP: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipaddrrow_xp
type MIB_IPADDRROW_XP struct {
	DwAddr      uint32
	DwIndex     uint32
	DwMask      uint32
	DwBCastAddr uint32
	DwReasmSize uint32
	Unused1     uint16
	WType       uint16
}

// MIB_IPADDRTABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipaddrtable
type MIB_IPADDRTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPADDRROW_XP
}

type MIB_IPDESTROW struct {
	ForwardRow          MIB_IPFORWARDROW
	DwForwardPreference uint32
	DwForwardViewSet    uint32
}

type MIB_IPDESTTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPDESTROW
}

// MIB_IPFORWARDNUMBER: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipforwardnumber
type MIB_IPFORWARDNUMBER struct {
	DwValue uint32
}

// MIB_IPFORWARDROW_Anonymous1_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPFORWARDROW_Anonymous1_e__Union struct {
	Data [1]uint32
}

// MIB_IPFORWARDROW_Anonymous2_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPFORWARDROW_Anonymous2_e__Union struct {
	Data [1]uint32
}

// MIB_IPFORWARDROW: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipforwardrow
type MIB_IPFORWARDROW struct {
	DwForwardDest      uint32
	DwForwardMask      uint32
	DwForwardPolicy    uint32
	DwForwardNextHop   uint32
	DwForwardIfIndex   uint32
	Anonymous1         uintptr
	Anonymous2         uintptr
	DwForwardAge       uint32
	DwForwardNextHopAS uint32
	DwForwardMetric1   uint32
	DwForwardMetric2   uint32
	DwForwardMetric3   uint32
	DwForwardMetric4   uint32
	DwForwardMetric5   uint32
}

// MIB_IPFORWARDTABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipforwardtable
type MIB_IPFORWARDTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPFORWARDROW
}

// MIB_IPFORWARD_ROW2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipforward_row2
type MIB_IPFORWARD_ROW2 struct {
	InterfaceLuid        networkmanagementndis.NET_LUID_LH
	InterfaceIndex       uint32
	DestinationPrefix    IP_ADDRESS_PREFIX
	NextHop              networkingwinsock.SOCKADDR_INET
	SitePrefixLength     byte
	ValidLifetime        uint32
	PreferredLifetime    uint32
	Metric               uint32
	Protocol             networkingwinsock.NL_ROUTE_PROTOCOL
	Loopback             foundation.BOOLEAN
	AutoconfigureAddress foundation.BOOLEAN
	Publish              foundation.BOOLEAN
	Immortal             foundation.BOOLEAN
	Age                  uint32
	Origin               networkingwinsock.NL_ROUTE_ORIGIN
}

// MIB_IPFORWARD_TABLE2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipforward_table2
type MIB_IPFORWARD_TABLE2 struct {
	NumEntries uint32
	Table      [1]MIB_IPFORWARD_ROW2
}

// MIB_IPINTERFACE_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipinterface_row
type MIB_IPINTERFACE_ROW struct {
	Family                               networkingwinsock.ADDRESS_FAMILY
	InterfaceLuid                        networkmanagementndis.NET_LUID_LH
	InterfaceIndex                       uint32
	MaxReassemblySize                    uint32
	InterfaceIdentifier                  uint64
	MinRouterAdvertisementInterval       uint32
	MaxRouterAdvertisementInterval       uint32
	AdvertisingEnabled                   foundation.BOOLEAN
	ForwardingEnabled                    foundation.BOOLEAN
	WeakHostSend                         foundation.BOOLEAN
	WeakHostReceive                      foundation.BOOLEAN
	UseAutomaticMetric                   foundation.BOOLEAN
	UseNeighborUnreachabilityDetection   foundation.BOOLEAN
	ManagedAddressConfigurationSupported foundation.BOOLEAN
	OtherStatefulConfigurationSupported  foundation.BOOLEAN
	AdvertiseDefaultRoute                foundation.BOOLEAN
	RouterDiscoveryBehavior              networkingwinsock.NL_ROUTER_DISCOVERY_BEHAVIOR
	DadTransmits                         uint32
	BaseReachableTime                    uint32
	RetransmitTime                       uint32
	PathMtuDiscoveryTimeout              uint32
	LinkLocalAddressBehavior             networkingwinsock.NL_LINK_LOCAL_ADDRESS_BEHAVIOR
	LinkLocalAddressTimeout              uint32
	ZoneIndices                          [16]uint32
	SitePrefixLength                     uint32
	Metric                               uint32
	NlMtu                                uint32
	Connected                            foundation.BOOLEAN
	SupportsWakeUpPatterns               foundation.BOOLEAN
	SupportsNeighborDiscovery            foundation.BOOLEAN
	SupportsRouterDiscovery              foundation.BOOLEAN
	ReachableTime                        uint32
	TransmitOffload                      networkingwinsock.NL_INTERFACE_OFFLOAD_ROD
	ReceiveOffload                       networkingwinsock.NL_INTERFACE_OFFLOAD_ROD
	DisableDefaultRoutes                 foundation.BOOLEAN
}

// MIB_IPINTERFACE_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipinterface_table
type MIB_IPINTERFACE_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_IPINTERFACE_ROW
}

// MIB_IPMCAST_BOUNDARY: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_ipmcast_boundary
type MIB_IPMCAST_BOUNDARY struct {
	DwIfIndex      uint32
	DwGroupAddress uint32
	DwGroupMask    uint32
	DwStatus       uint32
}

// MIB_IPMCAST_BOUNDARY_TABLE: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_ipmcast_boundary_table
type MIB_IPMCAST_BOUNDARY_TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPMCAST_BOUNDARY
}

// MIB_IPMCAST_GLOBAL: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_global
type MIB_IPMCAST_GLOBAL struct {
	DwEnable uint32
}

// MIB_IPMCAST_IF_ENTRY: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_if_entry
type MIB_IPMCAST_IF_ENTRY struct {
	DwIfIndex        uint32
	DwTtl            uint32
	DwProtocol       uint32
	DwRateLimit      uint32
	UlInMcastOctets  uint32
	UlOutMcastOctets uint32
}

// MIB_IPMCAST_IF_TABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_if_table
type MIB_IPMCAST_IF_TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPMCAST_IF_ENTRY
}

// MIB_IPMCAST_MFE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_mfe
type MIB_IPMCAST_MFE struct {
	DwGroup         uint32
	DwSource        uint32
	DwSrcMask       uint32
	DwUpStrmNgbr    uint32
	DwInIfIndex     uint32
	DwInIfProtocol  uint32
	DwRouteProtocol uint32
	DwRouteNetwork  uint32
	DwRouteMask     uint32
	UlUpTime        uint32
	UlExpiryTime    uint32
	UlTimeOut       uint32
	UlNumOutIf      uint32
	FFlags          uint32
	DwReserved      uint32
	RgmioOutInfo    [1]MIB_IPMCAST_OIF_XP
}

// MIB_IPMCAST_MFE_STATS: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_mfe_stats
type MIB_IPMCAST_MFE_STATS struct {
	DwGroup           uint32
	DwSource          uint32
	DwSrcMask         uint32
	DwUpStrmNgbr      uint32
	DwInIfIndex       uint32
	DwInIfProtocol    uint32
	DwRouteProtocol   uint32
	DwRouteNetwork    uint32
	DwRouteMask       uint32
	UlUpTime          uint32
	UlExpiryTime      uint32
	UlNumOutIf        uint32
	UlInPkts          uint32
	UlInOctets        uint32
	UlPktsDifferentIf uint32
	UlQueueOverflow   uint32
	RgmiosOutStats    [1]MIB_IPMCAST_OIF_STATS_LH
}

// MIB_IPMCAST_MFE_STATS_EX_XP: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_mfe_stats_ex_xp
type MIB_IPMCAST_MFE_STATS_EX_XP struct {
	DwGroup           uint32
	DwSource          uint32
	DwSrcMask         uint32
	DwUpStrmNgbr      uint32
	DwInIfIndex       uint32
	DwInIfProtocol    uint32
	DwRouteProtocol   uint32
	DwRouteNetwork    uint32
	DwRouteMask       uint32
	UlUpTime          uint32
	UlExpiryTime      uint32
	UlNumOutIf        uint32
	UlInPkts          uint32
	UlInOctets        uint32
	UlPktsDifferentIf uint32
	UlQueueOverflow   uint32
	UlUninitMfe       uint32
	UlNegativeMfe     uint32
	UlInDiscards      uint32
	UlInHdrErrors     uint32
	UlTotalOutPackets uint32
	RgmiosOutStats    [1]MIB_IPMCAST_OIF_STATS_LH
}

// MIB_IPMCAST_OIF_STATS_LH: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_oif_stats_lh
type MIB_IPMCAST_OIF_STATS_LH struct {
	DwOutIfIndex  uint32
	DwNextHopAddr uint32
	DwDialContext uint32
	UlTtlTooLow   uint32
	UlFragNeeded  uint32
	UlOutPackets  uint32
	UlOutDiscards uint32
}

// MIB_IPMCAST_OIF_STATS_W2K: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_oif_stats_w2k
type MIB_IPMCAST_OIF_STATS_W2K struct {
	DwOutIfIndex  uint32
	DwNextHopAddr uint32
	PvDialContext unsafe.Pointer
	UlTtlTooLow   uint32
	UlFragNeeded  uint32
	UlOutPackets  uint32
	UlOutDiscards uint32
}

// MIB_IPMCAST_OIF_W2K: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_oif_w2k
type MIB_IPMCAST_OIF_W2K struct {
	DwOutIfIndex  uint32
	DwNextHopAddr uint32
	PvReserved    unsafe.Pointer
	DwReserved    uint32
}

// MIB_IPMCAST_OIF_XP: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipmcast_oif_xp
type MIB_IPMCAST_OIF_XP struct {
	DwOutIfIndex  uint32
	DwNextHopAddr uint32
	DwReserved    uint32
	DwReserved1   uint32
}

// MIB_IPMCAST_SCOPE: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_ipmcast_scope
type MIB_IPMCAST_SCOPE struct {
	DwGroupAddress uint32
	DwGroupMask    uint32
	SnNameBuffer   [256]uint16
	DwStatus       uint32
}

// MIB_IPNETROW_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPNETROW_LH_Anonymous_e__Union struct {
	Data [1]uint32
}

// MIB_IPNETROW_LH: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipnetrow_lh
type MIB_IPNETROW_LH struct {
	DwIndex       uint32
	DwPhysAddrLen uint32
	BPhysAddr     [8]byte
	DwAddr        uint32
	Anonymous     uintptr
}

// MIB_IPNETROW_W2K: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipnetrow_w2k
type MIB_IPNETROW_W2K struct {
	DwIndex       uint32
	DwPhysAddrLen uint32
	BPhysAddr     [8]byte
	DwAddr        uint32
	DwType        uint32
}

// MIB_IPNETTABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipnettable
type MIB_IPNETTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPNETROW_LH
}

// MIB_IPNET_ROW2_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPNET_ROW2_Anonymous_e__Union struct {
	Data [1]uint64
}

// MIB_IPNET_ROW2_ReachabilityTime_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPNET_ROW2_ReachabilityTime_e__Union struct {
	Data [1]uint32
}

// MIB_IPNET_ROW2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipnet_row2
type MIB_IPNET_ROW2 struct {
	Address               networkingwinsock.SOCKADDR_INET
	InterfaceIndex        uint32
	InterfaceLuid         networkmanagementndis.NET_LUID_LH
	PhysicalAddress       [32]byte
	PhysicalAddressLength uint32
	State                 networkingwinsock.NL_NEIGHBOR_STATE
	Anonymous             uintptr
	ReachabilityTime      uintptr
}

// MIB_IPNET_TABLE2: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ipnet_table2
type MIB_IPNET_TABLE2 struct {
	NumEntries uint32
	Table      [1]MIB_IPNET_ROW2
}

// MIB_IPPATH_ROW_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPPATH_ROW_Anonymous_e__Union struct {
	Data [1]uint32
}

// MIB_IPPATH_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ippath_row
type MIB_IPPATH_ROW struct {
	Source            networkingwinsock.SOCKADDR_INET
	Destination       networkingwinsock.SOCKADDR_INET
	InterfaceLuid     networkmanagementndis.NET_LUID_LH
	InterfaceIndex    uint32
	CurrentNextHop    networkingwinsock.SOCKADDR_INET
	PathMtu           uint32
	RttMean           uint32
	RttDeviation      uint32
	Anonymous         uintptr
	IsReachable       foundation.BOOLEAN
	LinkTransmitSpeed uint64
	LinkReceiveSpeed  uint64
}

// MIB_IPPATH_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ippath_table
type MIB_IPPATH_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_IPPATH_ROW
}

// MIB_IPSTATS_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_IPSTATS_LH_Anonymous_e__Union struct {
	Data [1]uint32
}

// MIB_IPSTATS_LH: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipstats_lh
type MIB_IPSTATS_LH struct {
	Anonymous         uintptr
	DwDefaultTTL      uint32
	DwInReceives      uint32
	DwInHdrErrors     uint32
	DwInAddrErrors    uint32
	DwForwDatagrams   uint32
	DwInUnknownProtos uint32
	DwInDiscards      uint32
	DwInDelivers      uint32
	DwOutRequests     uint32
	DwRoutingDiscards uint32
	DwOutDiscards     uint32
	DwOutNoRoutes     uint32
	DwReasmTimeout    uint32
	DwReasmReqds      uint32
	DwReasmOks        uint32
	DwReasmFails      uint32
	DwFragOks         uint32
	DwFragFails       uint32
	DwFragCreates     uint32
	DwNumIf           uint32
	DwNumAddr         uint32
	DwNumRoutes       uint32
}

// MIB_IPSTATS_W2K: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_ipstats_w2k
type MIB_IPSTATS_W2K struct {
	DwForwarding      uint32
	DwDefaultTTL      uint32
	DwInReceives      uint32
	DwInHdrErrors     uint32
	DwInAddrErrors    uint32
	DwForwDatagrams   uint32
	DwInUnknownProtos uint32
	DwInDiscards      uint32
	DwInDelivers      uint32
	DwOutRequests     uint32
	DwRoutingDiscards uint32
	DwOutDiscards     uint32
	DwOutNoRoutes     uint32
	DwReasmTimeout    uint32
	DwReasmReqds      uint32
	DwReasmOks        uint32
	DwReasmFails      uint32
	DwFragOks         uint32
	DwFragFails       uint32
	DwFragCreates     uint32
	DwNumIf           uint32
	DwNumAddr         uint32
	DwNumRoutes       uint32
}

// MIB_IP_NETWORK_CONNECTION_BANDWIDTH_ESTIMATES: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_ip_network_connection_bandwidth_estimates
type MIB_IP_NETWORK_CONNECTION_BANDWIDTH_ESTIMATES struct {
	InboundBandwidthInformation  networkingwinsock.NL_BANDWIDTH_INFORMATION
	OutboundBandwidthInformation networkingwinsock.NL_BANDWIDTH_INFORMATION
}

// MIB_MCAST_LIMIT_ROW: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_mcast_limit_row
type MIB_MCAST_LIMIT_ROW struct {
	DwTtl       uint32
	DwRateLimit uint32
}

// MIB_MFE_STATS_TABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_mfe_stats_table
type MIB_MFE_STATS_TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPMCAST_MFE_STATS
}

// MIB_MFE_STATS_TABLE_EX_XP: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_mfe_stats_table_ex_xp
type MIB_MFE_STATS_TABLE_EX_XP struct {
	DwNumEntries uint32
	Table        [1]*MIB_IPMCAST_MFE_STATS_EX_XP
}

// MIB_MFE_TABLE: https://learn.microsoft.com/windows/win32/api/ipmib/ns-ipmib-mib_mfe_table
type MIB_MFE_TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_IPMCAST_MFE
}

// MIB_MULTICASTIPADDRESS_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_multicastipaddress_row
type MIB_MULTICASTIPADDRESS_ROW struct {
	Address        networkingwinsock.SOCKADDR_INET
	InterfaceIndex uint32
	InterfaceLuid  networkmanagementndis.NET_LUID_LH
	ScopeId        networkingwinsock.SCOPE_ID
}

// MIB_MULTICASTIPADDRESS_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_multicastipaddress_table
type MIB_MULTICASTIPADDRESS_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_MULTICASTIPADDRESS_ROW
}

// MIB_OPAQUE_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_OPAQUE_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

// MIB_OPAQUE_INFO: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_opaque_info
type MIB_OPAQUE_INFO struct {
	DwId      uint32
	Anonymous uintptr
}

// MIB_OPAQUE_QUERY: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_opaque_query
type MIB_OPAQUE_QUERY struct {
	DwVarId      uint32
	RgdwVarIndex [1]uint32
}

// MIB_PROXYARP: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-mib_proxyarp
type MIB_PROXYARP struct {
	DwAddress uint32
	DwMask    uint32
	DwIfIndex uint32
}

type MIB_ROUTESTATE struct {
	BRoutesSetToStack foundation.BOOL
}

// MIB_TCP6ROW: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6row
type MIB_TCP6ROW struct {
	State           MIB_TCP_STATE
	LocalAddr       networkingwinsock.IN6_ADDR
	DwLocalScopeId  uint32
	DwLocalPort     uint32
	RemoteAddr      networkingwinsock.IN6_ADDR
	DwRemoteScopeId uint32
	DwRemotePort    uint32
}

// MIB_TCP6ROW2: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6row2
type MIB_TCP6ROW2 struct {
	LocalAddr       networkingwinsock.IN6_ADDR
	DwLocalScopeId  uint32
	DwLocalPort     uint32
	RemoteAddr      networkingwinsock.IN6_ADDR
	DwRemoteScopeId uint32
	DwRemotePort    uint32
	State           MIB_TCP_STATE
	DwOwningPid     uint32
	DwOffloadState  TCP_CONNECTION_OFFLOAD_STATE
}

// MIB_TCP6ROW_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6row_owner_module
type MIB_TCP6ROW_OWNER_MODULE struct {
	UcLocalAddr       [16]byte
	DwLocalScopeId    uint32
	DwLocalPort       uint32
	UcRemoteAddr      [16]byte
	DwRemoteScopeId   uint32
	DwRemotePort      uint32
	DwState           uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	OwningModuleInfo  [16]uint64
}

// MIB_TCP6ROW_OWNER_PID: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6row_owner_pid
type MIB_TCP6ROW_OWNER_PID struct {
	UcLocalAddr     [16]byte
	DwLocalScopeId  uint32
	DwLocalPort     uint32
	UcRemoteAddr    [16]byte
	DwRemoteScopeId uint32
	DwRemotePort    uint32
	DwState         uint32
	DwOwningPid     uint32
}

// MIB_TCP6TABLE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6table
type MIB_TCP6TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_TCP6ROW
}

// MIB_TCP6TABLE2: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6table2
type MIB_TCP6TABLE2 struct {
	DwNumEntries uint32
	Table        [1]MIB_TCP6ROW2
}

// MIB_TCP6TABLE_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6table_owner_module
type MIB_TCP6TABLE_OWNER_MODULE struct {
	DwNumEntries uint32
	Table        [1]MIB_TCP6ROW_OWNER_MODULE
}

// MIB_TCP6TABLE_OWNER_PID: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcp6table_owner_pid
type MIB_TCP6TABLE_OWNER_PID struct {
	DwNumEntries uint32
	Table        [1]MIB_TCP6ROW_OWNER_PID
}

// MIB_TCPROW2: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow2
type MIB_TCPROW2 struct {
	DwState        uint32
	DwLocalAddr    uint32
	DwLocalPort    uint32
	DwRemoteAddr   uint32
	DwRemotePort   uint32
	DwOwningPid    uint32
	DwOffloadState TCP_CONNECTION_OFFLOAD_STATE
}

// MIB_TCPROW_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_TCPROW_LH_Anonymous_e__Union struct {
	Data [1]uint32
}

// MIB_TCPROW_LH: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_lh
type MIB_TCPROW_LH struct {
	Anonymous    uintptr
	DwLocalAddr  uint32
	DwLocalPort  uint32
	DwRemoteAddr uint32
	DwRemotePort uint32
}

// MIB_TCPROW_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_owner_module
type MIB_TCPROW_OWNER_MODULE struct {
	DwState           uint32
	DwLocalAddr       uint32
	DwLocalPort       uint32
	DwRemoteAddr      uint32
	DwRemotePort      uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	OwningModuleInfo  [16]uint64
}

// MIB_TCPROW_OWNER_PID: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_owner_pid
type MIB_TCPROW_OWNER_PID struct {
	DwState      uint32
	DwLocalAddr  uint32
	DwLocalPort  uint32
	DwRemoteAddr uint32
	DwRemotePort uint32
	DwOwningPid  uint32
}

// MIB_TCPROW_W2K: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_w2k
type MIB_TCPROW_W2K struct {
	DwState      uint32
	DwLocalAddr  uint32
	DwLocalPort  uint32
	DwRemoteAddr uint32
	DwRemotePort uint32
}

// MIB_TCPSTATS2: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcpstats2
type MIB_TCPSTATS2 struct {
	RtoAlgorithm   TCP_RTO_ALGORITHM
	DwRtoMin       uint32
	DwRtoMax       uint32
	DwMaxConn      uint32
	DwActiveOpens  uint32
	DwPassiveOpens uint32
	DwAttemptFails uint32
	DwEstabResets  uint32
	DwCurrEstab    uint32
	Dw64InSegs     uint64
	Dw64OutSegs    uint64
	DwRetransSegs  uint32
	DwInErrs       uint32
	DwOutRsts      uint32
	DwNumConns     uint32
}

// MIB_TCPSTATS_LH_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_TCPSTATS_LH_Anonymous_e__Union struct {
	Data [1]uint32
}

// MIB_TCPSTATS_LH: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcpstats_lh
type MIB_TCPSTATS_LH struct {
	Anonymous      uintptr
	DwRtoMin       uint32
	DwRtoMax       uint32
	DwMaxConn      uint32
	DwActiveOpens  uint32
	DwPassiveOpens uint32
	DwAttemptFails uint32
	DwEstabResets  uint32
	DwCurrEstab    uint32
	DwInSegs       uint32
	DwOutSegs      uint32
	DwRetransSegs  uint32
	DwInErrs       uint32
	DwOutRsts      uint32
	DwNumConns     uint32
}

// MIB_TCPSTATS_W2K: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcpstats_w2k
type MIB_TCPSTATS_W2K struct {
	DwRtoAlgorithm uint32
	DwRtoMin       uint32
	DwRtoMax       uint32
	DwMaxConn      uint32
	DwActiveOpens  uint32
	DwPassiveOpens uint32
	DwAttemptFails uint32
	DwEstabResets  uint32
	DwCurrEstab    uint32
	DwInSegs       uint32
	DwOutSegs      uint32
	DwRetransSegs  uint32
	DwInErrs       uint32
	DwOutRsts      uint32
	DwNumConns     uint32
}

// MIB_TCPTABLE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcptable
type MIB_TCPTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_TCPROW_LH
}

// MIB_TCPTABLE2: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcptable2
type MIB_TCPTABLE2 struct {
	DwNumEntries uint32
	Table        [1]MIB_TCPROW2
}

// MIB_TCPTABLE_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcptable_owner_module
type MIB_TCPTABLE_OWNER_MODULE struct {
	DwNumEntries uint32
	Table        [1]MIB_TCPROW_OWNER_MODULE
}

// MIB_TCPTABLE_OWNER_PID: https://learn.microsoft.com/windows/win32/api/tcpmib/ns-tcpmib-mib_tcptable_owner_pid
type MIB_TCPTABLE_OWNER_PID struct {
	DwNumEntries uint32
	Table        [1]MIB_TCPROW_OWNER_PID
}

// MIB_UDP6ROW: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6row
type MIB_UDP6ROW struct {
	DwLocalAddr    networkingwinsock.IN6_ADDR
	DwLocalScopeId uint32
	DwLocalPort    uint32
}

// MIB_UDP6ROW2_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_UDP6ROW2_Anonymous_e__Union struct {
	Data [1]uint64
}

type MIB_UDP6ROW2 struct {
	UcLocalAddr       [16]byte
	DwLocalScopeId    uint32
	DwLocalPort       uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	Anonymous         uintptr
	OwningModuleInfo  [16]uint64
	UcRemoteAddr      [16]byte
	DwRemoteScopeId   uint32
	DwRemotePort      uint32
}

// MIB_UDP6ROW_OWNER_MODULE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_UDP6ROW_OWNER_MODULE_Anonymous_e__Union struct {
	Data [1]uint64
}

// MIB_UDP6ROW_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6row_owner_module
type MIB_UDP6ROW_OWNER_MODULE struct {
	UcLocalAddr       [16]byte
	DwLocalScopeId    uint32
	DwLocalPort       uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	Anonymous         uintptr
	OwningModuleInfo  [16]uint64
}

// MIB_UDP6ROW_OWNER_PID: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6row_owner_pid
type MIB_UDP6ROW_OWNER_PID struct {
	UcLocalAddr    [16]byte
	DwLocalScopeId uint32
	DwLocalPort    uint32
	DwOwningPid    uint32
}

// MIB_UDP6TABLE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6table
type MIB_UDP6TABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_UDP6ROW
}

type MIB_UDP6TABLE2 struct {
	DwNumEntries uint32
	Table        [1]MIB_UDP6ROW2
}

// MIB_UDP6TABLE_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6table_owner_module
type MIB_UDP6TABLE_OWNER_MODULE struct {
	DwNumEntries uint32
	Table        [1]MIB_UDP6ROW_OWNER_MODULE
}

// MIB_UDP6TABLE_OWNER_PID: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udp6table_owner_pid
type MIB_UDP6TABLE_OWNER_PID struct {
	DwNumEntries uint32
	Table        [1]MIB_UDP6ROW_OWNER_PID
}

// MIB_UDPROW: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udprow
type MIB_UDPROW struct {
	DwLocalAddr uint32
	DwLocalPort uint32
}

// MIB_UDPROW2_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_UDPROW2_Anonymous_e__Union struct {
	Data [1]uint64
}

type MIB_UDPROW2 struct {
	DwLocalAddr       uint32
	DwLocalPort       uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	Anonymous         uintptr
	OwningModuleInfo  [16]uint64
	DwRemoteAddr      uint32
	DwRemotePort      uint32
}

// MIB_UDPROW_OWNER_MODULE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIB_UDPROW_OWNER_MODULE_Anonymous_e__Union struct {
	Data [1]uint64
}

// MIB_UDPROW_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udprow_owner_module
type MIB_UDPROW_OWNER_MODULE struct {
	DwLocalAddr       uint32
	DwLocalPort       uint32
	DwOwningPid       uint32
	LiCreateTimestamp int64
	Anonymous         uintptr
	OwningModuleInfo  [16]uint64
}

// MIB_UDPROW_OWNER_PID: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udprow_owner_pid
type MIB_UDPROW_OWNER_PID struct {
	DwLocalAddr uint32
	DwLocalPort uint32
	DwOwningPid uint32
}

// MIB_UDPSTATS: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udpstats
type MIB_UDPSTATS struct {
	DwInDatagrams  uint32
	DwNoPorts      uint32
	DwInErrors     uint32
	DwOutDatagrams uint32
	DwNumAddrs     uint32
}

// MIB_UDPSTATS2: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udpstats2
type MIB_UDPSTATS2 struct {
	Dw64InDatagrams  uint64
	DwNoPorts        uint32
	DwInErrors       uint32
	Dw64OutDatagrams uint64
	DwNumAddrs       uint32
}

// MIB_UDPTABLE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udptable
type MIB_UDPTABLE struct {
	DwNumEntries uint32
	Table        [1]MIB_UDPROW
}

type MIB_UDPTABLE2 struct {
	DwNumEntries uint32
	Table        [1]MIB_UDPROW2
}

// MIB_UDPTABLE_OWNER_MODULE: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udptable_owner_module
type MIB_UDPTABLE_OWNER_MODULE struct {
	DwNumEntries uint32
	Table        [1]MIB_UDPROW_OWNER_MODULE
}

// MIB_UDPTABLE_OWNER_PID: https://learn.microsoft.com/windows/win32/api/udpmib/ns-udpmib-mib_udptable_owner_pid
type MIB_UDPTABLE_OWNER_PID struct {
	DwNumEntries uint32
	Table        [1]MIB_UDPROW_OWNER_PID
}

// MIB_UNICASTIPADDRESS_ROW: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_unicastipaddress_row
type MIB_UNICASTIPADDRESS_ROW struct {
	Address            networkingwinsock.SOCKADDR_INET
	InterfaceLuid      networkmanagementndis.NET_LUID_LH
	InterfaceIndex     uint32
	PrefixOrigin       networkingwinsock.NL_PREFIX_ORIGIN
	SuffixOrigin       networkingwinsock.NL_SUFFIX_ORIGIN
	ValidLifetime      uint32
	PreferredLifetime  uint32
	OnLinkPrefixLength byte
	SkipAsSource       foundation.BOOLEAN
	DadState           networkingwinsock.NL_DAD_STATE
	ScopeId            networkingwinsock.SCOPE_ID
	CreationTimeStamp  int64
}

// MIB_UNICASTIPADDRESS_TABLE: https://learn.microsoft.com/windows/win32/api/netioapi/ns-netioapi-mib_unicastipaddress_table
type MIB_UNICASTIPADDRESS_TABLE struct {
	NumEntries uint32
	Table      [1]MIB_UNICASTIPADDRESS_ROW
}

// NET_ADDRESS_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type NET_ADDRESS_INFO_Anonymous_e__Union struct {
	Data [3]uint64
}

// NET_ADDRESS_INFO: https://learn.microsoft.com/windows/win32/api/iphlpapi/ns-iphlpapi-net_address_info
type NET_ADDRESS_INFO struct {
	Format    NET_ADDRESS_FORMAT
	Anonymous uintptr
}

type PFLOGFRAME struct {
	Timestamp             int64
	PfeTypeOfFrame        PFFRAMETYPE
	DwTotalSizeUsed       uint32
	DwFilterRule          uint32
	WSizeOfAdditionalData uint16
	WSizeOfIpHeader       uint16
	DwInterfaceName       uint32
	DwIPIndex             uint32
	BPacketData           [1]byte
}

type PF_FILTER_DESCRIPTOR struct {
	DwFilterFlags     uint32
	DwRule            uint32
	PfatType          PFADDRESSTYPE
	SrcAddr           *byte
	SrcMask           *byte
	DstAddr           *byte
	DstMask           *byte
	DwProtocol        uint32
	FLateBound        uint32
	WSrcPort          uint16
	WDstPort          uint16
	WSrcPortHighRange uint16
	WDstPortHighRange uint16
}

type PF_FILTER_STATS struct {
	DwNumPacketsFiltered uint32
	Info                 PF_FILTER_DESCRIPTOR
}

type PF_INTERFACE_STATS struct {
	PvDriverContext  unsafe.Pointer
	DwFlags          uint32
	DwInDrops        uint32
	DwOutDrops       uint32
	EaInAction       PFFORWARD_ACTION
	EaOutAction      PFFORWARD_ACTION
	DwNumInFilters   uint32
	DwNumOutFilters  uint32
	DwFrag           uint32
	DwSpoof          uint32
	DwReserved1      uint32
	DwReserved2      uint32
	LiSYN            int64
	LiTotalLogged    int64
	DwLostLogEntries uint32
	FilterInfo       [1]PF_FILTER_STATS
}

type PF_LATEBIND_INFO struct {
	SrcAddr *byte
	DstAddr *byte
	Mask    *byte
}

// TCPIP_OWNER_MODULE_BASIC_INFO: https://learn.microsoft.com/windows/win32/api/iprtrmib/ns-iprtrmib-tcpip_owner_module_basic_info
type TCPIP_OWNER_MODULE_BASIC_INFO struct {
	PModuleName foundation.PWSTR
	PModulePath foundation.PWSTR
}

// TCP_ESTATS_BANDWIDTH_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_bandwidth_rod_v0
type TCP_ESTATS_BANDWIDTH_ROD_v0 struct {
	OutboundBandwidth       uint64
	InboundBandwidth        uint64
	OutboundInstability     uint64
	InboundInstability      uint64
	OutboundBandwidthPeaked foundation.BOOLEAN
	InboundBandwidthPeaked  foundation.BOOLEAN
}

// TCP_ESTATS_BANDWIDTH_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_bandwidth_rw_v0
type TCP_ESTATS_BANDWIDTH_RW_v0 struct {
	EnableCollectionOutbound TCP_BOOLEAN_OPTIONAL
	EnableCollectionInbound  TCP_BOOLEAN_OPTIONAL
}

// TCP_ESTATS_DATA_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_data_rod_v0
type TCP_ESTATS_DATA_ROD_v0 struct {
	DataBytesOut      uint64
	DataSegsOut       uint64
	DataBytesIn       uint64
	DataSegsIn        uint64
	SegsOut           uint64
	SegsIn            uint64
	SoftErrors        uint32
	SoftErrorReason   uint32
	SndUna            uint32
	SndNxt            uint32
	SndMax            uint32
	ThruBytesAcked    uint64
	RcvNxt            uint32
	ThruBytesReceived uint64
}

// TCP_ESTATS_DATA_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_data_rw_v0
type TCP_ESTATS_DATA_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_FINE_RTT_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_fine_rtt_rod_v0
type TCP_ESTATS_FINE_RTT_ROD_v0 struct {
	RttVar uint32
	MaxRtt uint32
	MinRtt uint32
	SumRtt uint32
}

// TCP_ESTATS_FINE_RTT_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_fine_rtt_rw_v0
type TCP_ESTATS_FINE_RTT_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_OBS_REC_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_obs_rec_rod_v0
type TCP_ESTATS_OBS_REC_ROD_v0 struct {
	CurRwinRcvd  uint32
	MaxRwinRcvd  uint32
	MinRwinRcvd  uint32
	WinScaleRcvd byte
}

// TCP_ESTATS_OBS_REC_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_obs_rec_rw_v0
type TCP_ESTATS_OBS_REC_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_PATH_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_path_rod_v0
type TCP_ESTATS_PATH_ROD_v0 struct {
	FastRetran            uint32
	Timeouts              uint32
	SubsequentTimeouts    uint32
	CurTimeoutCount       uint32
	AbruptTimeouts        uint32
	PktsRetrans           uint32
	BytesRetrans          uint32
	DupAcksIn             uint32
	SacksRcvd             uint32
	SackBlocksRcvd        uint32
	CongSignals           uint32
	PreCongSumCwnd        uint32
	PreCongSumRtt         uint32
	PostCongSumRtt        uint32
	PostCongCountRtt      uint32
	EcnSignals            uint32
	EceRcvd               uint32
	SendStall             uint32
	QuenchRcvd            uint32
	RetranThresh          uint32
	SndDupAckEpisodes     uint32
	SumBytesReordered     uint32
	NonRecovDa            uint32
	NonRecovDaEpisodes    uint32
	AckAfterFr            uint32
	DsackDups             uint32
	SampleRtt             uint32
	SmoothedRtt           uint32
	RttVar                uint32
	MaxRtt                uint32
	MinRtt                uint32
	SumRtt                uint32
	CountRtt              uint32
	CurRto                uint32
	MaxRto                uint32
	MinRto                uint32
	CurMss                uint32
	MaxMss                uint32
	MinMss                uint32
	SpuriousRtoDetections uint32
}

// TCP_ESTATS_PATH_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_path_rw_v0
type TCP_ESTATS_PATH_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_REC_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_rec_rod_v0
type TCP_ESTATS_REC_ROD_v0 struct {
	CurRwinSent    uint32
	MaxRwinSent    uint32
	MinRwinSent    uint32
	LimRwin        uint32
	DupAckEpisodes uint32
	DupAcksOut     uint32
	CeRcvd         uint32
	EcnSent        uint32
	EcnNoncesRcvd  uint32
	CurReasmQueue  uint32
	MaxReasmQueue  uint32
	CurAppRQueue   uintptr
	MaxAppRQueue   uintptr
	WinScaleSent   byte
}

// TCP_ESTATS_REC_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_rec_rw_v0
type TCP_ESTATS_REC_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_SEND_BUFF_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_send_buff_rod_v0
type TCP_ESTATS_SEND_BUFF_ROD_v0 struct {
	CurRetxQueue uintptr
	MaxRetxQueue uintptr
	CurAppWQueue uintptr
	MaxAppWQueue uintptr
}

// TCP_ESTATS_SEND_BUFF_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_send_buff_rw_v0
type TCP_ESTATS_SEND_BUFF_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_SND_CONG_ROD_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_snd_cong_rod_v0
type TCP_ESTATS_SND_CONG_ROD_v0 struct {
	SndLimTransRwin uint32
	SndLimTimeRwin  uint32
	SndLimBytesRwin uintptr
	SndLimTransCwnd uint32
	SndLimTimeCwnd  uint32
	SndLimBytesCwnd uintptr
	SndLimTransSnd  uint32
	SndLimTimeSnd   uint32
	SndLimBytesSnd  uintptr
	SlowStart       uint32
	CongAvoid       uint32
	OtherReductions uint32
	CurCwnd         uint32
	MaxSsCwnd       uint32
	MaxCaCwnd       uint32
	CurSsthresh     uint32
	MaxSsthresh     uint32
	MinSsthresh     uint32
}

// TCP_ESTATS_SND_CONG_ROS_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_snd_cong_ros_v0
type TCP_ESTATS_SND_CONG_ROS_v0 struct {
	LimCwnd uint32
}

// TCP_ESTATS_SND_CONG_RW_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_snd_cong_rw_v0
type TCP_ESTATS_SND_CONG_RW_v0 struct {
	EnableCollection foundation.BOOLEAN
}

// TCP_ESTATS_SYN_OPTS_ROS_v0: https://learn.microsoft.com/windows/win32/api/tcpestats/ns-tcpestats-tcp_estats_syn_opts_ros_v0
type TCP_ESTATS_SYN_OPTS_ROS_v0 struct {
	ActiveOpen foundation.BOOLEAN
	MssRcvd    uint32
	MssSent    uint32
}

// TCP_RESERVE_PORT_RANGE: https://learn.microsoft.com/windows/win32/api/ipexport/ns-ipexport-tcp_reserve_port_range
type TCP_RESERVE_PORT_RANGE struct {
	UpperRange uint16
	LowerRange uint16
}

// PINTERFACE_TIMESTAMP_CONFIG_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type PINTERFACE_TIMESTAMP_CONFIG_CHANGE_CALLBACK uintptr

// PIPFORWARD_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *MIB_IPFORWARD_ROW2, MIB_NOTIFICATION_TYPE).
type PIPFORWARD_CHANGE_CALLBACK uintptr

// PIPINTERFACE_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *MIB_IPINTERFACE_ROW, MIB_NOTIFICATION_TYPE).
type PIPINTERFACE_CHANGE_CALLBACK uintptr

// PNETWORK_CONNECTIVITY_HINT_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, networkingwinsock.NL_NETWORK_CONNECTIVITY_HINT).
type PNETWORK_CONNECTIVITY_HINT_CHANGE_CALLBACK uintptr

// PSTABLE_UNICAST_IPADDRESS_TABLE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *MIB_UNICASTIPADDRESS_TABLE).
type PSTABLE_UNICAST_IPADDRESS_TABLE_CALLBACK uintptr

// PTEREDO_PORT_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, uint16, MIB_NOTIFICATION_TYPE).
type PTEREDO_PORT_CHANGE_CALLBACK uintptr

// PUNICAST_IPADDRESS_CHANGE_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *MIB_UNICASTIPADDRESS_ROW, MIB_NOTIFICATION_TYPE).
type PUNICAST_IPADDRESS_CHANGE_CALLBACK uintptr
