// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows

package cabinets

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	storagecabinets "github.com/deploymenttheory/go-bindings-win32/bindings/win32/storage/cabinets"
)

// FCIAddFile wraps the raw FCIAddFile call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fci/nf-fci-fciaddfile
func FCIAddFile(hfci unsafe.Pointer, pszSourceFile foundation.PSTR, pszFileName foundation.PSTR, fExecute bool, pfnfcignc storagecabinets.PFNFCIGETNEXTCABINET, pfnfcis storagecabinets.PFNFCISTATUS, pfnfcigoi storagecabinets.PFNFCIGETOPENINFO, typeCompress uint16) bool {
	_fExecute := foundation.BOOL(win32.Bool32(fExecute))
	return storagecabinets.FCIAddFile(hfci, pszSourceFile, pszFileName, _fExecute, pfnfcignc, pfnfcis, pfnfcigoi, typeCompress) != 0
}

// FCIDestroy wraps the raw FCIDestroy call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fci/nf-fci-fcidestroy
func FCIDestroy(hfci unsafe.Pointer) bool {
	return storagecabinets.FCIDestroy(hfci) != 0
}

// FCIFlushCabinet wraps the raw FCIFlushCabinet call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fci/nf-fci-fciflushcabinet
func FCIFlushCabinet(hfci unsafe.Pointer, fGetNextCab bool, pfnfcignc storagecabinets.PFNFCIGETNEXTCABINET, pfnfcis storagecabinets.PFNFCISTATUS) bool {
	_fGetNextCab := foundation.BOOL(win32.Bool32(fGetNextCab))
	return storagecabinets.FCIFlushCabinet(hfci, _fGetNextCab, pfnfcignc, pfnfcis) != 0
}

// FCIFlushFolder wraps the raw FCIFlushFolder call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fci/nf-fci-fciflushfolder
func FCIFlushFolder(hfci unsafe.Pointer, pfnfcignc storagecabinets.PFNFCIGETNEXTCABINET, pfnfcis storagecabinets.PFNFCISTATUS) bool {
	return storagecabinets.FCIFlushFolder(hfci, pfnfcignc, pfnfcis) != 0
}

// FDICopy wraps the raw FDICopy call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fdi/nf-fdi-fdicopy
func FDICopy(hfdi unsafe.Pointer, pszCabinet foundation.PSTR, pszCabPath foundation.PSTR, flags int32, pfnfdin storagecabinets.PFNFDINOTIFY, pfnfdid storagecabinets.PFNFDIDECRYPT, pvUser unsafe.Pointer) bool {
	return storagecabinets.FDICopy(hfdi, pszCabinet, pszCabPath, flags, pfnfdin, pfnfdid, pvUser) != 0
}

// FDIDestroy wraps the raw FDIDestroy call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fdi/nf-fdi-fdidestroy
func FDIDestroy(hfdi unsafe.Pointer) bool {
	return storagecabinets.FDIDestroy(hfdi) != 0
}

// FDIIsCabinet wraps the raw FDIIsCabinet call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fdi/nf-fdi-fdiiscabinet
func FDIIsCabinet(hfdi unsafe.Pointer, hf uintptr, pfdici *storagecabinets.FDICABINETINFO) bool {
	return storagecabinets.FDIIsCabinet(hfdi, hf, pfdici) != 0
}

// FDITruncateCabinet wraps the raw FDITruncateCabinet call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/fdi/nf-fdi-fditruncatecabinet
func FDITruncateCabinet(hfdi unsafe.Pointer, pszCabinetName foundation.PSTR, iFolderToDelete uint16) bool {
	return storagecabinets.FDITruncateCabinet(hfdi, pszCabinetName, iFolderToDelete) != 0
}
