// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package xps

import (
	storagexps "github.com/deploymenttheory/go-bindings-win32/bindings/win32/storage/xps"
)

type ABORTPROC = storagexps.ABORTPROC
type DOCINFOA = storagexps.DOCINFOA
type DOCINFOW = storagexps.DOCINFOW
type DRAWPATRECT = storagexps.DRAWPATRECT
type PRINTER_DEVICE_CAPABILITIES = storagexps.PRINTER_DEVICE_CAPABILITIES
type PRINT_WINDOW_FLAGS = storagexps.PRINT_WINDOW_FLAGS
type PSFEATURE_CUSTPAPER = storagexps.PSFEATURE_CUSTPAPER
type PSFEATURE_OUTPUT = storagexps.PSFEATURE_OUTPUT
type PSINJECTDATA = storagexps.PSINJECTDATA
type PSINJECT_POINT = storagexps.PSINJECT_POINT
type XPS_COLOR = storagexps.XPS_COLOR
type XPS_COLOR_INTERPOLATION = storagexps.XPS_COLOR_INTERPOLATION
type XPS_COLOR_TYPE = storagexps.XPS_COLOR_TYPE
type XPS_COLOR_XPS_COLOR_VALUE = storagexps.XPS_COLOR_XPS_COLOR_VALUE
type XPS_DASH = storagexps.XPS_DASH
type XPS_DASH_CAP = storagexps.XPS_DASH_CAP
type XPS_DOCUMENT_TYPE = storagexps.XPS_DOCUMENT_TYPE
type XPS_FILL_RULE = storagexps.XPS_FILL_RULE
type XPS_FONT_EMBEDDING = storagexps.XPS_FONT_EMBEDDING
type XPS_GLYPH_INDEX = storagexps.XPS_GLYPH_INDEX
type XPS_GLYPH_MAPPING = storagexps.XPS_GLYPH_MAPPING
type XPS_IMAGE_TYPE = storagexps.XPS_IMAGE_TYPE
type XPS_INTERLEAVING = storagexps.XPS_INTERLEAVING
type XPS_LINE_CAP = storagexps.XPS_LINE_CAP
type XPS_LINE_JOIN = storagexps.XPS_LINE_JOIN
type XPS_MATRIX = storagexps.XPS_MATRIX
type XPS_OBJECT_TYPE = storagexps.XPS_OBJECT_TYPE
type XPS_POINT = storagexps.XPS_POINT
type XPS_RECT = storagexps.XPS_RECT
type XPS_SEGMENT_STROKE_PATTERN = storagexps.XPS_SEGMENT_STROKE_PATTERN
type XPS_SEGMENT_TYPE = storagexps.XPS_SEGMENT_TYPE
type XPS_SIGNATURE_STATUS = storagexps.XPS_SIGNATURE_STATUS
type XPS_SIGN_FLAGS = storagexps.XPS_SIGN_FLAGS
type XPS_SIGN_POLICY = storagexps.XPS_SIGN_POLICY
type XPS_SIZE = storagexps.XPS_SIZE
type XPS_SPREAD_METHOD = storagexps.XPS_SPREAD_METHOD
type XPS_STYLE_SIMULATION = storagexps.XPS_STYLE_SIMULATION
type XPS_THUMBNAIL_SIZE = storagexps.XPS_THUMBNAIL_SIZE
type XPS_TILE_MODE = storagexps.XPS_TILE_MODE
type XpsOMObjectFactory = storagexps.XpsOMObjectFactory
type XpsOMThumbnailGenerator = storagexps.XpsOMThumbnailGenerator
type XpsSignatureManager = storagexps.XpsSignatureManager
