// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package display

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	graphicsgdi "github.com/deploymenttheory/go-bindings-win32/bindings/win32/graphics/gdi"
	systemconsole "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/console"
)

// Invalid values: -1, 0.
type DHPDEV uintptr

// Invalid values: -1, 0.
type DHSURF uintptr

// Invalid values: -1, 0.
type HBM uintptr

// Invalid values: -1, 0.
type HDEV uintptr

// Invalid values: -1, 0.
type HDRVOBJ uintptr

// Invalid values: -1, 0.
type HFASTMUTEX uintptr

// Release with EngDeleteSemaphore.
// Invalid values: -1, 0.
type HSEMAPHORE uintptr

// Invalid values: -1, 0.
type HSURF uintptr

// AR_STATE: https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-ar_state
type AR_STATE int32

const (
	AR_ENABLED       AR_STATE = 0
	AR_DISABLED      AR_STATE = 1
	AR_SUPPRESSED    AR_STATE = 2
	AR_REMOTESESSION AR_STATE = 4
	AR_MULTIMON      AR_STATE = 8
	AR_NOSENSOR      AR_STATE = 16
	AR_NOT_SUPPORTED AR_STATE = 32
	AR_DOCKED        AR_STATE = 64
	AR_LAPTOP        AR_STATE = 128
)

type BACKLIGHT_OPTIMIZATION_LEVEL int32

const (
	BacklightOptimizationDisable BACKLIGHT_OPTIMIZATION_LEVEL = 0
	BacklightOptimizationDesktop BACKLIGHT_OPTIMIZATION_LEVEL = 1
	BacklightOptimizationDynamic BACKLIGHT_OPTIMIZATION_LEVEL = 2
	BacklightOptimizationDimmed  BACKLIGHT_OPTIMIZATION_LEVEL = 3
	BacklightOptimizationEDR     BACKLIGHT_OPTIMIZATION_LEVEL = 4
)

type BRIGHTNESS_INTERFACE_VERSION int32

const (
	BRIGHTNESS_INTERFACE_VERSION_1 BRIGHTNESS_INTERFACE_VERSION = 1
	BRIGHTNESS_INTERFACE_VERSION_2 BRIGHTNESS_INTERFACE_VERSION = 2
	BRIGHTNESS_INTERFACE_VERSION_3 BRIGHTNESS_INTERFACE_VERSION = 3
)

type BlackScreenDiagnosticsCalloutParam int32

const (
	BlackScreenDiagnosticsData BlackScreenDiagnosticsCalloutParam = 1
	BlackScreenDisplayRecovery BlackScreenDiagnosticsCalloutParam = 2
)

type COLORSPACE_TRANSFORM_DATA_TYPE int32

const (
	COLORSPACE_TRANSFORM_DATA_TYPE_FIXED_POINT COLORSPACE_TRANSFORM_DATA_TYPE = 0
	COLORSPACE_TRANSFORM_DATA_TYPE_FLOAT       COLORSPACE_TRANSFORM_DATA_TYPE = 1
)

type COLORSPACE_TRANSFORM_STAGE_CONTROL int32

const (
	ColorSpaceTransformStageControl_No_Change COLORSPACE_TRANSFORM_STAGE_CONTROL = 0
	ColorSpaceTransformStageControl_Enable    COLORSPACE_TRANSFORM_STAGE_CONTROL = 1
	ColorSpaceTransformStageControl_Bypass    COLORSPACE_TRANSFORM_STAGE_CONTROL = 2
)

type COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION int32

const (
	COLORSPACE_TRANSFORM_VERSION_DEFAULT       COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION = 0
	COLORSPACE_TRANSFORM_VERSION_1             COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION = 1
	COLORSPACE_TRANSFORM_VERSION_NOT_SUPPORTED COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION = 0
)

type COLORSPACE_TRANSFORM_TYPE int32

const (
	COLORSPACE_TRANSFORM_TYPE_UNINITIALIZED COLORSPACE_TRANSFORM_TYPE = 0
	COLORSPACE_TRANSFORM_TYPE_DEFAULT       COLORSPACE_TRANSFORM_TYPE = 1
	COLORSPACE_TRANSFORM_TYPE_RGB256x3x16   COLORSPACE_TRANSFORM_TYPE = 2
	COLORSPACE_TRANSFORM_TYPE_DXGI_1        COLORSPACE_TRANSFORM_TYPE = 3
	COLORSPACE_TRANSFORM_TYPE_MATRIX_3x4    COLORSPACE_TRANSFORM_TYPE = 4
	COLORSPACE_TRANSFORM_TYPE_MATRIX_V2     COLORSPACE_TRANSFORM_TYPE = 5
)

// DISPLAYCONFIG_DEVICE_INFO_TYPE: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_device_info_type
type DISPLAYCONFIG_DEVICE_INFO_TYPE int32

const (
	DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME                DISPLAYCONFIG_DEVICE_INFO_TYPE = 1
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME                DISPLAYCONFIG_DEVICE_INFO_TYPE = 2
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE      DISPLAYCONFIG_DEVICE_INFO_TYPE = 3
	DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME               DISPLAYCONFIG_DEVICE_INFO_TYPE = 4
	DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE         DISPLAYCONFIG_DEVICE_INFO_TYPE = 5
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE           DISPLAYCONFIG_DEVICE_INFO_TYPE = 6
	DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION DISPLAYCONFIG_DEVICE_INFO_TYPE = 7
	DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION DISPLAYCONFIG_DEVICE_INFO_TYPE = 8
	DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO        DISPLAYCONFIG_DEVICE_INFO_TYPE = 9
	DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE       DISPLAYCONFIG_DEVICE_INFO_TYPE = 10
	DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL            DISPLAYCONFIG_DEVICE_INFO_TYPE = 11
	DISPLAYCONFIG_DEVICE_INFO_GET_MONITOR_SPECIALIZATION     DISPLAYCONFIG_DEVICE_INFO_TYPE = 12
	DISPLAYCONFIG_DEVICE_INFO_SET_MONITOR_SPECIALIZATION     DISPLAYCONFIG_DEVICE_INFO_TYPE = 13
	DISPLAYCONFIG_DEVICE_INFO_SET_RESERVED1                  DISPLAYCONFIG_DEVICE_INFO_TYPE = 14
	DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO_2      DISPLAYCONFIG_DEVICE_INFO_TYPE = 15
	DISPLAYCONFIG_DEVICE_INFO_SET_HDR_STATE                  DISPLAYCONFIG_DEVICE_INFO_TYPE = 16
	DISPLAYCONFIG_DEVICE_INFO_SET_WCG_STATE                  DISPLAYCONFIG_DEVICE_INFO_TYPE = 17
)

// DISPLAYCONFIG_MODE_INFO_TYPE: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_mode_info_type
type DISPLAYCONFIG_MODE_INFO_TYPE int32

const (
	DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE        DISPLAYCONFIG_MODE_INFO_TYPE = 1
	DISPLAYCONFIG_MODE_INFO_TYPE_TARGET        DISPLAYCONFIG_MODE_INFO_TYPE = 2
	DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE DISPLAYCONFIG_MODE_INFO_TYPE = 3
)

// DISPLAYCONFIG_PIXELFORMAT: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_pixelformat
type DISPLAYCONFIG_PIXELFORMAT int32

const (
	DISPLAYCONFIG_PIXELFORMAT_8BPP   DISPLAYCONFIG_PIXELFORMAT = 1
	DISPLAYCONFIG_PIXELFORMAT_16BPP  DISPLAYCONFIG_PIXELFORMAT = 2
	DISPLAYCONFIG_PIXELFORMAT_24BPP  DISPLAYCONFIG_PIXELFORMAT = 3
	DISPLAYCONFIG_PIXELFORMAT_32BPP  DISPLAYCONFIG_PIXELFORMAT = 4
	DISPLAYCONFIG_PIXELFORMAT_NONGDI DISPLAYCONFIG_PIXELFORMAT = 5
)

// DISPLAYCONFIG_ROTATION: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_rotation
type DISPLAYCONFIG_ROTATION int32

const (
	DISPLAYCONFIG_ROTATION_IDENTITY  DISPLAYCONFIG_ROTATION = 1
	DISPLAYCONFIG_ROTATION_ROTATE90  DISPLAYCONFIG_ROTATION = 2
	DISPLAYCONFIG_ROTATION_ROTATE180 DISPLAYCONFIG_ROTATION = 3
	DISPLAYCONFIG_ROTATION_ROTATE270 DISPLAYCONFIG_ROTATION = 4
)

// DISPLAYCONFIG_SCALING: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_scaling
type DISPLAYCONFIG_SCALING int32

const (
	DISPLAYCONFIG_SCALING_IDENTITY               DISPLAYCONFIG_SCALING = 1
	DISPLAYCONFIG_SCALING_CENTERED               DISPLAYCONFIG_SCALING = 2
	DISPLAYCONFIG_SCALING_STRETCHED              DISPLAYCONFIG_SCALING = 3
	DISPLAYCONFIG_SCALING_ASPECTRATIOCENTEREDMAX DISPLAYCONFIG_SCALING = 4
	DISPLAYCONFIG_SCALING_CUSTOM                 DISPLAYCONFIG_SCALING = 5
	DISPLAYCONFIG_SCALING_PREFERRED              DISPLAYCONFIG_SCALING = 128
)

// DISPLAYCONFIG_SCANLINE_ORDERING: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_scanline_ordering
type DISPLAYCONFIG_SCANLINE_ORDERING int32

const (
	DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED                DISPLAYCONFIG_SCANLINE_ORDERING = 0
	DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE                DISPLAYCONFIG_SCANLINE_ORDERING = 1
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED                 DISPLAYCONFIG_SCANLINE_ORDERING = 2
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST DISPLAYCONFIG_SCANLINE_ORDERING = 2
	DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST DISPLAYCONFIG_SCANLINE_ORDERING = 3
)

// DISPLAYCONFIG_TOPOLOGY_ID: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_topology_id
type DISPLAYCONFIG_TOPOLOGY_ID int32

const (
	DISPLAYCONFIG_TOPOLOGY_INTERNAL DISPLAYCONFIG_TOPOLOGY_ID = 1
	DISPLAYCONFIG_TOPOLOGY_CLONE    DISPLAYCONFIG_TOPOLOGY_ID = 2
	DISPLAYCONFIG_TOPOLOGY_EXTEND   DISPLAYCONFIG_TOPOLOGY_ID = 4
	DISPLAYCONFIG_TOPOLOGY_EXTERNAL DISPLAYCONFIG_TOPOLOGY_ID = 8
)

// DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY: https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_video_output_technology
type DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY int32

const (
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_OTHER                  DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = -1
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HD15                   DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 0
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SVIDEO                 DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 1
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPOSITE_VIDEO        DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 2
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPONENT_VIDEO        DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 3
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DVI                    DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 4
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI                   DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 5
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_LVDS                   DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 6
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_D_JPN                  DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 8
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDI                    DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 9
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL   DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 10
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED   DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 11
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EXTERNAL           DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 12
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EMBEDDED           DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 13
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDTVDONGLE             DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 14
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_MIRACAST               DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 15
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_WIRED         DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 16
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_VIRTUAL       DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 17
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_USB_TUNNEL DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = 18
	DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL               DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = -2147483648
)

type DSI_CONTROL_TRANSMISSION_MODE int32

const (
	DCT_DEFAULT                DSI_CONTROL_TRANSMISSION_MODE = 0
	DCT_FORCE_LOW_POWER        DSI_CONTROL_TRANSMISSION_MODE = 1
	DCT_FORCE_HIGH_PERFORMANCE DSI_CONTROL_TRANSMISSION_MODE = 2
)

type ENG_DEVICE_ATTRIBUTE int32

const (
	QDA_RESERVED           ENG_DEVICE_ATTRIBUTE = 0
	QDA_ACCELERATION_LEVEL ENG_DEVICE_ATTRIBUTE = 1
)

type ENG_SYSTEM_ATTRIBUTE int32

const (
	EngProcessorFeature             ENG_SYSTEM_ATTRIBUTE = 1
	EngNumberOfProcessors           ENG_SYSTEM_ATTRIBUTE = 2
	EngOptimumAvailableUserMemory   ENG_SYSTEM_ATTRIBUTE = 3
	EngOptimumAvailableSystemMemory ENG_SYSTEM_ATTRIBUTE = 4
)

// MC_COLOR_TEMPERATURE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_color_temperature
type MC_COLOR_TEMPERATURE int32

const (
	MC_COLOR_TEMPERATURE_UNKNOWN MC_COLOR_TEMPERATURE = 0
	MC_COLOR_TEMPERATURE_4000K   MC_COLOR_TEMPERATURE = 1
	MC_COLOR_TEMPERATURE_5000K   MC_COLOR_TEMPERATURE = 2
	MC_COLOR_TEMPERATURE_6500K   MC_COLOR_TEMPERATURE = 3
	MC_COLOR_TEMPERATURE_7500K   MC_COLOR_TEMPERATURE = 4
	MC_COLOR_TEMPERATURE_8200K   MC_COLOR_TEMPERATURE = 5
	MC_COLOR_TEMPERATURE_9300K   MC_COLOR_TEMPERATURE = 6
	MC_COLOR_TEMPERATURE_10000K  MC_COLOR_TEMPERATURE = 7
	MC_COLOR_TEMPERATURE_11500K  MC_COLOR_TEMPERATURE = 8
)

// MC_DISPLAY_TECHNOLOGY_TYPE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_display_technology_type
type MC_DISPLAY_TECHNOLOGY_TYPE int32

const (
	MC_SHADOW_MASK_CATHODE_RAY_TUBE    MC_DISPLAY_TECHNOLOGY_TYPE = 0
	MC_APERTURE_GRILL_CATHODE_RAY_TUBE MC_DISPLAY_TECHNOLOGY_TYPE = 1
	MC_THIN_FILM_TRANSISTOR            MC_DISPLAY_TECHNOLOGY_TYPE = 2
	MC_LIQUID_CRYSTAL_ON_SILICON       MC_DISPLAY_TECHNOLOGY_TYPE = 3
	MC_PLASMA                          MC_DISPLAY_TECHNOLOGY_TYPE = 4
	MC_ORGANIC_LIGHT_EMITTING_DIODE    MC_DISPLAY_TECHNOLOGY_TYPE = 5
	MC_ELECTROLUMINESCENT              MC_DISPLAY_TECHNOLOGY_TYPE = 6
	MC_MICROELECTROMECHANICAL          MC_DISPLAY_TECHNOLOGY_TYPE = 7
	MC_FIELD_EMISSION_DEVICE           MC_DISPLAY_TECHNOLOGY_TYPE = 8
)

// MC_DRIVE_TYPE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_drive_type
type MC_DRIVE_TYPE int32

const (
	MC_RED_DRIVE   MC_DRIVE_TYPE = 0
	MC_GREEN_DRIVE MC_DRIVE_TYPE = 1
	MC_BLUE_DRIVE  MC_DRIVE_TYPE = 2
)

// MC_GAIN_TYPE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_gain_type
type MC_GAIN_TYPE int32

const (
	MC_RED_GAIN   MC_GAIN_TYPE = 0
	MC_GREEN_GAIN MC_GAIN_TYPE = 1
	MC_BLUE_GAIN  MC_GAIN_TYPE = 2
)

// MC_POSITION_TYPE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_position_type
type MC_POSITION_TYPE int32

const (
	MC_HORIZONTAL_POSITION MC_POSITION_TYPE = 0
	MC_VERTICAL_POSITION   MC_POSITION_TYPE = 1
)

// MC_SIZE_TYPE: https://learn.microsoft.com/windows/win32/api/highlevelmonitorconfigurationapi/ne-highlevelmonitorconfigurationapi-mc_size_type
type MC_SIZE_TYPE int32

const (
	MC_WIDTH  MC_SIZE_TYPE = 0
	MC_HEIGHT MC_SIZE_TYPE = 1
)

// MC_VCP_CODE_TYPE: https://learn.microsoft.com/windows/win32/api/lowlevelmonitorconfigurationapi/ne-lowlevelmonitorconfigurationapi-mc_vcp_code_type
type MC_VCP_CODE_TYPE int32

const (
	MC_MOMENTARY     MC_VCP_CODE_TYPE = 0
	MC_SET_PARAMETER MC_VCP_CODE_TYPE = 1
)

// ORIENTATION_PREFERENCE: https://learn.microsoft.com/windows/win32/api/winuser/ne-winuser-orientation_preference
type ORIENTATION_PREFERENCE int32

const (
	ORIENTATION_PREFERENCE_NONE              ORIENTATION_PREFERENCE = 0
	ORIENTATION_PREFERENCE_LANDSCAPE         ORIENTATION_PREFERENCE = 1
	ORIENTATION_PREFERENCE_PORTRAIT          ORIENTATION_PREFERENCE = 2
	ORIENTATION_PREFERENCE_LANDSCAPE_FLIPPED ORIENTATION_PREFERENCE = 4
	ORIENTATION_PREFERENCE_PORTRAIT_FLIPPED  ORIENTATION_PREFERENCE = 8
)

type OUTPUT_COLOR_ENCODING int32

const (
	OUTPUT_COLOR_ENCODING_RGB       OUTPUT_COLOR_ENCODING = 0
	OUTPUT_COLOR_ENCODING_YCBCR444  OUTPUT_COLOR_ENCODING = 1
	OUTPUT_COLOR_ENCODING_YCBCR422  OUTPUT_COLOR_ENCODING = 2
	OUTPUT_COLOR_ENCODING_YCBCR420  OUTPUT_COLOR_ENCODING = 3
	OUTPUT_COLOR_ENCODING_INTENSITY OUTPUT_COLOR_ENCODING = 4
)

type OUTPUT_WIRE_COLOR_SPACE_TYPE int32

const (
	OUTPUT_WIRE_COLOR_SPACE_G22_P709              OUTPUT_WIRE_COLOR_SPACE_TYPE = 0
	OUTPUT_WIRE_COLOR_SPACE_RESERVED              OUTPUT_WIRE_COLOR_SPACE_TYPE = 4
	OUTPUT_WIRE_COLOR_SPACE_G2084_P2020           OUTPUT_WIRE_COLOR_SPACE_TYPE = 12
	OUTPUT_WIRE_COLOR_SPACE_G22_P709_WCG          OUTPUT_WIRE_COLOR_SPACE_TYPE = 30
	OUTPUT_WIRE_COLOR_SPACE_G22_P2020             OUTPUT_WIRE_COLOR_SPACE_TYPE = 31
	OUTPUT_WIRE_COLOR_SPACE_G2084_P2020_HDR10PLUS OUTPUT_WIRE_COLOR_SPACE_TYPE = 32
	OUTPUT_WIRE_COLOR_SPACE_G2084_P2020_DVLL      OUTPUT_WIRE_COLOR_SPACE_TYPE = 33
)

type QUERY_DISPLAY_CONFIG_FLAGS uint32

const (
	QDC_ALL_PATHS                  QUERY_DISPLAY_CONFIG_FLAGS = 1
	QDC_ONLY_ACTIVE_PATHS          QUERY_DISPLAY_CONFIG_FLAGS = 2
	QDC_DATABASE_CURRENT           QUERY_DISPLAY_CONFIG_FLAGS = 4
	QDC_VIRTUAL_MODE_AWARE         QUERY_DISPLAY_CONFIG_FLAGS = 16
	QDC_INCLUDE_HMD                QUERY_DISPLAY_CONFIG_FLAGS = 32
	QDC_VIRTUAL_REFRESH_RATE_AWARE QUERY_DISPLAY_CONFIG_FLAGS = 64
)

type SET_DISPLAY_CONFIG_FLAGS uint32

const (
	SDC_USE_DATABASE_CURRENT        SET_DISPLAY_CONFIG_FLAGS = 15
	SDC_TOPOLOGY_INTERNAL           SET_DISPLAY_CONFIG_FLAGS = 1
	SDC_TOPOLOGY_CLONE              SET_DISPLAY_CONFIG_FLAGS = 2
	SDC_TOPOLOGY_EXTEND             SET_DISPLAY_CONFIG_FLAGS = 4
	SDC_TOPOLOGY_EXTERNAL           SET_DISPLAY_CONFIG_FLAGS = 8
	SDC_TOPOLOGY_SUPPLIED           SET_DISPLAY_CONFIG_FLAGS = 16
	SDC_USE_SUPPLIED_DISPLAY_CONFIG SET_DISPLAY_CONFIG_FLAGS = 32
	SDC_VALIDATE                    SET_DISPLAY_CONFIG_FLAGS = 64
	SDC_APPLY                       SET_DISPLAY_CONFIG_FLAGS = 128
	SDC_NO_OPTIMIZATION             SET_DISPLAY_CONFIG_FLAGS = 256
	SDC_SAVE_TO_DATABASE            SET_DISPLAY_CONFIG_FLAGS = 512
	SDC_ALLOW_CHANGES               SET_DISPLAY_CONFIG_FLAGS = 1024
	SDC_PATH_PERSIST_IF_REQUIRED    SET_DISPLAY_CONFIG_FLAGS = 2048
	SDC_FORCE_MODE_ENUMERATION      SET_DISPLAY_CONFIG_FLAGS = 4096
	SDC_ALLOW_PATH_ORDER_CHANGES    SET_DISPLAY_CONFIG_FLAGS = 8192
	SDC_VIRTUAL_MODE_AWARE          SET_DISPLAY_CONFIG_FLAGS = 32768
	SDC_VIRTUAL_REFRESH_RATE_AWARE  SET_DISPLAY_CONFIG_FLAGS = 131072
)

type VIDEO_BANK_TYPE int32

const (
	VideoNotBanked    VIDEO_BANK_TYPE = 0
	VideoBanked1RW    VIDEO_BANK_TYPE = 1
	VideoBanked1R1W   VIDEO_BANK_TYPE = 2
	VideoBanked2RW    VIDEO_BANK_TYPE = 3
	NumVideoBankTypes VIDEO_BANK_TYPE = 4
)

type VIDEO_POWER_STATE int32

const (
	VideoPowerUnspecified VIDEO_POWER_STATE = 0
	VideoPowerOn          VIDEO_POWER_STATE = 1
	VideoPowerStandBy     VIDEO_POWER_STATE = 2
	VideoPowerSuspend     VIDEO_POWER_STATE = 3
	VideoPowerOff         VIDEO_POWER_STATE = 4
	VideoPowerHibernate   VIDEO_POWER_STATE = 5
	VideoPowerShutdown    VIDEO_POWER_STATE = 6
	VideoPowerMaximum     VIDEO_POWER_STATE = 7
)

type VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE int32

const (
	VideoPowerNotifyCallout             VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 1
	VideoEnumChildPdoNotifyCallout      VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 3
	VideoFindAdapterCallout             VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 4
	VideoPnpNotifyCallout               VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 7
	VideoDxgkDisplaySwitchCallout       VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 8
	VideoDxgkFindAdapterTdrCallout      VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 10
	VideoDxgkHardwareProtectionTeardown VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 11
	VideoRepaintDesktop                 VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 12
	VideoUpdateCursor                   VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 13
	VideoDisableMultiPlaneOverlay       VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 14
	VideoDesktopDuplicationChange       VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 15
	VideoBlackScreenDiagnostics         VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 16
	VideoForceCompositionRender         VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE = 17
)

// Adapter: https://learn.microsoft.com/windows/win32/api/cloneviewhelper/ns-cloneviewhelper-adapter
type Adapter struct {
	AdapterName [128]uint16
	NumSources  int32
	Sources     [1]Sources
}

// Adapters: https://learn.microsoft.com/windows/win32/api/cloneviewhelper/ns-cloneviewhelper-adapters
type Adapters struct {
	NumAdapters int32
	Adapter     [1]Adapter
}

type BACKLIGHT_REDUCTION_GAMMA_RAMP struct {
	R [256]uint16
	G [256]uint16
	B [256]uint16
}

type BANK_POSITION struct {
	ReadBankPosition  uint32
	WriteBankPosition uint32
}

// BLENDOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-blendobj
type BLENDOBJ struct {
	BlendFunction graphicsgdi.BLENDFUNCTION
}

type BRIGHTNESS_LEVEL struct {
	Count byte
	Level [103]byte
}

type BRIGHTNESS_NIT_RANGE struct {
	MinLevelInMillinit uint32
	MaxLevelInMillinit uint32
	StepSizeInMillinit uint32
}

type BRIGHTNESS_NIT_RANGES struct {
	NormalRangeCount           uint32
	RangeCount                 uint32
	PreferredMaximumBrightness uint32
	SupportedRanges            [16]BRIGHTNESS_NIT_RANGE
}

// BRUSHOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-brushobj
type BRUSHOBJ struct {
	ISolidColor uint32
	PvRbrush    unsafe.Pointer
	FlColorType uint32
}

type CDDDXGK_REDIRBITMAPPRESENTINFO struct {
	NumDirtyRects                  uint32
	DirtyRect                      *foundation.RECT
	NumContexts                    uint32
	HContext                       [65]foundation.HANDLE
	BDoNotSynchronizeWithDxContent foundation.BOOLEAN
}

type CHAR_IMAGE_INFO struct {
	CharInfo      systemconsole.CHAR_INFO
	FontImageInfo FONT_IMAGE_INFO
}

type CHROMATICITY_COORDINATE struct {
	X float32
	Y float32
}

// CIECHROMA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-ciechroma
type CIECHROMA struct {
	X  int32
	Y  int32
	Y_ int32
}

// CLIPLINE: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-clipline
type CLIPLINE struct {
	PtfxA       POINTFIX
	PtfxB       POINTFIX
	LStyleState int32
	C           uint32
	Arun        [1]RUN
}

// CLIPOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-clipobj
type CLIPOBJ struct {
	IUniq        uint32
	RclBounds    foundation.RECTL
	IDComplexity byte
	IFComplexity byte
	IMode        byte
	FjOptions    byte
}

// COLORINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-colorinfo
type COLORINFO struct {
	Red                CIECHROMA
	Green              CIECHROMA
	Blue               CIECHROMA
	Cyan               CIECHROMA
	Magenta            CIECHROMA
	Yellow             CIECHROMA
	AlignmentWhite     CIECHROMA
	RedGamma           int32
	GreenGamma         int32
	BlueGamma          int32
	MagentaInCyanDye   int32
	YellowInCyanDye    int32
	CyanInMagentaDye   int32
	YellowInMagentaDye int32
	CyanInYellowDye    int32
	MagentaInYellowDye int32
}

type COLORSPACE_SCALAR_MULTIPLIER_CAPS struct {
	Valid           foundation.BOOLEAN
	NumericRangeMin float32
	NumericRangeMax float32
}

// COLORSPACE_TRANSFORM_Data_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type COLORSPACE_TRANSFORM_Data_e__Union struct {
	Data [24588]uint32
}

type COLORSPACE_TRANSFORM struct {
	Type COLORSPACE_TRANSFORM_TYPE
	Data uintptr
}

type COLORSPACE_TRANSFORM_1DLUT_CAP struct {
	NumberOfLUTEntries uint32
	DataCap            COLORSPACE_TRANSFORM_DATA_CAP
}

type COLORSPACE_TRANSFORM_3x4 struct {
	ColorMatrix3x4   [12]float32
	ScalarMultiplier float32
	LookupTable1D    [4096]GAMMA_RAMP_RGB
}

// COLORSPACE_TRANSFORM_DATA_CAP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type COLORSPACE_TRANSFORM_DATA_CAP_Anonymous_e__Union struct {
	Data [1]uint64
}

type COLORSPACE_TRANSFORM_DATA_CAP struct {
	DataType        COLORSPACE_TRANSFORM_DATA_TYPE
	Anonymous       uintptr
	NumericRangeMin float32
	NumericRangeMax float32
}

// COLORSPACE_TRANSFORM_MATRIX_CAP_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type COLORSPACE_TRANSFORM_MATRIX_CAP_Anonymous_e__Union struct {
	Data [1]uint64
}

type COLORSPACE_TRANSFORM_MATRIX_CAP struct {
	Anonymous uintptr
	DataCap   COLORSPACE_TRANSFORM_DATA_CAP
}

type COLORSPACE_TRANSFORM_MATRIX_V2 struct {
	StageControlLookupTable1DDegamma COLORSPACE_TRANSFORM_STAGE_CONTROL
	LookupTable1DDegamma             [4096]GAMMA_RAMP_RGB
	StageControlColorMatrix3x3       COLORSPACE_TRANSFORM_STAGE_CONTROL
	ColorMatrix3x3                   [9]float32
	StageControlLookupTable1DRegamma COLORSPACE_TRANSFORM_STAGE_CONTROL
	LookupTable1DRegamma             [4096]GAMMA_RAMP_RGB
}

type COLORSPACE_TRANSFORM_SET_INPUT struct {
	OutputWireColorSpaceExpected OUTPUT_WIRE_COLOR_SPACE_TYPE
	OutputWireFormatExpected     OUTPUT_WIRE_FORMAT
	ColorSpaceTransform          COLORSPACE_TRANSFORM
}

type COLORSPACE_TRANSFORM_TARGET_CAPS struct {
	Version                 COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION
	LookupTable1DDegammaCap COLORSPACE_TRANSFORM_1DLUT_CAP
	ColorMatrix3x3Cap       COLORSPACE_TRANSFORM_MATRIX_CAP
	LookupTable1DRegammaCap COLORSPACE_TRANSFORM_1DLUT_CAP
}

// DEVHTADJDATA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-devhtadjdata
type DEVHTADJDATA struct {
	DeviceFlags uint32
	DeviceXDPI  uint32
	DeviceYDPI  uint32
	PDefHTInfo  *DEVHTINFO
	PAdjHTInfo  *DEVHTINFO
}

// DEVHTINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-devhtinfo
type DEVHTINFO struct {
	HTFlags       uint32
	HTPatternSize uint32
	DevPelsDPI    uint32
	ColorInfo     COLORINFO
}

// DEVINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-devinfo
type DEVINFO struct {
	FlGraphicsCaps  uint32
	LfDefaultFont   graphicsgdi.LOGFONTW
	LfAnsiVarFont   graphicsgdi.LOGFONTW
	LfAnsiFixFont   graphicsgdi.LOGFONTW
	CFonts          uint32
	IDitherFormat   uint32
	CxDither        uint16
	CyDither        uint16
	HpalDefault     graphicsgdi.HPALETTE
	FlGraphicsCaps2 uint32
}

// DISPLAYCONFIG_2DREGION: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_2dregion
type DISPLAYCONFIG_2DREGION struct {
	Cx uint32
	Cy uint32
}

// DISPLAYCONFIG_ADAPTER_NAME: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_adapter_name
type DISPLAYCONFIG_ADAPTER_NAME struct {
	Header            DISPLAYCONFIG_DEVICE_INFO_HEADER
	AdapterDevicePath [128]uint16
}

// DISPLAYCONFIG_DESKTOP_IMAGE_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_desktop_image_info
type DISPLAYCONFIG_DESKTOP_IMAGE_INFO struct {
	PathSourceSize     foundation.POINTL
	DesktopImageRegion foundation.RECTL
	DesktopImageClip   foundation.RECTL
}

// DISPLAYCONFIG_DEVICE_INFO_HEADER: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_device_info_header
type DISPLAYCONFIG_DEVICE_INFO_HEADER struct {
	Type      DISPLAYCONFIG_DEVICE_INFO_TYPE
	Size      uint32
	AdapterId foundation.LUID
	Id        uint32
}

// DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO struct {
	Header              DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous           uintptr
	ColorEncoding       graphicsgdi.DISPLAYCONFIG_COLOR_ENCODING
	BitsPerColorChannel uint32
}

// DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2 struct {
	Header              DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous           uintptr
	ColorEncoding       graphicsgdi.DISPLAYCONFIG_COLOR_ENCODING
	BitsPerColorChannel uint32
	ActiveColorMode     graphicsgdi.DISPLAYCONFIG_ADVANCED_COLOR_MODE
}

// DISPLAYCONFIG_GET_MONITOR_SPECIALIZATION_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_GET_MONITOR_SPECIALIZATION_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_GET_MONITOR_SPECIALIZATION struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_MODE_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_MODE_INFO_Anonymous_e__Union struct {
	Data [7]uint64
}

// DISPLAYCONFIG_MODE_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_mode_info
type DISPLAYCONFIG_MODE_INFO struct {
	InfoType  DISPLAYCONFIG_MODE_INFO_TYPE
	Id        uint32
	AdapterId foundation.LUID
	Anonymous uintptr
}

// DISPLAYCONFIG_PATH_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_path_info
type DISPLAYCONFIG_PATH_INFO struct {
	SourceInfo DISPLAYCONFIG_PATH_SOURCE_INFO
	TargetInfo DISPLAYCONFIG_PATH_TARGET_INFO
	Flags      uint32
}

// DISPLAYCONFIG_PATH_SOURCE_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_PATH_SOURCE_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_PATH_SOURCE_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_path_source_info
type DISPLAYCONFIG_PATH_SOURCE_INFO struct {
	AdapterId   foundation.LUID
	Id          uint32
	Anonymous   uintptr
	StatusFlags uint32
}

// DISPLAYCONFIG_PATH_TARGET_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_PATH_TARGET_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_PATH_TARGET_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_path_target_info
type DISPLAYCONFIG_PATH_TARGET_INFO struct {
	AdapterId        foundation.LUID
	Id               uint32
	Anonymous        uintptr
	OutputTechnology DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY
	Rotation         DISPLAYCONFIG_ROTATION
	Scaling          DISPLAYCONFIG_SCALING
	RefreshRate      DISPLAYCONFIG_RATIONAL
	ScanLineOrdering DISPLAYCONFIG_SCANLINE_ORDERING
	TargetAvailable  foundation.BOOL
	StatusFlags      uint32
}

// DISPLAYCONFIG_RATIONAL: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_rational
type DISPLAYCONFIG_RATIONAL struct {
	Numerator   uint32
	Denominator uint32
}

// DISPLAYCONFIG_SDR_WHITE_LEVEL: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_sdr_white_level
type DISPLAYCONFIG_SDR_WHITE_LEVEL struct {
	Header        DISPLAYCONFIG_DEVICE_INFO_HEADER
	SDRWhiteLevel uint32
}

// DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_SET_HDR_STATE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SET_HDR_STATE_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_SET_HDR_STATE struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_SET_MONITOR_SPECIALIZATION_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SET_MONITOR_SPECIALIZATION_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_SET_MONITOR_SPECIALIZATION struct {
	Header                        DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous                     uintptr
	SpecializationType            win32.GUID
	SpecializationSubType         win32.GUID
	SpecializationApplicationName [128]uint16
}

// DISPLAYCONFIG_SET_TARGET_PERSISTENCE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SET_TARGET_PERSISTENCE_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_SET_TARGET_PERSISTENCE: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_set_target_persistence
type DISPLAYCONFIG_SET_TARGET_PERSISTENCE struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_SET_WCG_STATE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SET_WCG_STATE_Anonymous_e__Union struct {
	Data [1]uint64
}

type DISPLAYCONFIG_SET_WCG_STATE struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_SOURCE_DEVICE_NAME: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_source_device_name
type DISPLAYCONFIG_SOURCE_DEVICE_NAME struct {
	Header            DISPLAYCONFIG_DEVICE_INFO_HEADER
	ViewGdiDeviceName [32]uint16
}

// DISPLAYCONFIG_SOURCE_MODE: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_source_mode
type DISPLAYCONFIG_SOURCE_MODE struct {
	Width       uint32
	Height      uint32
	PixelFormat DISPLAYCONFIG_PIXELFORMAT
	Position    foundation.POINTL
}

// DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_support_virtual_resolution
type DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION struct {
	Header    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Anonymous uintptr
}

// DISPLAYCONFIG_TARGET_BASE_TYPE: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_target_base_type
type DISPLAYCONFIG_TARGET_BASE_TYPE struct {
	Header               DISPLAYCONFIG_DEVICE_INFO_HEADER
	BaseOutputTechnology DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY
}

// DISPLAYCONFIG_TARGET_DEVICE_NAME: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_target_device_name
type DISPLAYCONFIG_TARGET_DEVICE_NAME struct {
	Header                    DISPLAYCONFIG_DEVICE_INFO_HEADER
	Flags                     DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS
	OutputTechnology          DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY
	EdidManufactureId         uint16
	EdidProductCodeId         uint16
	ConnectorInstance         uint32
	MonitorFriendlyDeviceName [64]uint16
	MonitorDevicePath         [128]uint16
}

// DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_target_device_name_flags
type DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS struct {
	Anonymous uintptr
}

// DISPLAYCONFIG_TARGET_MODE: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_target_mode
type DISPLAYCONFIG_TARGET_MODE struct {
	TargetVideoSignalInfo DISPLAYCONFIG_VIDEO_SIGNAL_INFO
}

// DISPLAYCONFIG_TARGET_PREFERRED_MODE: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_target_preferred_mode
type DISPLAYCONFIG_TARGET_PREFERRED_MODE struct {
	Header     DISPLAYCONFIG_DEVICE_INFO_HEADER
	Width      uint32
	Height     uint32
	TargetMode DISPLAYCONFIG_TARGET_MODE
}

// DISPLAYCONFIG_VIDEO_SIGNAL_INFO_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type DISPLAYCONFIG_VIDEO_SIGNAL_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

// DISPLAYCONFIG_VIDEO_SIGNAL_INFO: https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_video_signal_info
type DISPLAYCONFIG_VIDEO_SIGNAL_INFO struct {
	PixelRate        uint64
	HSyncFreq        DISPLAYCONFIG_RATIONAL
	VSyncFreq        DISPLAYCONFIG_RATIONAL
	ActiveSize       DISPLAYCONFIG_2DREGION
	TotalSize        DISPLAYCONFIG_2DREGION
	Anonymous        uintptr
	ScanLineOrdering DISPLAYCONFIG_SCANLINE_ORDERING
}

type DISPLAY_BRIGHTNESS struct {
	UcDisplayPolicy byte
	UcACBrightness  byte
	UcDCBrightness  byte
}

type DRH_APIBITMAPDATA struct {
	Pso *SURFOBJ
	B   foundation.BOOL
}

// DRIVEROBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-driverobj
type DRIVEROBJ struct {
	PvObj     unsafe.Pointer
	PFreeProc FREEOBJPROC
	Hdev      HDEV
	Dhpdev    DHPDEV
}

// DRVENABLEDATA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-drvenabledata
type DRVENABLEDATA struct {
	IDriverVersion uint32
	C              uint32
	Pdrvfn         *DRVFN
}

// DRVFN: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-drvfn
type DRVFN struct {
	IFunc uint32
	Pfn   PFN
}

type DXGK_WIN32K_PARAM_DATA struct {
	PathsArray           unsafe.Pointer
	ModesArray           unsafe.Pointer
	NumPathArrayElements uint32
	NumModeArrayElements uint32
	SDCFlags             uint32
}

// DisplayMode: https://learn.microsoft.com/windows/win32/api/cloneviewhelper/ns-cloneviewhelper-displaymode
type DisplayMode struct {
	DeviceName [32]uint16
	DevMode    graphicsgdi.DEVMODEW
}

// DisplayModes: https://learn.microsoft.com/windows/win32/api/cloneviewhelper/ns-cloneviewhelper-displaymodes
type DisplayModes struct {
	NumDisplayModes int32
	DisplayMode     [1]DisplayMode
}

type EMFINFO struct {
	NSize           uint32
	Hdc             graphicsgdi.HDC
	PvEMF           *byte
	PvCurrentRecord *byte
}

// ENGSAFESEMAPHORE: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-engsafesemaphore
type ENGSAFESEMAPHORE struct {
	Hsem   HSEMAPHORE
	LCount int32
}

type ENG_EVENT struct {
	PKEvent unsafe.Pointer
	FFlags  uint32
}

// ENG_TIME_FIELDS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-eng_time_fields
type ENG_TIME_FIELDS struct {
	UsYear         uint16
	UsMonth        uint16
	UsDay          uint16
	UsHour         uint16
	UsMinute       uint16
	UsSecond       uint16
	UsMilliseconds uint16
	UsWeekday      uint16
}

// ENUMRECTS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-enumrects
type ENUMRECTS struct {
	C    uint32
	Arcl [1]foundation.RECTL
}

// FD_DEVICEMETRICS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fd_devicemetrics
type FD_DEVICEMETRICS struct {
	FlRealizedType         uint32
	PteBase                POINTE
	PteSide                POINTE
	LD                     int32
	FxMaxAscender          int32
	FxMaxDescender         int32
	PtlUnderline1          foundation.POINTL
	PtlStrikeOut           foundation.POINTL
	PtlULThickness         foundation.POINTL
	PtlSOThickness         foundation.POINTL
	CxMax                  uint32
	CyMax                  uint32
	CjGlyphMax             uint32
	FdxQuantized           FD_XFORM
	LNonLinearExtLeading   int32
	LNonLinearIntLeading   int32
	LNonLinearMaxCharWidth int32
	LNonLinearAvgCharWidth int32
	LMinA                  int32
	LMinC                  int32
	LMinD                  int32
	AlReserved             [1]int32
}

// FD_GLYPHATTR: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fd_glyphattr
type FD_GLYPHATTR struct {
	CjThis     uint32
	CGlyphs    uint32
	IMode      uint32
	AGlyphAttr [1]byte
}

// FD_GLYPHSET: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fd_glyphset
type FD_GLYPHSET struct {
	CjThis           uint32
	FlAccel          uint32
	CGlyphsSupported uint32
	CRuns            uint32
	Awcrun           [1]WCRUN
}

// FD_KERNINGPAIR: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fd_kerningpair
type FD_KERNINGPAIR struct {
	WcFirst  uint16
	WcSecond uint16
	FwdKern  int16
}

type FD_LIGATURE struct {
	CulThis    uint32
	UlType     uint32
	CLigatures uint32
	Alig       [1]LIGATURE
}

// FD_XFORM: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fd_xform
type FD_XFORM struct {
	EXX float32
	EXY float32
	EYX float32
	EYY float32
}

// FLOATOBJ_XFORM: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-floatobj_xform
type FLOATOBJ_XFORM struct {
	EM11 float32
	EM12 float32
	EM21 float32
	EM22 float32
	EDx  float32
	EDy  float32
}

// FLOAT_LONG is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type FLOAT_LONG struct {
	Data [1]uint32
}

// FONTDIFF: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fontdiff
type FONTDIFF struct {
	JReserved1      byte
	JReserved2      byte
	JReserved3      byte
	BWeight         byte
	UsWinWeight     uint16
	FsSelection     uint16
	FwdAveCharWidth int16
	FwdMaxCharInc   int16
	PtlCaret        foundation.POINTL
}

// FONTINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fontinfo
type FONTINFO struct {
	CjThis           uint32
	FlCaps           uint32
	CGlyphsSupported uint32
	CjMaxGlyph1      uint32
	CjMaxGlyph4      uint32
	CjMaxGlyph8      uint32
	CjMaxGlyph32     uint32
}

// FONTOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fontobj
type FONTOBJ struct {
	IUniq        uint32
	IFace        uint32
	CxMax        uint32
	FlFontType   uint32
	ITTUniq      uintptr
	IFile        uintptr
	SizLogResPpi foundation.SIZE
	UlStyleSize  uint32
	PvConsumer   unsafe.Pointer
	PvProducer   unsafe.Pointer
}

// FONTSIM: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-fontsim
type FONTSIM struct {
	DpBold       int32
	DpItalic     int32
	DpBoldItalic int32
}

type FONT_IMAGE_INFO struct {
	FontSize  systemconsole.COORD
	ImageBits *byte
}

type FSCNTL_SCREEN_INFO struct {
	Position       systemconsole.COORD
	ScreenSize     systemconsole.COORD
	NNumberOfChars uint32
}

type FSVIDEO_COPY_FRAME_BUFFER struct {
	SrcScreen  FSCNTL_SCREEN_INFO
	DestScreen FSCNTL_SCREEN_INFO
}

type FSVIDEO_CURSOR_POSITION struct {
	Coord  VIDEO_CURSOR_POSITION
	DwType uint32
}

type FSVIDEO_MODE_INFORMATION struct {
	VideoMode   VIDEO_MODE_INFORMATION
	VideoMemory VIDEO_MEMORY_INFORMATION
}

type FSVIDEO_REVERSE_MOUSE_POINTER struct {
	Screen FSCNTL_SCREEN_INFO
	DwType uint32
}

type FSVIDEO_SCREEN_INFORMATION struct {
	ScreenSize systemconsole.COORD
	FontSize   systemconsole.COORD
}

type FSVIDEO_WRITE_TO_FRAME_BUFFER struct {
	SrcBuffer  *CHAR_IMAGE_INFO
	DestScreen FSCNTL_SCREEN_INFO
}

// GAMMARAMP: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-gammaramp
type GAMMARAMP struct {
	Red   [256]uint16
	Green [256]uint16
	Blue  [256]uint16
}

type GAMMA_RAMP_DXGI_1 struct {
	Scale      GAMMA_RAMP_RGB
	Offset     GAMMA_RAMP_RGB
	GammaCurve [1025]GAMMA_RAMP_RGB
}

type GAMMA_RAMP_RGB struct {
	Red   float32
	Green float32
	Blue  float32
}

type GAMMA_RAMP_RGB256x3x16 struct {
	Red   [256]uint16
	Green [256]uint16
	Blue  [256]uint16
}

// GDIINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-gdiinfo
type GDIINFO struct {
	UlVersion                      uint32
	UlTechnology                   uint32
	UlHorzSize                     uint32
	UlVertSize                     uint32
	UlHorzRes                      uint32
	UlVertRes                      uint32
	CBitsPixel                     uint32
	CPlanes                        uint32
	UlNumColors                    uint32
	FlRaster                       uint32
	UlLogPixelsX                   uint32
	UlLogPixelsY                   uint32
	FlTextCaps                     uint32
	UlDACRed                       uint32
	UlDACGreen                     uint32
	UlDACBlue                      uint32
	UlAspectX                      uint32
	UlAspectY                      uint32
	UlAspectXY                     uint32
	XStyleStep                     int32
	YStyleStep                     int32
	DenStyleStep                   int32
	PtlPhysOffset                  foundation.POINTL
	SzlPhysSize                    foundation.SIZE
	UlNumPalReg                    uint32
	CiDevice                       COLORINFO
	UlDevicePelsDPI                uint32
	UlPrimaryOrder                 uint32
	UlHTPatternSize                uint32
	UlHTOutputFormat               uint32
	FlHTFlags                      uint32
	UlVRefresh                     uint32
	UlBltAlignment                 uint32
	UlPanningHorzRes               uint32
	UlPanningVertRes               uint32
	XPanningAlignment              uint32
	YPanningAlignment              uint32
	CxHTPat                        uint32
	CyHTPat                        uint32
	PHTPatA                        *byte
	PHTPatB                        *byte
	PHTPatC                        *byte
	FlShadeBlend                   uint32
	UlPhysicalPixelCharacteristics uint32
	UlPhysicalPixelGamma           uint32
}

// GLYPHBITS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-glyphbits
type GLYPHBITS struct {
	PtlOrigin  foundation.POINTL
	SizlBitmap foundation.SIZE
	Aj         [1]byte
}

// GLYPHDATA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-glyphdata
type GLYPHDATA struct {
	Gdf         GLYPHDEF
	Hg          uint32
	FxD         int32
	FxA         int32
	FxAB        int32
	FxInkTop    int32
	FxInkBottom int32
	RclInk      foundation.RECTL
	PtqD        POINTQF
}

// GLYPHDEF: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-glyphdef
// GLYPHDEF is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type GLYPHDEF struct {
	Data [1]uint64
}

// GLYPHPOS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-glyphpos
type GLYPHPOS struct {
	Hg   uint32
	Pgdf *GLYPHDEF
	Ptl  foundation.POINTL
}

// IFIEXTRA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-ifiextra
type IFIEXTRA struct {
	UlIdentifier   uint32
	DpFontSig      int32
	Cig            uint32
	DpDesignVector int32
	DpAxesInfoW    int32
	AulReserved    [1]uint32
}

// IFIMETRICS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-ifimetrics
type IFIMETRICS struct {
	CjThis                uint32
	CjIfiExtra            uint32
	DpwszFamilyName       int32
	DpwszStyleName        int32
	DpwszFaceName         int32
	DpwszUniqueName       int32
	DpFontSim             int32
	LEmbedId              int32
	LItalicAngle          int32
	LCharBias             int32
	DpCharSets            int32
	JWinCharSet           byte
	JWinPitchAndFamily    byte
	UsWinWeight           uint16
	FlInfo                uint32
	FsSelection           uint16
	FsType                uint16
	FwdUnitsPerEm         int16
	FwdLowestPPEm         int16
	FwdWinAscender        int16
	FwdWinDescender       int16
	FwdMacAscender        int16
	FwdMacDescender       int16
	FwdMacLineGap         int16
	FwdTypoAscender       int16
	FwdTypoDescender      int16
	FwdTypoLineGap        int16
	FwdAveCharWidth       int16
	FwdMaxCharInc         int16
	FwdCapHeight          int16
	FwdXHeight            int16
	FwdSubscriptXSize     int16
	FwdSubscriptYSize     int16
	FwdSubscriptXOffset   int16
	FwdSubscriptYOffset   int16
	FwdSuperscriptXSize   int16
	FwdSuperscriptYSize   int16
	FwdSuperscriptXOffset int16
	FwdSuperscriptYOffset int16
	FwdUnderscoreSize     int16
	FwdUnderscorePosition int16
	FwdStrikeoutSize      int16
	FwdStrikeoutPosition  int16
	ChFirstChar           byte
	ChLastChar            byte
	ChDefaultChar         byte
	ChBreakChar           byte
	WcFirstChar           uint16
	WcLastChar            uint16
	WcDefaultChar         uint16
	WcBreakChar           uint16
	PtlBaseline           foundation.POINTL
	PtlAspect             foundation.POINTL
	PtlCaret              foundation.POINTL
	RclFontBox            foundation.RECTL
	AchVendId             [4]byte
	CKerningPairs         uint32
	UlPanoseCulture       uint32
	Panose                graphicsgdi.PANOSE
	Align                 unsafe.Pointer
}

type INDIRECT_DISPLAY_INFO struct {
	DisplayAdapterLuid       foundation.LUID
	Flags                    uint32
	NumMonitors              uint32
	DisplayAdapterTargetBase uint32
	DriverVersionMajor       uint32
	DriverVersionMinor       uint32
}

type LIGATURE struct {
	CulSize uint32
	Pwsz    foundation.PWSTR
	Chglyph uint32
	Ahglyph [1]uint32
}

// LINEATTRS: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-lineattrs
type LINEATTRS struct {
	Fl           uint32
	IJoin        uint32
	IEndCap      uint32
	ElWidth      FLOAT_LONG
	EMiterLimit  float32
	Cstyle       uint32
	Pstyle       *FLOAT_LONG
	ElStyleState FLOAT_LONG
}

type MIPI_DSI_CAPS struct {
	DSITypeMajor                  byte
	DSITypeMinor                  byte
	SpecVersionMajor              byte
	SpecVersionMinor              byte
	SpecVersionPatch              byte
	TargetMaximumReturnPacketSize uint16
	ResultCodeFlags               byte
	ResultCodeStatus              byte
	Revision                      byte
	Level                         byte
	DeviceClassHi                 byte
	DeviceClassLo                 byte
	ManufacturerHi                byte
	ManufacturerLo                byte
	ProductHi                     byte
	ProductLo                     byte
	LengthHi                      byte
	LengthLo                      byte
}

// MIPI_DSI_PACKET_Anonymous1_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIPI_DSI_PACKET_Anonymous1_e__Union struct {
	Data [1]uint64
}

// MIPI_DSI_PACKET_Anonymous2_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIPI_DSI_PACKET_Anonymous2_e__Union struct {
	Data [1]uint64
}

type MIPI_DSI_PACKET struct {
	Anonymous1 uintptr
	Anonymous2 uintptr
	EccFiller  byte
	Payload    [8]byte
}

// MIPI_DSI_RESET_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type MIPI_DSI_RESET_Anonymous_e__Union struct {
	Data [1]uint64
}

type MIPI_DSI_RESET struct {
	Flags     uint32
	Anonymous uintptr
}

type MIPI_DSI_TRANSMISSION_Anonymous_e__Struct struct {
	Bitfield uint16
}

type MIPI_DSI_TRANSMISSION struct {
	TotalBufferSize          uint32
	PacketCount              byte
	FailedPacket             byte
	Anonymous                uintptr
	ReadWordCount            uint16
	FinalCommandExtraPayload uint16
	MipiErrors               uint16
	HostErrors               uint16
	Packets                  [1]MIPI_DSI_PACKET
}

type OUTPUT_WIRE_FORMAT struct {
	ColorEncoding OUTPUT_COLOR_ENCODING
	BitsPerPixel  uint32
}

// PALOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-palobj
type PALOBJ struct {
	UlReserved uint32
}

// PANEL_BRIGHTNESS_SENSOR_DATA_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_BRIGHTNESS_SENSOR_DATA_Anonymous_e__Union struct {
	Data [1]uint64
}

type PANEL_BRIGHTNESS_SENSOR_DATA struct {
	Anonymous              uintptr
	AlsReading             float32
	ChromaticityCoordinate CHROMATICITY_COORDINATE
	ColorTemperature       float32
}

type PANEL_GET_BACKLIGHT_REDUCTION struct {
	BacklightUsersetting uint16
	BacklightEffective   uint16
	GammaRamp            BACKLIGHT_REDUCTION_GAMMA_RAMP
}

// PANEL_GET_BRIGHTNESS_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_GET_BRIGHTNESS_Anonymous_e__Union struct {
	Data [1]uint64
}

type PANEL_GET_BRIGHTNESS struct {
	Version   BRIGHTNESS_INTERFACE_VERSION
	Anonymous uintptr
}

// PANEL_QUERY_BRIGHTNESS_CAPS_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_QUERY_BRIGHTNESS_CAPS_Anonymous_e__Union struct {
	Data [1]uint64
}

type PANEL_QUERY_BRIGHTNESS_CAPS struct {
	Version   BRIGHTNESS_INTERFACE_VERSION
	Anonymous uintptr
}

// PANEL_QUERY_BRIGHTNESS_RANGES_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_QUERY_BRIGHTNESS_RANGES_Anonymous_e__Union struct {
	Data [51]uint32
}

type PANEL_QUERY_BRIGHTNESS_RANGES struct {
	Version   BRIGHTNESS_INTERFACE_VERSION
	Anonymous uintptr
}

type PANEL_SET_BACKLIGHT_OPTIMIZATION struct {
	Level BACKLIGHT_OPTIMIZATION_LEVEL
}

// PANEL_SET_BRIGHTNESS_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_SET_BRIGHTNESS_Anonymous_e__Union struct {
	Data [1]uint64
}

type PANEL_SET_BRIGHTNESS struct {
	Version   BRIGHTNESS_INTERFACE_VERSION
	Anonymous uintptr
}

// PANEL_SET_BRIGHTNESS_STATE_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type PANEL_SET_BRIGHTNESS_STATE_Anonymous_e__Union struct {
	Data [1]uint64
}

type PANEL_SET_BRIGHTNESS_STATE struct {
	Anonymous uintptr
}

// PATHDATA: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-pathdata
type PATHDATA struct {
	Flags uint32
	Count uint32
	Pptfx *POINTFIX
}

// PATHOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-pathobj
type PATHOBJ struct {
	Fl      uint32
	CCurves uint32
}

// PERBANDINFO: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-perbandinfo
type PERBANDINFO struct {
	BRepeatThisBand foundation.BOOL
	SzlBand         foundation.SIZE
	UlHorzRes       uint32
	UlVertRes       uint32
}

type POINTE struct {
	X float32
	Y float32
}

type POINTFIX struct {
	X int32
	Y int32
}

type POINTQF struct {
	X int64
	Y int64
}

type RECTFX struct {
	XLeft   int32
	YTop    int32
	XRight  int32
	YBottom int32
}

// RUN: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-run
type RUN struct {
	IStart int32
	IStop  int32
}

type SET_ACTIVE_COLOR_PROFILE_NAME struct {
	ColorProfileName [1]uint16
}

// STROBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-strobj
type STROBJ struct {
	CGlyphs     uint32
	FlAccel     uint32
	UlCharInc   uint32
	RclBkGround foundation.RECTL
	Pgp         *GLYPHPOS
	PwszOrg     foundation.PWSTR
}

// SURFOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-surfobj
type SURFOBJ struct {
	Dhsurf        DHSURF
	Hsurf         HSURF
	Dhpdev        DHPDEV
	Hdev          HDEV
	SizlBitmap    foundation.SIZE
	CjBits        uint32
	PvBits        unsafe.Pointer
	PvScan0       unsafe.Pointer
	LDelta        int32
	IUniq         uint32
	IBitmapFormat uint32
	IType         uint16
	FjBitmap      uint16
}

// Sources: https://learn.microsoft.com/windows/win32/api/cloneviewhelper/ns-cloneviewhelper-sources
type Sources struct {
	SourceId   uint32
	NumTargets int32
	ATargets   [1]uint32
}

// TYPE1_FONT: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-type1_font
type TYPE1_FONT struct {
	HPFM         foundation.HANDLE
	HPFB         foundation.HANDLE
	UlIdentifier uint32
}

type VGA_CHAR struct {
	Char       foundation.CHAR
	Attributes foundation.CHAR
}

// VIDEOPARAMETERS: https://learn.microsoft.com/windows/win32/api/tvout/ns-tvout-videoparameters
type VIDEOPARAMETERS struct {
	Guid                  win32.GUID
	DwOffset              uint32
	DwCommand             uint32
	DwFlags               uint32
	DwMode                uint32
	DwTVStandard          uint32
	DwAvailableModes      uint32
	DwAvailableTVStandard uint32
	DwFlickerFilter       uint32
	DwOverScanX           uint32
	DwOverScanY           uint32
	DwMaxUnscaledX        uint32
	DwMaxUnscaledY        uint32
	DwPositionX           uint32
	DwPositionY           uint32
	DwBrightness          uint32
	DwContrast            uint32
	DwCPType              uint32
	DwCPCommand           uint32
	DwCPStandard          uint32
	DwCPKey               uint32
	BCP_APSTriggerBits    uint32
	BOEMCopyProtection    [256]byte
}

type VIDEO_BANK_SELECT struct {
	Length                    uint32
	Size                      uint32
	BankingFlags              uint32
	BankingType               uint32
	PlanarHCBankingType       uint32
	BitmapWidthInBytes        uint32
	BitmapSize                uint32
	Granularity               uint32
	PlanarHCGranularity       uint32
	CodeOffset                uint32
	PlanarHCBankCodeOffset    uint32
	PlanarHCEnableCodeOffset  uint32
	PlanarHCDisableCodeOffset uint32
}

type VIDEO_BRIGHTNESS_POLICY_Anonymous_e__Struct struct {
	BatteryLevel byte
	Brightness   byte
}

type VIDEO_BRIGHTNESS_POLICY struct {
	DefaultToBiosPolicy foundation.BOOLEAN
	LevelCount          byte
	Level               [1]uintptr
}

// VIDEO_CLUT_Anonymous_e__Union is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type VIDEO_CLUT_Anonymous_e__Union struct {
	Data [1]uint32
}

type VIDEO_CLUT struct {
	NumEntries  uint16
	FirstEntry  uint16
	LookupTable [1]uintptr
}

type VIDEO_CLUTDATA struct {
	Red    byte
	Green  byte
	Blue   byte
	Unused byte
}

type VIDEO_COLOR_CAPABILITIES struct {
	Length              uint32
	AttributeFlags      uint32
	RedPhosphoreDecay   int32
	GreenPhosphoreDecay int32
	BluePhosphoreDecay  int32
	WhiteChromaticity_x int32
	WhiteChromaticity_y int32
	WhiteChromaticity_Y int32
	RedChromaticity_x   int32
	RedChromaticity_y   int32
	GreenChromaticity_x int32
	GreenChromaticity_y int32
	BlueChromaticity_x  int32
	BlueChromaticity_y  int32
	WhiteGamma          int32
	RedGamma            int32
	GreenGamma          int32
	BlueGamma           int32
}

type VIDEO_COLOR_LUT_DATA struct {
	Length        uint32
	LutDataFormat uint32
	LutData       [1]byte
}

type VIDEO_CURSOR_ATTRIBUTES struct {
	Width  uint16
	Height uint16
	Column int16
	Row    int16
	Rate   byte
	Enable byte
}

type VIDEO_CURSOR_POSITION struct {
	Column int16
	Row    int16
}

type VIDEO_DEVICE_SESSION_STATUS struct {
	BEnable  uint32
	BSuccess uint32
}

type VIDEO_HARDWARE_STATE struct {
	StateHeader *VIDEO_HARDWARE_STATE_HEADER
	StateLength uint32
}

type VIDEO_HARDWARE_STATE_HEADER struct {
	Length                       uint32
	PortValue                    [48]byte
	AttribIndexDataState         uint32
	BasicSequencerOffset         uint32
	BasicCrtContOffset           uint32
	BasicGraphContOffset         uint32
	BasicAttribContOffset        uint32
	BasicDacOffset               uint32
	BasicLatchesOffset           uint32
	ExtendedSequencerOffset      uint32
	ExtendedCrtContOffset        uint32
	ExtendedGraphContOffset      uint32
	ExtendedAttribContOffset     uint32
	ExtendedDacOffset            uint32
	ExtendedValidatorStateOffset uint32
	ExtendedMiscDataOffset       uint32
	PlaneLength                  uint32
	Plane1Offset                 uint32
	Plane2Offset                 uint32
	Plane3Offset                 uint32
	Plane4Offset                 uint32
	VGAStateFlags                uint32
	DIBOffset                    uint32
	DIBBitsPerPixel              uint32
	DIBXResolution               uint32
	DIBYResolution               uint32
	DIBXlatOffset                uint32
	DIBXlatLength                uint32
	VesaInfoOffset               uint32
	FrameBufferData              unsafe.Pointer
}

type VIDEO_LOAD_FONT_INFORMATION struct {
	WidthInPixels  uint16
	HeightInPixels uint16
	FontSize       uint32
	Font           [1]byte
}

type VIDEO_LUT_RGB256WORDS struct {
	Red   [256]uint16
	Green [256]uint16
	Blue  [256]uint16
}

type VIDEO_MEMORY struct {
	RequestedVirtualAddress unsafe.Pointer
}

type VIDEO_MEMORY_INFORMATION struct {
	VideoRamBase      unsafe.Pointer
	VideoRamLength    uint32
	FrameBufferBase   unsafe.Pointer
	FrameBufferLength uint32
}

type VIDEO_MODE struct {
	RequestedMode uint32
}

type VIDEO_MODE_INFORMATION struct {
	Length                       uint32
	ModeIndex                    uint32
	VisScreenWidth               uint32
	VisScreenHeight              uint32
	ScreenStride                 uint32
	NumberOfPlanes               uint32
	BitsPerPlane                 uint32
	Frequency                    uint32
	XMillimeter                  uint32
	YMillimeter                  uint32
	NumberRedBits                uint32
	NumberGreenBits              uint32
	NumberBlueBits               uint32
	RedMask                      uint32
	GreenMask                    uint32
	BlueMask                     uint32
	AttributeFlags               uint32
	VideoMemoryBitmapWidth       uint32
	VideoMemoryBitmapHeight      uint32
	DriverSpecificAttributeFlags uint32
}

type VIDEO_MONITOR_DESCRIPTOR struct {
	DescriptorSize uint32
	Descriptor     [1]byte
}

type VIDEO_NUM_MODES struct {
	NumModes              uint32
	ModeInformationLength uint32
}

type VIDEO_PALETTE_DATA struct {
	NumEntries uint16
	FirstEntry uint16
	Colors     [1]uint16
}

type VIDEO_PERFORMANCE_COUNTER struct {
	NbOfAllocationEvicted  [10]uint64
	NbOfAllocationMarked   [10]uint64
	NbOfAllocationRestored [10]uint64
	KBytesEvicted          [10]uint64
	KBytesMarked           [10]uint64
	KBytesRestored         [10]uint64
	NbProcessCommited      uint64
	NbAllocationCommited   uint64
	NbAllocationMarked     uint64
	KBytesAllocated        uint64
	KBytesAvailable        uint64
	KBytesCurMarked        uint64
	Reference              uint64
	Unreference            uint64
	TrueReference          uint64
	NbOfPageIn             uint64
	KBytesPageIn           uint64
	NbOfPageOut            uint64
	KBytesPageOut          uint64
	NbOfRotateOut          uint64
	KBytesRotateOut        uint64
}

type VIDEO_POINTER_ATTRIBUTES struct {
	Flags        uint32
	Width        uint32
	Height       uint32
	WidthInBytes uint32
	Enable       uint32
	Column       int16
	Row          int16
	Pixels       [1]byte
}

type VIDEO_POINTER_CAPABILITIES struct {
	Flags            uint32
	MaxWidth         uint32
	MaxHeight        uint32
	HWPtrBitmapStart uint32
	HWPtrBitmapEnd   uint32
}

type VIDEO_POINTER_POSITION struct {
	Column int16
	Row    int16
}

type VIDEO_POWER_MANAGEMENT struct {
	Length      uint32
	DPMSVersion uint32
	PowerState  uint32
}

type VIDEO_PUBLIC_ACCESS_RANGES struct {
	InIoSpace       uint32
	MappedInIoSpace uint32
	VirtualAddress  unsafe.Pointer
}

type VIDEO_QUERY_PERFORMANCE_COUNTER struct {
	BufferSize uint32
	Buffer     *VIDEO_PERFORMANCE_COUNTER
}

type VIDEO_REGISTER_VDM struct {
	MinimumStateSize uint32
}

type VIDEO_SHARE_MEMORY struct {
	ProcessHandle           foundation.HANDLE
	ViewOffset              uint32
	ViewSize                uint32
	RequestedVirtualAddress unsafe.Pointer
}

type VIDEO_SHARE_MEMORY_INFORMATION struct {
	SharedViewOffset uint32
	SharedViewSize   uint32
	VirtualAddress   unsafe.Pointer
}

type VIDEO_VDM struct {
	ProcessHandle foundation.HANDLE
}

type VIDEO_WIN32K_CALLBACKS struct {
	PhysDisp          unsafe.Pointer
	Callout           PVIDEO_WIN32K_CALLOUT
	BACPI             uint32
	PPhysDeviceObject foundation.HANDLE
	DualviewFlags     uint32
}

type VIDEO_WIN32K_CALLBACKS_PARAMS struct {
	CalloutType       VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE
	PhysDisp          unsafe.Pointer
	Param             uintptr
	Status            int32
	LockUserSession   foundation.BOOLEAN
	IsPostDevice      foundation.BOOLEAN
	SurpriseRemoval   foundation.BOOLEAN
	WaitForQueueReady foundation.BOOLEAN
}

// WCRUN: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-wcrun
type WCRUN struct {
	WcLow   uint16
	CGlyphs uint16
	Phg     *uint32
}

// WNDOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-wndobj
type WNDOBJ struct {
	CoClient   CLIPOBJ
	PvConsumer unsafe.Pointer
	RclClient  foundation.RECTL
	PsoOwner   *SURFOBJ
}

// XFORML: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-xforml
type XFORML struct {
	EM11 float32
	EM12 float32
	EM21 float32
	EM22 float32
	EDx  float32
	EDy  float32
}

// XFORMOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-xformobj
type XFORMOBJ struct {
	UlReserved uint32
}

// XLATEOBJ: https://learn.microsoft.com/windows/win32/api/winddi/ns-winddi-xlateobj
type XLATEOBJ struct {
	IUniq    uint32
	FlXlate  uint32
	ISrcType uint16
	IDstType uint16
	CEntries uint32
	PulXlate *uint32
}

// FREEOBJPROC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DRIVEROBJ) foundation.BOOL.
type FREEOBJPROC uintptr

// PFN is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() uintptr.
type PFN uintptr

// PFN_DrvAccumulateD3DDirtyRect is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *CDDDXGK_REDIRBITMAPPRESENTINFO) foundation.BOOL.
type PFN_DrvAccumulateD3DDirtyRect uintptr

// PFN_DrvAlphaBlend is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *foundation.RECTL, *foundation.RECTL, *BLENDOBJ) foundation.BOOL.
type PFN_DrvAlphaBlend uintptr

// PFN_DrvAssertMode is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.BOOL) foundation.BOOL.
type PFN_DrvAssertMode uintptr

// PFN_DrvAssociateSharedSurface is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, foundation.HANDLE, foundation.HANDLE, foundation.SIZE) foundation.BOOL.
type PFN_DrvAssociateSharedSurface uintptr

// PFN_DrvBitBlt is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *foundation.RECTL, *foundation.POINTL, *foundation.POINTL, *BRUSHOBJ, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvBitBlt uintptr

// PFN_DrvCompletePDEV is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, HDEV).
type PFN_DrvCompletePDEV uintptr

// PFN_DrvCopyBits is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *foundation.RECTL, *foundation.POINTL) foundation.BOOL.
type PFN_DrvCopyBits uintptr

// PFN_DrvCreateDeviceBitmap is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.SIZE, uint32) graphicsgdi.HBITMAP.
type PFN_DrvCreateDeviceBitmap uintptr

// PFN_DrvCreateDeviceBitmapEx is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.SIZE, uint32, uint32, DHSURF, uint32, uint32, *foundation.HANDLE) graphicsgdi.HBITMAP.
type PFN_DrvCreateDeviceBitmapEx uintptr

// PFN_DrvDeleteDeviceBitmap is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHSURF).
type PFN_DrvDeleteDeviceBitmap uintptr

// PFN_DrvDeleteDeviceBitmapEx is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHSURF).
type PFN_DrvDeleteDeviceBitmapEx uintptr

// PFN_DrvDeriveSurface is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*graphicsdirectdraw.DD_DIRECTDRAW_GLOBAL, *graphicsdirectdraw.DD_SURFACE_LOCAL) graphicsgdi.HBITMAP.
type PFN_DrvDeriveSurface uintptr

// PFN_DrvDescribePixelFormat is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, int32, uint32, *graphicsopengl.PIXELFORMATDESCRIPTOR) int32.
type PFN_DrvDescribePixelFormat uintptr

// PFN_DrvDestroyFont is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FONTOBJ).
type PFN_DrvDestroyFont uintptr

// PFN_DrvDisableDirectDraw is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV).
type PFN_DrvDisableDirectDraw uintptr

// PFN_DrvDisableDriver is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PFN_DrvDisableDriver uintptr

// PFN_DrvDisablePDEV is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV).
type PFN_DrvDisablePDEV uintptr

// PFN_DrvDisableSurface is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV).
type PFN_DrvDisableSurface uintptr

// PFN_DrvDitherColor is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, uint32, uint32, *uint32) uint32.
type PFN_DrvDitherColor uintptr

// PFN_DrvDrawEscape is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, uint32, *CLIPOBJ, *foundation.RECTL, uint32, unsafe.Pointer) uint32.
type PFN_DrvDrawEscape uintptr

// PFN_DrvEnableDirectDraw is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *graphicsdirectdraw.DD_CALLBACKS, *graphicsdirectdraw.DD_SURFACECALLBACKS, *graphicsdirectdraw.DD_PALETTECALLBACKS) foundation.BOOL.
type PFN_DrvEnableDirectDraw uintptr

// PFN_DrvEnableDriver is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uint32, uint32, *DRVENABLEDATA) foundation.BOOL.
type PFN_DrvEnableDriver uintptr

// PFN_DrvEnablePDEV is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*graphicsgdi.DEVMODEW, foundation.PWSTR, uint32, *HSURF, uint32, *GDIINFO, uint32, *DEVINFO, HDEV, foundation.PWSTR, foundation.HANDLE) DHPDEV.
type PFN_DrvEnablePDEV uintptr

// PFN_DrvEnableSurface is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV) HSURF.
type PFN_DrvEnableSurface uintptr

// PFN_DrvEndDoc is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, uint32) foundation.BOOL.
type PFN_DrvEndDoc uintptr

// PFN_DrvEndDxInterop is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, foundation.BOOL, *foundation.BOOL, unsafe.Pointer) foundation.BOOL.
type PFN_DrvEndDxInterop uintptr

// PFN_DrvEscape is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, uint32, uint32, unsafe.Pointer, uint32, unsafe.Pointer) uint32.
type PFN_DrvEscape uintptr

// PFN_DrvFillPath is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *PATHOBJ, *CLIPOBJ, *BRUSHOBJ, *foundation.POINTL, uint32, uint32) foundation.BOOL.
type PFN_DrvFillPath uintptr

// PFN_DrvFontManagement is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *FONTOBJ, uint32, uint32, unsafe.Pointer, uint32, unsafe.Pointer) uint32.
type PFN_DrvFontManagement uintptr

// PFN_DrvFree is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, uintptr).
type PFN_DrvFree uintptr

// PFN_DrvGetDirectDrawInfo is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *graphicsdirectdraw.DD_HALINFO, *uint32, *graphicsdirectdraw.VIDEOMEMORY, *uint32, *uint32) foundation.BOOL.
type PFN_DrvGetDirectDrawInfo uintptr

// PFN_DrvGetGlyphMode is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *FONTOBJ) uint32.
type PFN_DrvGetGlyphMode uintptr

// PFN_DrvGetModes is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(foundation.HANDLE, uint32, *graphicsgdi.DEVMODEW) uint32.
type PFN_DrvGetModes uintptr

// PFN_DrvGetTrueTypeFile is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr, *uint32) unsafe.Pointer.
type PFN_DrvGetTrueTypeFile uintptr

// PFN_DrvGradientFill is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *CLIPOBJ, *XLATEOBJ, *graphicsgdi.TRIVERTEX, uint32, unsafe.Pointer, uint32, *foundation.RECTL, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvGradientFill uintptr

// PFN_DrvIcmCheckBitmapBits is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.HANDLE, *SURFOBJ, *byte) foundation.BOOL.
type PFN_DrvIcmCheckBitmapBits uintptr

// PFN_DrvIcmCreateColorTransform is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *uicolorsystem.LOGCOLORSPACEW, unsafe.Pointer, uint32, unsafe.Pointer, uint32, unsafe.Pointer, uint32, uint32) foundation.HANDLE.
type PFN_DrvIcmCreateColorTransform uintptr

// PFN_DrvIcmDeleteColorTransform is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.HANDLE) foundation.BOOL.
type PFN_DrvIcmDeleteColorTransform uintptr

// PFN_DrvIcmSetDeviceGammaRamp is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, uint32, unsafe.Pointer) foundation.BOOL.
type PFN_DrvIcmSetDeviceGammaRamp uintptr

// PFN_DrvLineTo is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *CLIPOBJ, *BRUSHOBJ, int32, int32, int32, int32, *foundation.RECTL, uint32) foundation.BOOL.
type PFN_DrvLineTo uintptr

// PFN_DrvLoadFontFile is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uint32, *uintptr, *unsafe.Pointer, *uint32, *graphicsgdi.DESIGNVECTOR, uint32, uint32) uintptr.
type PFN_DrvLoadFontFile uintptr

// PFN_DrvLockDisplayArea is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *foundation.RECTL).
type PFN_DrvLockDisplayArea uintptr

// PFN_DrvMovePointer is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, int32, int32, *foundation.RECTL).
type PFN_DrvMovePointer uintptr

// PFN_DrvNextBand is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *foundation.POINTL) foundation.BOOL.
type PFN_DrvNextBand uintptr

// PFN_DrvNotify is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, uint32, unsafe.Pointer).
type PFN_DrvNotify uintptr

// PFN_DrvPaint is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *CLIPOBJ, *BRUSHOBJ, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvPaint uintptr

// PFN_DrvPlgBlt is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *graphicsgdi.COLORADJUSTMENT, *foundation.POINTL, *POINTFIX, *foundation.RECTL, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvPlgBlt uintptr

// PFN_DrvQueryAdvanceWidths is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *FONTOBJ, uint32, *uint32, unsafe.Pointer, uint32) foundation.BOOL.
type PFN_DrvQueryAdvanceWidths uintptr

// PFN_DrvQueryDeviceSupport is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *XLATEOBJ, *XFORMOBJ, uint32, uint32, unsafe.Pointer, uint32, unsafe.Pointer) foundation.BOOL.
type PFN_DrvQueryDeviceSupport uintptr

// PFN_DrvQueryFont is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, uintptr, uint32, *uintptr) *IFIMETRICS.
type PFN_DrvQueryFont uintptr

// PFN_DrvQueryFontCaps is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uint32, *uint32) int32.
type PFN_DrvQueryFontCaps uintptr

// PFN_DrvQueryFontData is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *FONTOBJ, uint32, uint32, *GLYPHDATA, unsafe.Pointer, uint32) int32.
type PFN_DrvQueryFontData uintptr

// PFN_DrvQueryFontFile is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr, uint32, uint32, *uint32) int32.
type PFN_DrvQueryFontFile uintptr

// PFN_DrvQueryFontTree is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, uintptr, uint32, uint32, *uintptr) unsafe.Pointer.
type PFN_DrvQueryFontTree uintptr

// PFN_DrvQueryGlyphAttrs is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FONTOBJ, uint32) *FD_GLYPHATTR.
type PFN_DrvQueryGlyphAttrs uintptr

// PFN_DrvQueryPerBandInfo is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *PERBANDINFO) foundation.BOOL.
type PFN_DrvQueryPerBandInfo uintptr

// PFN_DrvQuerySpoolType is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.PWSTR) foundation.BOOL.
type PFN_DrvQuerySpoolType uintptr

// PFN_DrvQueryTrueTypeOutline is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *FONTOBJ, uint32, foundation.BOOL, *GLYPHDATA, uint32, *graphicsgdi.TTPOLYGONHEADER) int32.
type PFN_DrvQueryTrueTypeOutline uintptr

// PFN_DrvQueryTrueTypeSection is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uint32, uint32, uint32, *foundation.HANDLE, *int32) int32.
type PFN_DrvQueryTrueTypeSection uintptr

// PFN_DrvQueryTrueTypeTable is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr, uint32, uint32, int32, uint32, *byte, **byte, *uint32) int32.
type PFN_DrvQueryTrueTypeTable uintptr

// PFN_DrvRealizeBrush is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*BRUSHOBJ, *SURFOBJ, *SURFOBJ, *SURFOBJ, *XLATEOBJ, uint32) foundation.BOOL.
type PFN_DrvRealizeBrush uintptr

// PFN_DrvRenderHint is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, uint32, uintptr, unsafe.Pointer) int32.
type PFN_DrvRenderHint uintptr

// PFN_DrvResetDevice is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, unsafe.Pointer) uint32.
type PFN_DrvResetDevice uintptr

// PFN_DrvResetPDEV is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, DHPDEV) foundation.BOOL.
type PFN_DrvResetPDEV uintptr

// PFN_DrvSaveScreenBits is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, uint32, uintptr, *foundation.RECTL) uintptr.
type PFN_DrvSaveScreenBits uintptr

// PFN_DrvSendPage is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ) foundation.BOOL.
type PFN_DrvSendPage uintptr

// PFN_DrvSetPalette is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *PALOBJ, uint32, uint32, uint32) foundation.BOOL.
type PFN_DrvSetPalette uintptr

// PFN_DrvSetPixelFormat is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, int32, foundation.HWND) foundation.BOOL.
type PFN_DrvSetPixelFormat uintptr

// PFN_DrvSetPointerShape is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *SURFOBJ, *XLATEOBJ, int32, int32, int32, int32, *foundation.RECTL, uint32) uint32.
type PFN_DrvSetPointerShape uintptr

// PFN_DrvStartBanding is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *foundation.POINTL) foundation.BOOL.
type PFN_DrvStartBanding uintptr

// PFN_DrvStartDoc is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, foundation.PWSTR, uint32) foundation.BOOL.
type PFN_DrvStartDoc uintptr

// PFN_DrvStartDxInterop is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, foundation.BOOL, unsafe.Pointer) foundation.BOOL.
type PFN_DrvStartDxInterop uintptr

// PFN_DrvStartPage is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ) foundation.BOOL.
type PFN_DrvStartPage uintptr

// PFN_DrvStretchBlt is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *graphicsgdi.COLORADJUSTMENT, *foundation.POINTL, *foundation.RECTL, *foundation.RECTL, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvStretchBlt uintptr

// PFN_DrvStretchBltROP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *graphicsgdi.COLORADJUSTMENT, *foundation.POINTL, *foundation.RECTL, *foundation.RECTL, *foundation.POINTL, uint32, *BRUSHOBJ, uint32) foundation.BOOL.
type PFN_DrvStretchBltROP uintptr

// PFN_DrvStrokeAndFillPath is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *PATHOBJ, *CLIPOBJ, *XFORMOBJ, *BRUSHOBJ, *LINEATTRS, *BRUSHOBJ, *foundation.POINTL, uint32, uint32) foundation.BOOL.
type PFN_DrvStrokeAndFillPath uintptr

// PFN_DrvStrokePath is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *PATHOBJ, *CLIPOBJ, *XFORMOBJ, *BRUSHOBJ, *foundation.POINTL, *LINEATTRS, uint32) foundation.BOOL.
type PFN_DrvStrokePath uintptr

// PFN_DrvSurfaceComplete is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, foundation.HANDLE) foundation.BOOL.
type PFN_DrvSurfaceComplete uintptr

// PFN_DrvSwapBuffers is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *WNDOBJ) foundation.BOOL.
type PFN_DrvSwapBuffers uintptr

// PFN_DrvSynchronize is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *foundation.RECTL).
type PFN_DrvSynchronize uintptr

// PFN_DrvSynchronizeRedirectionBitmaps is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *uint64) foundation.NTSTATUS.
type PFN_DrvSynchronizeRedirectionBitmaps uintptr

// PFN_DrvSynchronizeSurface is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *foundation.RECTL, uint32).
type PFN_DrvSynchronizeSurface uintptr

// PFN_DrvTextOut is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *STROBJ, *FONTOBJ, *CLIPOBJ, *foundation.RECTL, *foundation.RECTL, *BRUSHOBJ, *BRUSHOBJ, *foundation.POINTL, uint32) foundation.BOOL.
type PFN_DrvTextOut uintptr

// PFN_DrvTransparentBlt is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*SURFOBJ, *SURFOBJ, *CLIPOBJ, *XLATEOBJ, *foundation.RECTL, *foundation.RECTL, uint32, uint32) foundation.BOOL.
type PFN_DrvTransparentBlt uintptr

// PFN_DrvUnloadFontFile is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr) foundation.BOOL.
type PFN_DrvUnloadFontFile uintptr

// PFN_DrvUnlockDisplayArea is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(DHPDEV, *foundation.RECTL).
type PFN_DrvUnlockDisplayArea uintptr

// PVIDEO_WIN32K_CALLOUT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type PVIDEO_WIN32K_CALLOUT uintptr

// SORTCOMP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer) int32.
type SORTCOMP uintptr

// WNDOBJCHANGEPROC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*WNDOBJ, uint32).
type WNDOBJCHANGEPROC uintptr
