// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package compression

import (
	storagecompression "github.com/deploymenttheory/go-bindings-win32/bindings/win32/storage/compression"
)

type COMPRESS_ALLOCATION_ROUTINES = storagecompression.COMPRESS_ALLOCATION_ROUTINES
