// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package js

import (
	systemjs "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/js"
)

type JsErrorCode = systemjs.JsErrorCode
type JsMemoryEventType = systemjs.JsMemoryEventType
type JsRuntimeAttributes = systemjs.JsRuntimeAttributes
type JsRuntimeVersion = systemjs.JsRuntimeVersion
type JsValueType = systemjs.JsValueType
