// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package subsystemforlinux

// WSL_DISTRIBUTION_FLAGS: https://learn.microsoft.com/windows/win32/api/wslapi/ne-wslapi-wsl_distribution_flags
type WSL_DISTRIBUTION_FLAGS int32

const (
	WSL_DISTRIBUTION_FLAGS_NONE                  WSL_DISTRIBUTION_FLAGS = 0
	WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP        WSL_DISTRIBUTION_FLAGS = 1
	WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH        WSL_DISTRIBUTION_FLAGS = 2
	WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING WSL_DISTRIBUTION_FLAGS = 4
)
