// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package windowsnetworkvirtualization binds the Windows.Win32.NetworkManagement.WindowsNetworkVirtualization API surface.
package windowsnetworkvirtualization
