// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package windowsnetworkvirtualization

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	systemio "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/io"
)

var (
	modwnvapi = win32.NewDLL("wnvapi.dll")
)

var (
	procWnvOpen                = modwnvapi.NewProc("WnvOpen")
	procWnvRequestNotification = modwnvapi.NewProc("WnvRequestNotification")
)

// Procs exposes this package's lazily resolved exports for availability
// probing: Procs.<Function>.Find() reports nil, or the *win32.ProcError a
// call to <Function> would panic with on this system (an export missing from
// this Windows build, or a DLL that is not installed).
var Procs = struct {
	WnvOpen                *win32.Proc
	WnvRequestNotification *win32.Proc
}{
	WnvOpen:                procWnvOpen,
	WnvRequestNotification: procWnvRequestNotification,
}

// WnvOpen calls wnvapi!WnvOpen.
// https://learn.microsoft.com/windows/win32/api/wnvapi/nf-wnvapi-wnvopen
// Minimum OS: windowsserver2012.
func WnvOpen() foundation.HANDLE {
	r1, _, _ := syscall.SyscallN(procWnvOpen.Addr())
	return foundation.HANDLE(r1)
}

// WnvRequestNotification calls wnvapi!WnvRequestNotification.
// https://learn.microsoft.com/windows/win32/api/wnvapi/nf-wnvapi-wnvrequestnotification
// Minimum OS: windowsserver2012.
func WnvRequestNotification(WnvHandle foundation.HANDLE, NotificationParam *WNV_NOTIFICATION_PARAM, Overlapped *systemio.OVERLAPPED, BytesTransferred *uint32) uint32 {
	r1, _, _ := syscall.SyscallN(procWnvRequestNotification.Addr(), uintptr(WnvHandle), uintptr(unsafe.Pointer(NotificationParam)), uintptr(unsafe.Pointer(Overlapped)), uintptr(unsafe.Pointer(BytesTransferred)))
	return uint32(r1)
}
