// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package componentservices provides idiomatic Go wrappers over the raw Windows.Win32.System.ComponentServices bindings.
package componentservices
