// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package configurationsnapin

import (
	securityconfigurationsnapin "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security/configurationsnapin"
)

type SCESVC_INFO_TYPE = securityconfigurationsnapin.SCESVC_INFO_TYPE
type SCE_LOG_ERR_LEVEL = securityconfigurationsnapin.SCE_LOG_ERR_LEVEL
