// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package directcomposition

import (
	graphicsdirectcomposition "github.com/deploymenttheory/go-bindings-win32/bindings/win32/graphics/directcomposition"
)

type COMPOSITION_FRAME_STATS = graphicsdirectcomposition.COMPOSITION_FRAME_STATS
type COMPOSITION_STATS = graphicsdirectcomposition.COMPOSITION_STATS
type COMPOSITION_TARGET_ID = graphicsdirectcomposition.COMPOSITION_TARGET_ID
type COMPOSITION_TARGET_STATS = graphicsdirectcomposition.COMPOSITION_TARGET_STATS
type DCOMPOSITION_FRAME_STATISTICS = graphicsdirectcomposition.DCOMPOSITION_FRAME_STATISTICS
type DCompositionInkTrailPoint = graphicsdirectcomposition.DCompositionInkTrailPoint
