// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package stationsanddesktops

// DESKTOPENUMPROCA is a callback pointer: create one with syscall.NewCallback
// using the shape func(foundation.PSTR, foundation.LPARAM) uintptr (the native return type is
// foundation.BOOL; NewCallback requires a uintptr-sized result).
type DESKTOPENUMPROCA uintptr

// DESKTOPENUMPROCW is a callback pointer: create one with syscall.NewCallback
// using the shape func(foundation.PWSTR, foundation.LPARAM) uintptr (the native return type is
// foundation.BOOL; NewCallback requires a uintptr-sized result).
type DESKTOPENUMPROCW uintptr

// WINSTAENUMPROCA is a callback pointer: create one with syscall.NewCallback
// using the shape func(foundation.PSTR, foundation.LPARAM) uintptr (the native return type is
// foundation.BOOL; NewCallback requires a uintptr-sized result).
type WINSTAENUMPROCA uintptr

// WINSTAENUMPROCW is a callback pointer: create one with syscall.NewCallback
// using the shape func(foundation.PWSTR, foundation.LPARAM) uintptr (the native return type is
// foundation.BOOL; NewCallback requires a uintptr-sized result).
type WINSTAENUMPROCW uintptr
