// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package wifi

import (
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	networkmanagementwifi "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networkmanagement/wifi"
	systemcomidiom "github.com/deploymenttheory/go-bindings-win32/opinionated/idiomatic/win32/system/com"
)

// IDot11AdHocInterface is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocInterface with error-returning methods.
type IDot11AdHocInterface struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocInterface
}

// WrapIDot11AdHocInterface wraps a raw networkmanagementwifi.IDot11AdHocInterface pointer.
func WrapIDot11AdHocInterface(raw *networkmanagementwifi.IDot11AdHocInterface) IDot11AdHocInterface {
	return IDot11AdHocInterface{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// GetDeviceSignature wraps the raw GetDeviceSignature call.
func (self IDot11AdHocInterface) GetDeviceSignature(pSignature *win32.GUID) error {
	return win32.HRESULTError(int32(self.Raw.GetDeviceSignature(pSignature)))
}

// GetFriendlyName wraps the raw GetFriendlyName call.
func (self IDot11AdHocInterface) GetFriendlyName(ppszName *foundation.PWSTR) error {
	return win32.HRESULTError(int32(self.Raw.GetFriendlyName(ppszName)))
}

// IsDot11d wraps the raw IsDot11d call.
func (self IDot11AdHocInterface) IsDot11d(pf11d *byte) error {
	return win32.HRESULTError(int32(self.Raw.IsDot11d(pf11d)))
}

// IsAdHocCapable wraps the raw IsAdHocCapable call.
func (self IDot11AdHocInterface) IsAdHocCapable(pfAdHocCapable *byte) error {
	return win32.HRESULTError(int32(self.Raw.IsAdHocCapable(pfAdHocCapable)))
}

// IsRadioOn wraps the raw IsRadioOn call.
func (self IDot11AdHocInterface) IsRadioOn(pfIsRadioOn *byte) error {
	return win32.HRESULTError(int32(self.Raw.IsRadioOn(pfIsRadioOn)))
}

// GetActiveNetwork wraps the raw GetActiveNetwork call.
func (self IDot11AdHocInterface) GetActiveNetwork(ppNetwork **networkmanagementwifi.IDot11AdHocNetwork) error {
	return win32.HRESULTError(int32(self.Raw.GetActiveNetwork(ppNetwork)))
}

// GetIEnumSecuritySettings wraps the raw GetIEnumSecuritySettings call.
func (self IDot11AdHocInterface) GetIEnumSecuritySettings(ppEnum **networkmanagementwifi.IEnumDot11AdHocSecuritySettings) error {
	return win32.HRESULTError(int32(self.Raw.GetIEnumSecuritySettings(ppEnum)))
}

// GetIEnumDot11AdHocNetworks wraps the raw GetIEnumDot11AdHocNetworks call.
func (self IDot11AdHocInterface) GetIEnumDot11AdHocNetworks(pFilterGuid *win32.GUID, ppEnum **networkmanagementwifi.IEnumDot11AdHocNetworks) error {
	return win32.HRESULTError(int32(self.Raw.GetIEnumDot11AdHocNetworks(pFilterGuid, ppEnum)))
}

// GetStatus wraps the raw GetStatus call.
func (self IDot11AdHocInterface) GetStatus(pState *networkmanagementwifi.DOT11_ADHOC_NETWORK_CONNECTION_STATUS) error {
	return win32.HRESULTError(int32(self.Raw.GetStatus(pState)))
}

// IDot11AdHocInterfaceNotificationSink is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocInterfaceNotificationSink with error-returning methods.
type IDot11AdHocInterfaceNotificationSink struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocInterfaceNotificationSink
}

// WrapIDot11AdHocInterfaceNotificationSink wraps a raw networkmanagementwifi.IDot11AdHocInterfaceNotificationSink pointer.
func WrapIDot11AdHocInterfaceNotificationSink(raw *networkmanagementwifi.IDot11AdHocInterfaceNotificationSink) IDot11AdHocInterfaceNotificationSink {
	return IDot11AdHocInterfaceNotificationSink{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// OnConnectionStatusChange wraps the raw OnConnectionStatusChange call.
func (self IDot11AdHocInterfaceNotificationSink) OnConnectionStatusChange(eStatus networkmanagementwifi.DOT11_ADHOC_NETWORK_CONNECTION_STATUS) error {
	return win32.HRESULTError(int32(self.Raw.OnConnectionStatusChange(eStatus)))
}

// IDot11AdHocManager is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocManager with error-returning methods.
type IDot11AdHocManager struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocManager
}

// WrapIDot11AdHocManager wraps a raw networkmanagementwifi.IDot11AdHocManager pointer.
func WrapIDot11AdHocManager(raw *networkmanagementwifi.IDot11AdHocManager) IDot11AdHocManager {
	return IDot11AdHocManager{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// CreateNetwork wraps the raw CreateNetwork call.
func (self IDot11AdHocManager) CreateNetwork(Name string, Password string, GeographicalId int32, pInterface *networkmanagementwifi.IDot11AdHocInterface, pSecurity *networkmanagementwifi.IDot11AdHocSecuritySettings, pContextGuid *win32.GUID, pIAdHoc **networkmanagementwifi.IDot11AdHocNetwork) error {
	_Name := win32.UTF16Ptr(Name)
	_Password := win32.UTF16Ptr(Password)
	return win32.HRESULTError(int32(self.Raw.CreateNetwork(foundation.PWSTR(_Name), foundation.PWSTR(_Password), GeographicalId, pInterface, pSecurity, pContextGuid, pIAdHoc)))
}

// CommitCreatedNetwork wraps the raw CommitCreatedNetwork call.
func (self IDot11AdHocManager) CommitCreatedNetwork(pIAdHoc *networkmanagementwifi.IDot11AdHocNetwork, fSaveProfile foundation.BOOLEAN, fMakeSavedProfileUserSpecific foundation.BOOLEAN) error {
	return win32.HRESULTError(int32(self.Raw.CommitCreatedNetwork(pIAdHoc, fSaveProfile, fMakeSavedProfileUserSpecific)))
}

// GetIEnumDot11AdHocNetworks wraps the raw GetIEnumDot11AdHocNetworks call.
func (self IDot11AdHocManager) GetIEnumDot11AdHocNetworks(pContextGuid *win32.GUID, ppEnum **networkmanagementwifi.IEnumDot11AdHocNetworks) error {
	return win32.HRESULTError(int32(self.Raw.GetIEnumDot11AdHocNetworks(pContextGuid, ppEnum)))
}

// GetIEnumDot11AdHocInterfaces wraps the raw GetIEnumDot11AdHocInterfaces call.
func (self IDot11AdHocManager) GetIEnumDot11AdHocInterfaces(ppEnum **networkmanagementwifi.IEnumDot11AdHocInterfaces) error {
	return win32.HRESULTError(int32(self.Raw.GetIEnumDot11AdHocInterfaces(ppEnum)))
}

// GetNetwork wraps the raw GetNetwork call.
func (self IDot11AdHocManager) GetNetwork(NetworkSignature *win32.GUID, pNetwork **networkmanagementwifi.IDot11AdHocNetwork) error {
	return win32.HRESULTError(int32(self.Raw.GetNetwork(NetworkSignature, pNetwork)))
}

// IDot11AdHocManagerNotificationSink is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocManagerNotificationSink with error-returning methods.
type IDot11AdHocManagerNotificationSink struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocManagerNotificationSink
}

// WrapIDot11AdHocManagerNotificationSink wraps a raw networkmanagementwifi.IDot11AdHocManagerNotificationSink pointer.
func WrapIDot11AdHocManagerNotificationSink(raw *networkmanagementwifi.IDot11AdHocManagerNotificationSink) IDot11AdHocManagerNotificationSink {
	return IDot11AdHocManagerNotificationSink{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// OnNetworkAdd wraps the raw OnNetworkAdd call.
func (self IDot11AdHocManagerNotificationSink) OnNetworkAdd(pIAdHocNetwork *networkmanagementwifi.IDot11AdHocNetwork) error {
	return win32.HRESULTError(int32(self.Raw.OnNetworkAdd(pIAdHocNetwork)))
}

// OnNetworkRemove wraps the raw OnNetworkRemove call.
func (self IDot11AdHocManagerNotificationSink) OnNetworkRemove(Signature *win32.GUID) error {
	return win32.HRESULTError(int32(self.Raw.OnNetworkRemove(Signature)))
}

// OnInterfaceAdd wraps the raw OnInterfaceAdd call.
func (self IDot11AdHocManagerNotificationSink) OnInterfaceAdd(pIAdHocInterface *networkmanagementwifi.IDot11AdHocInterface) error {
	return win32.HRESULTError(int32(self.Raw.OnInterfaceAdd(pIAdHocInterface)))
}

// OnInterfaceRemove wraps the raw OnInterfaceRemove call.
func (self IDot11AdHocManagerNotificationSink) OnInterfaceRemove(Signature *win32.GUID) error {
	return win32.HRESULTError(int32(self.Raw.OnInterfaceRemove(Signature)))
}

// IDot11AdHocNetwork is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocNetwork with error-returning methods.
type IDot11AdHocNetwork struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocNetwork
}

// WrapIDot11AdHocNetwork wraps a raw networkmanagementwifi.IDot11AdHocNetwork pointer.
func WrapIDot11AdHocNetwork(raw *networkmanagementwifi.IDot11AdHocNetwork) IDot11AdHocNetwork {
	return IDot11AdHocNetwork{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// GetStatus wraps the raw GetStatus call.
func (self IDot11AdHocNetwork) GetStatus(eStatus *networkmanagementwifi.DOT11_ADHOC_NETWORK_CONNECTION_STATUS) error {
	return win32.HRESULTError(int32(self.Raw.GetStatus(eStatus)))
}

// GetSSID wraps the raw GetSSID call.
func (self IDot11AdHocNetwork) GetSSID(ppszwSSID *foundation.PWSTR) error {
	return win32.HRESULTError(int32(self.Raw.GetSSID(ppszwSSID)))
}

// HasProfile wraps the raw HasProfile call.
func (self IDot11AdHocNetwork) HasProfile(pf11d *byte) error {
	return win32.HRESULTError(int32(self.Raw.HasProfile(pf11d)))
}

// GetProfileName wraps the raw GetProfileName call.
func (self IDot11AdHocNetwork) GetProfileName(ppszwProfileName *foundation.PWSTR) error {
	return win32.HRESULTError(int32(self.Raw.GetProfileName(ppszwProfileName)))
}

// DeleteProfile wraps the raw DeleteProfile call.
func (self IDot11AdHocNetwork) DeleteProfile() error {
	return win32.HRESULTError(int32(self.Raw.DeleteProfile()))
}

// GetSignalQuality wraps the raw GetSignalQuality call.
func (self IDot11AdHocNetwork) GetSignalQuality(puStrengthValue *uint32, puStrengthMax *uint32) error {
	return win32.HRESULTError(int32(self.Raw.GetSignalQuality(puStrengthValue, puStrengthMax)))
}

// GetSecuritySetting wraps the raw GetSecuritySetting call.
func (self IDot11AdHocNetwork) GetSecuritySetting(pAdHocSecuritySetting **networkmanagementwifi.IDot11AdHocSecuritySettings) error {
	return win32.HRESULTError(int32(self.Raw.GetSecuritySetting(pAdHocSecuritySetting)))
}

// GetContextGuid wraps the raw GetContextGuid call.
func (self IDot11AdHocNetwork) GetContextGuid(pContextGuid *win32.GUID) error {
	return win32.HRESULTError(int32(self.Raw.GetContextGuid(pContextGuid)))
}

// GetSignature wraps the raw GetSignature call.
func (self IDot11AdHocNetwork) GetSignature(pSignature *win32.GUID) error {
	return win32.HRESULTError(int32(self.Raw.GetSignature(pSignature)))
}

// GetInterface wraps the raw GetInterface call.
func (self IDot11AdHocNetwork) GetInterface(pAdHocInterface **networkmanagementwifi.IDot11AdHocInterface) error {
	return win32.HRESULTError(int32(self.Raw.GetInterface(pAdHocInterface)))
}

// Connect wraps the raw Connect call.
func (self IDot11AdHocNetwork) Connect(Passphrase string, GeographicalId int32, fSaveProfile foundation.BOOLEAN, fMakeSavedProfileUserSpecific foundation.BOOLEAN) error {
	_Passphrase := win32.UTF16Ptr(Passphrase)
	return win32.HRESULTError(int32(self.Raw.Connect(foundation.PWSTR(_Passphrase), GeographicalId, fSaveProfile, fMakeSavedProfileUserSpecific)))
}

// Disconnect wraps the raw Disconnect call.
func (self IDot11AdHocNetwork) Disconnect() error {
	return win32.HRESULTError(int32(self.Raw.Disconnect()))
}

// IDot11AdHocNetworkNotificationSink is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocNetworkNotificationSink with error-returning methods.
type IDot11AdHocNetworkNotificationSink struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocNetworkNotificationSink
}

// WrapIDot11AdHocNetworkNotificationSink wraps a raw networkmanagementwifi.IDot11AdHocNetworkNotificationSink pointer.
func WrapIDot11AdHocNetworkNotificationSink(raw *networkmanagementwifi.IDot11AdHocNetworkNotificationSink) IDot11AdHocNetworkNotificationSink {
	return IDot11AdHocNetworkNotificationSink{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// OnStatusChange wraps the raw OnStatusChange call.
func (self IDot11AdHocNetworkNotificationSink) OnStatusChange(eStatus networkmanagementwifi.DOT11_ADHOC_NETWORK_CONNECTION_STATUS) error {
	return win32.HRESULTError(int32(self.Raw.OnStatusChange(eStatus)))
}

// OnConnectFail wraps the raw OnConnectFail call.
func (self IDot11AdHocNetworkNotificationSink) OnConnectFail(eFailReason networkmanagementwifi.DOT11_ADHOC_CONNECT_FAIL_REASON) error {
	return win32.HRESULTError(int32(self.Raw.OnConnectFail(eFailReason)))
}

// IDot11AdHocSecuritySettings is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IDot11AdHocSecuritySettings with error-returning methods.
type IDot11AdHocSecuritySettings struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IDot11AdHocSecuritySettings
}

// WrapIDot11AdHocSecuritySettings wraps a raw networkmanagementwifi.IDot11AdHocSecuritySettings pointer.
func WrapIDot11AdHocSecuritySettings(raw *networkmanagementwifi.IDot11AdHocSecuritySettings) IDot11AdHocSecuritySettings {
	return IDot11AdHocSecuritySettings{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// GetDot11AuthAlgorithm wraps the raw GetDot11AuthAlgorithm call.
func (self IDot11AdHocSecuritySettings) GetDot11AuthAlgorithm(pAuth *networkmanagementwifi.DOT11_ADHOC_AUTH_ALGORITHM) error {
	return win32.HRESULTError(int32(self.Raw.GetDot11AuthAlgorithm(pAuth)))
}

// GetDot11CipherAlgorithm wraps the raw GetDot11CipherAlgorithm call.
func (self IDot11AdHocSecuritySettings) GetDot11CipherAlgorithm(pCipher *networkmanagementwifi.DOT11_ADHOC_CIPHER_ALGORITHM) error {
	return win32.HRESULTError(int32(self.Raw.GetDot11CipherAlgorithm(pCipher)))
}

// IEnumDot11AdHocInterfaces is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IEnumDot11AdHocInterfaces with error-returning methods.
type IEnumDot11AdHocInterfaces struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IEnumDot11AdHocInterfaces
}

// WrapIEnumDot11AdHocInterfaces wraps a raw networkmanagementwifi.IEnumDot11AdHocInterfaces pointer.
func WrapIEnumDot11AdHocInterfaces(raw *networkmanagementwifi.IEnumDot11AdHocInterfaces) IEnumDot11AdHocInterfaces {
	return IEnumDot11AdHocInterfaces{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Next wraps the raw Next call.
func (self IEnumDot11AdHocInterfaces) Next(cElt uint32, rgElt **networkmanagementwifi.IDot11AdHocInterface, pcEltFetched *uint32) error {
	return win32.HRESULTError(int32(self.Raw.Next(cElt, rgElt, pcEltFetched)))
}

// Skip wraps the raw Skip call.
func (self IEnumDot11AdHocInterfaces) Skip(cElt uint32) error {
	return win32.HRESULTError(int32(self.Raw.Skip(cElt)))
}

// Reset wraps the raw Reset call.
func (self IEnumDot11AdHocInterfaces) Reset() error {
	return win32.HRESULTError(int32(self.Raw.Reset()))
}

// Clone wraps the raw Clone call.
func (self IEnumDot11AdHocInterfaces) Clone(ppEnum **networkmanagementwifi.IEnumDot11AdHocInterfaces) error {
	return win32.HRESULTError(int32(self.Raw.Clone(ppEnum)))
}

// IEnumDot11AdHocNetworks is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IEnumDot11AdHocNetworks with error-returning methods.
type IEnumDot11AdHocNetworks struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IEnumDot11AdHocNetworks
}

// WrapIEnumDot11AdHocNetworks wraps a raw networkmanagementwifi.IEnumDot11AdHocNetworks pointer.
func WrapIEnumDot11AdHocNetworks(raw *networkmanagementwifi.IEnumDot11AdHocNetworks) IEnumDot11AdHocNetworks {
	return IEnumDot11AdHocNetworks{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Next wraps the raw Next call.
func (self IEnumDot11AdHocNetworks) Next(cElt uint32, rgElt **networkmanagementwifi.IDot11AdHocNetwork, pcEltFetched *uint32) error {
	return win32.HRESULTError(int32(self.Raw.Next(cElt, rgElt, pcEltFetched)))
}

// Skip wraps the raw Skip call.
func (self IEnumDot11AdHocNetworks) Skip(cElt uint32) error {
	return win32.HRESULTError(int32(self.Raw.Skip(cElt)))
}

// Reset wraps the raw Reset call.
func (self IEnumDot11AdHocNetworks) Reset() error {
	return win32.HRESULTError(int32(self.Raw.Reset()))
}

// Clone wraps the raw Clone call.
func (self IEnumDot11AdHocNetworks) Clone(ppEnum **networkmanagementwifi.IEnumDot11AdHocNetworks) error {
	return win32.HRESULTError(int32(self.Raw.Clone(ppEnum)))
}

// IEnumDot11AdHocSecuritySettings is an idiomatic wrapper over the raw COM interface NetworkManagement.WiFi.IEnumDot11AdHocSecuritySettings with error-returning methods.
type IEnumDot11AdHocSecuritySettings struct {
	systemcomidiom.IUnknown
	Raw *networkmanagementwifi.IEnumDot11AdHocSecuritySettings
}

// WrapIEnumDot11AdHocSecuritySettings wraps a raw networkmanagementwifi.IEnumDot11AdHocSecuritySettings pointer.
func WrapIEnumDot11AdHocSecuritySettings(raw *networkmanagementwifi.IEnumDot11AdHocSecuritySettings) IEnumDot11AdHocSecuritySettings {
	return IEnumDot11AdHocSecuritySettings{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Next wraps the raw Next call.
func (self IEnumDot11AdHocSecuritySettings) Next(cElt uint32, rgElt **networkmanagementwifi.IDot11AdHocSecuritySettings, pcEltFetched *uint32) error {
	return win32.HRESULTError(int32(self.Raw.Next(cElt, rgElt, pcEltFetched)))
}

// Skip wraps the raw Skip call.
func (self IEnumDot11AdHocSecuritySettings) Skip(cElt uint32) error {
	return win32.HRESULTError(int32(self.Raw.Skip(cElt)))
}

// Reset wraps the raw Reset call.
func (self IEnumDot11AdHocSecuritySettings) Reset() error {
	return win32.HRESULTError(int32(self.Raw.Reset()))
}

// Clone wraps the raw Clone call.
func (self IEnumDot11AdHocSecuritySettings) Clone(ppEnum **networkmanagementwifi.IEnumDot11AdHocSecuritySettings) error {
	return win32.HRESULTError(int32(self.Raw.Clone(ppEnum)))
}
