// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package extensibleauthenticationprotocol

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	securitycryptography "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security/cryptography"
)

// EAPHOST_AUTH_INFO: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ns-eaphostpeertypes-eaphost_auth_info
type EAPHOST_AUTH_INFO struct {
	Status       EAPHOST_AUTH_STATUS
	DwErrorCode  uint32
	DwReasonCode uint32
}

type EAPHOST_IDENTITY_UI_PARAMS struct {
	EapMethodType          EAP_METHOD_TYPE
	DwFlags                uint32
	DwSizeofConnectionData uint32
	PConnectionData        *byte
	DwSizeofUserData       uint32
	PUserData              *byte
	DwSizeofUserDataOut    uint32
	PUserDataOut           *byte
	PwszIdentity           foundation.PWSTR
	DwError                uint32
	PEapError              *EAP_ERROR
}

type EAPHOST_INTERACTIVE_UI_PARAMS struct {
	DwSizeofContextData       uint32
	PContextData              *byte
	DwSizeofInteractiveUIData uint32
	PInteractiveUIData        *byte
	DwError                   uint32
	PEapError                 *EAP_ERROR
}

// EAP_ATTRIBUTE: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_attribute
type EAP_ATTRIBUTE struct {
	EaType   EAP_ATTRIBUTE_TYPE
	DwLength uint32
	PValue   *byte
}

// EAP_ATTRIBUTES: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_attributes
type EAP_ATTRIBUTES struct {
	DwNumberOfAttributes uint32
	PAttribs             *EAP_ATTRIBUTE
}

// EAP_AUTHENTICATOR_METHOD_ROUTINES: https://learn.microsoft.com/windows/win32/api/eapmethodauthenticatorapis/ns-eapmethodauthenticatorapis-eap_authenticator_method_routines
type EAP_AUTHENTICATOR_METHOD_ROUTINES struct {
	DwSizeInBytes                                 uint32
	PEapType                                      *EAP_METHOD_TYPE
	EapMethodAuthenticatorInitialize              uintptr
	EapMethodAuthenticatorBeginSession            uintptr
	EapMethodAuthenticatorUpdateInnerMethodParams uintptr
	EapMethodAuthenticatorReceivePacket           uintptr
	EapMethodAuthenticatorSendPacket              uintptr
	EapMethodAuthenticatorGetAttributes           uintptr
	EapMethodAuthenticatorSetAttributes           uintptr
	EapMethodAuthenticatorGetResult               uintptr
	EapMethodAuthenticatorEndSession              uintptr
	EapMethodAuthenticatorShutdown                uintptr
}

// EAP_CONFIG_INPUT_FIELD_ARRAY: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_config_input_field_array
type EAP_CONFIG_INPUT_FIELD_ARRAY struct {
	DwVersion        uint32
	DwNumberOfFields uint32
	PFields          *EAP_CONFIG_INPUT_FIELD_DATA
}

// EAP_CONFIG_INPUT_FIELD_DATA: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_config_input_field_data
type EAP_CONFIG_INPUT_FIELD_DATA struct {
	DwSize          uint32
	Type            EAP_CONFIG_INPUT_FIELD_TYPE
	DwFlagProps     uint32
	PwszLabel       foundation.PWSTR
	PwszData        foundation.PWSTR
	DwMinDataLength uint32
	DwMaxDataLength uint32
}

// EAP_CRED_EXPIRY_REQ: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_cred_expiry_req
type EAP_CRED_EXPIRY_REQ struct {
	CurCreds EAP_CONFIG_INPUT_FIELD_ARRAY
	NewCreds EAP_CONFIG_INPUT_FIELD_ARRAY
}

// EAP_ERROR: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_error
type EAP_ERROR struct {
	DwWinError       uint32
	Type             EAP_METHOD_TYPE
	DwReasonCode     uint32
	RootCauseGuid    win32.GUID
	RepairGuid       win32.GUID
	HelpLinkGuid     win32.GUID
	PRootCauseString foundation.PWSTR
	PRepairString    foundation.PWSTR
}

// EAP_INTERACTIVE_UI_DATA: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_interactive_ui_data
type EAP_INTERACTIVE_UI_DATA struct {
	DwVersion  uint32
	DwSize     uint32
	DwDataType EAP_INTERACTIVE_UI_DATA_TYPE
	CbUiData   uint32
	PbUiData   EAP_UI_DATA_FORMAT
}

// EAP_METHOD_AUTHENTICATOR_RESULT: https://learn.microsoft.com/windows/win32/api/eapauthenticatoractiondefine/ns-eapauthenticatoractiondefine-eap_method_authenticator_result
type EAP_METHOD_AUTHENTICATOR_RESULT struct {
	FIsSuccess      foundation.BOOL
	DwFailureReason uint32
	PAuthAttribs    *EAP_ATTRIBUTES
}

// EAP_METHOD_INFO: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_info
type EAP_METHOD_INFO struct {
	Eaptype          EAP_METHOD_TYPE
	PwszAuthorName   foundation.PWSTR
	PwszFriendlyName foundation.PWSTR
	EapProperties    uint32
	PInnerMethodInfo *EAP_METHOD_INFO
}

// EAP_METHOD_INFO_ARRAY: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_info_array
type EAP_METHOD_INFO_ARRAY struct {
	DwNumberOfMethods uint32
	PEapMethods       *EAP_METHOD_INFO
}

// EAP_METHOD_INFO_ARRAY_EX: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_info_array_ex
type EAP_METHOD_INFO_ARRAY_EX struct {
	DwNumberOfMethods uint32
	PEapMethods       *EAP_METHOD_INFO_EX
}

// EAP_METHOD_INFO_EX: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_info_ex
type EAP_METHOD_INFO_EX struct {
	Eaptype               EAP_METHOD_TYPE
	PwszAuthorName        foundation.PWSTR
	PwszFriendlyName      foundation.PWSTR
	EapProperties         uint32
	PInnerMethodInfoArray *EAP_METHOD_INFO_ARRAY_EX
}

// EAP_METHOD_PROPERTY: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property
type EAP_METHOD_PROPERTY struct {
	EapMethodPropertyType      EAP_METHOD_PROPERTY_TYPE
	EapMethodPropertyValueType EAP_METHOD_PROPERTY_VALUE_TYPE
	EapMethodPropertyValue     EAP_METHOD_PROPERTY_VALUE
}

// EAP_METHOD_PROPERTY_ARRAY: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property_array
type EAP_METHOD_PROPERTY_ARRAY struct {
	DwNumberOfProperties uint32
	PMethodProperty      *EAP_METHOD_PROPERTY
}

// EAP_METHOD_PROPERTY_VALUE: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property_value
// EAP_METHOD_PROPERTY_VALUE is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type EAP_METHOD_PROPERTY_VALUE struct {
	Data [2]uint64
}

// EAP_METHOD_PROPERTY_VALUE_BOOL: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property_value_bool
type EAP_METHOD_PROPERTY_VALUE_BOOL struct {
	Length uint32
	Value  foundation.BOOL
}

// EAP_METHOD_PROPERTY_VALUE_DWORD: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property_value_dword
type EAP_METHOD_PROPERTY_VALUE_DWORD struct {
	Length uint32
	Value  uint32
}

// EAP_METHOD_PROPERTY_VALUE_STRING: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_property_value_string
type EAP_METHOD_PROPERTY_VALUE_STRING struct {
	Length uint32
	Value  *byte
}

// EAP_METHOD_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_method_type
type EAP_METHOD_TYPE struct {
	EapType    EAP_TYPE
	DwAuthorId uint32
}

// EAP_PEER_METHOD_ROUTINES: https://learn.microsoft.com/windows/win32/api/eapmethodpeerapis/ns-eapmethodpeerapis-eap_peer_method_routines
type EAP_PEER_METHOD_ROUTINES struct {
	DwVersion                    uint32
	PEapType                     *EAP_TYPE
	EapPeerInitialize            uintptr
	EapPeerGetIdentity           uintptr
	EapPeerBeginSession          uintptr
	EapPeerSetCredentials        uintptr
	EapPeerProcessRequestPacket  uintptr
	EapPeerGetResponsePacket     uintptr
	EapPeerGetResult             uintptr
	EapPeerGetUIContext          uintptr
	EapPeerSetUIContext          uintptr
	EapPeerGetResponseAttributes uintptr
	EapPeerSetResponseAttributes uintptr
	EapPeerEndSession            uintptr
	EapPeerShutdown              uintptr
}

// EAP_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_type
type EAP_TYPE struct {
	Type         byte
	DwVendorId   uint32
	DwVendorType uint32
}

// EAP_UI_DATA_FORMAT: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eap_ui_data_format
// EAP_UI_DATA_FORMAT is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type EAP_UI_DATA_FORMAT struct {
	Data [1]uint64
}

// EapCertificateCredential: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eapcertificatecredential
type EapCertificateCredential struct {
	CertHash [20]byte
	Password foundation.PWSTR
}

// EapCredential: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eapcredential
type EapCredential struct {
	CredType EapCredentialType
	CredData EapCredentialTypeData
}

// EapCredentialTypeData is a C union; the raw tier exposes its correctly sized
// and aligned backing storage. Typed accessors arrive with the idiomatic tier.
type EapCredentialTypeData struct {
	Data [4]uint64
}

// EapHostPeerMethodResult: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ns-eaphostpeertypes-eaphostpeermethodresult
type EapHostPeerMethodResult struct {
	FIsSuccess             foundation.BOOL
	DwFailureReasonCode    uint32
	FSaveConnectionData    foundation.BOOL
	DwSizeofConnectionData uint32
	PConnectionData        *byte
	FSaveUserData          foundation.BOOL
	DwSizeofUserData       uint32
	PUserData              *byte
	PAttribArray           *EAP_ATTRIBUTES
	IsolationState         ISOLATION_STATE
	PEapMethodInfo         *EAP_METHOD_INFO
	PEapError              *EAP_ERROR
}

// EapPacket: https://learn.microsoft.com/windows/win32/api/eapmethodtypes/ns-eapmethodtypes-eappacket
type EapPacket struct {
	Code   byte
	Id     byte
	Length [2]byte
	Data   [1]byte
}

// EapPeerMethodOutput: https://learn.microsoft.com/windows/win32/api/eapauthenticatoractiondefine/ns-eapauthenticatoractiondefine-eappeermethodoutput
type EapPeerMethodOutput struct {
	Action              EapPeerMethodResponseAction
	FAllowNotifications foundation.BOOL
}

// EapPeerMethodResult: https://learn.microsoft.com/windows/win32/api/eapmethodpeerapis/ns-eapmethodpeerapis-eappeermethodresult
type EapPeerMethodResult struct {
	FIsSuccess             foundation.BOOL
	DwFailureReasonCode    uint32
	FSaveConnectionData    foundation.BOOL
	DwSizeofConnectionData uint32
	PConnectionData        *byte
	FSaveUserData          foundation.BOOL
	DwSizeofUserData       uint32
	PUserData              *byte
	PAttribArray           *EAP_ATTRIBUTES
	PEapError              *EAP_ERROR
	PNgcKerbTicket         *NgcTicketContext
	FSaveToCredMan         foundation.BOOL
}

// EapSimCredential: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eapsimcredential
type EapSimCredential struct {
	IccID foundation.PWSTR
}

// EapUsernamePasswordCredential: https://learn.microsoft.com/windows/win32/api/eaptypes/ns-eaptypes-eapusernamepasswordcredential
type EapUsernamePasswordCredential struct {
	Username foundation.PWSTR
	Password foundation.PWSTR
}

type LEGACY_IDENTITY_UI_PARAMS struct {
	EapType                uint32
	DwFlags                uint32
	DwSizeofConnectionData uint32
	PConnectionData        *byte
	DwSizeofUserData       uint32
	PUserData              *byte
	DwSizeofUserDataOut    uint32
	PUserDataOut           *byte
	PwszIdentity           foundation.PWSTR
	DwError                uint32
}

type LEGACY_INTERACTIVE_UI_PARAMS struct {
	EapType                   uint32
	DwSizeofContextData       uint32
	PContextData              *byte
	DwSizeofInteractiveUIData uint32
	PInteractiveUIData        *byte
	DwError                   uint32
}

type NgcTicketContext struct {
	WszTicket         [45]uint16
	HKey              securitycryptography.NCRYPT_KEY_HANDLE
	HImpersonateToken foundation.HANDLE
}

// PPP_EAP_INFO: https://learn.microsoft.com/windows/win32/api/raseapif/ns-raseapif-ppp_eap_info
type PPP_EAP_INFO struct {
	DwSizeInBytes     uint32
	DwEapTypeId       uint32
	RasEapInitialize  uintptr
	RasEapBegin       uintptr
	RasEapEnd         uintptr
	RasEapMakeMessage uintptr
}

// PPP_EAP_INPUT: https://learn.microsoft.com/windows/win32/api/raseapif/ns-raseapif-ppp_eap_input
type PPP_EAP_INPUT struct {
	DwSizeInBytes                  uint32
	FFlags                         uint32
	FAuthenticator                 foundation.BOOL
	PwszIdentity                   foundation.PWSTR
	PwszPassword                   foundation.PWSTR
	BInitialId                     byte
	PUserAttributes                *RAS_AUTH_ATTRIBUTE
	FAuthenticationComplete        foundation.BOOL
	DwAuthResultCode               uint32
	HTokenImpersonateUser          foundation.HANDLE
	FSuccessPacketReceived         foundation.BOOL
	FDataReceivedFromInteractiveUI foundation.BOOL
	PDataFromInteractiveUI         *byte
	DwSizeOfDataFromInteractiveUI  uint32
	PConnectionData                *byte
	DwSizeOfConnectionData         uint32
	PUserData                      *byte
	DwSizeOfUserData               uint32
	HReserved                      foundation.HANDLE
	GuidConnectionId               win32.GUID
	IsVpn                          foundation.BOOL
}

// PPP_EAP_OUTPUT: https://learn.microsoft.com/windows/win32/api/raseapif/ns-raseapif-ppp_eap_output
type PPP_EAP_OUTPUT struct {
	DwSizeInBytes          uint32
	Action                 PPP_EAP_ACTION
	DwAuthResultCode       uint32
	PUserAttributes        *RAS_AUTH_ATTRIBUTE
	FInvokeInteractiveUI   foundation.BOOL
	PUIContextData         *byte
	DwSizeOfUIContextData  uint32
	FSaveConnectionData    foundation.BOOL
	PConnectionData        *byte
	DwSizeOfConnectionData uint32
	FSaveUserData          foundation.BOOL
	PUserData              *byte
	DwSizeOfUserData       uint32
	PNgcKerbTicket         *NgcTicketContext
	FSaveToCredMan         foundation.BOOL
}

// PPP_EAP_PACKET: https://learn.microsoft.com/windows/win32/api/raseapif/ns-raseapif-ppp_eap_packet
type PPP_EAP_PACKET struct {
	Code   byte
	Id     byte
	Length [2]byte
	Data   [1]byte
}

// RAS_AUTH_ATTRIBUTE: https://learn.microsoft.com/windows/win32/api/raseapif/ns-raseapif-ras_auth_attribute
type RAS_AUTH_ATTRIBUTE struct {
	RaaType  RAS_AUTH_ATTRIBUTE_TYPE
	DwLength uint32
	Value    unsafe.Pointer
}
