// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package extensibleauthenticationprotocol

// EAPHOST_AUTH_STATUS: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ne-eaphostpeertypes-eaphost_auth_status
type EAPHOST_AUTH_STATUS int32

const (
	EapHostInvalidSession       EAPHOST_AUTH_STATUS = 0
	EapHostAuthNotStarted       EAPHOST_AUTH_STATUS = 1
	EapHostAuthIdentityExchange EAPHOST_AUTH_STATUS = 2
	EapHostAuthNegotiatingType  EAPHOST_AUTH_STATUS = 3
	EapHostAuthInProgress       EAPHOST_AUTH_STATUS = 4
	EapHostAuthSucceeded        EAPHOST_AUTH_STATUS = 5
	EapHostAuthFailed           EAPHOST_AUTH_STATUS = 6
)

// EAP_ATTRIBUTE_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eap_attribute_type
type EAP_ATTRIBUTE_TYPE int32

const (
	EatMinimum                EAP_ATTRIBUTE_TYPE = 0
	EatUserName               EAP_ATTRIBUTE_TYPE = 1
	EatUserPassword           EAP_ATTRIBUTE_TYPE = 2
	EatMD5CHAPPassword        EAP_ATTRIBUTE_TYPE = 3
	EatNASIPAddress           EAP_ATTRIBUTE_TYPE = 4
	EatNASPort                EAP_ATTRIBUTE_TYPE = 5
	EatServiceType            EAP_ATTRIBUTE_TYPE = 6
	EatFramedProtocol         EAP_ATTRIBUTE_TYPE = 7
	EatFramedIPAddress        EAP_ATTRIBUTE_TYPE = 8
	EatFramedIPNetmask        EAP_ATTRIBUTE_TYPE = 9
	EatFramedRouting          EAP_ATTRIBUTE_TYPE = 10
	EatFilterId               EAP_ATTRIBUTE_TYPE = 11
	EatFramedMTU              EAP_ATTRIBUTE_TYPE = 12
	EatFramedCompression      EAP_ATTRIBUTE_TYPE = 13
	EatLoginIPHost            EAP_ATTRIBUTE_TYPE = 14
	EatLoginService           EAP_ATTRIBUTE_TYPE = 15
	EatLoginTCPPort           EAP_ATTRIBUTE_TYPE = 16
	EatUnassigned17           EAP_ATTRIBUTE_TYPE = 17
	EatReplyMessage           EAP_ATTRIBUTE_TYPE = 18
	EatCallbackNumber         EAP_ATTRIBUTE_TYPE = 19
	EatCallbackId             EAP_ATTRIBUTE_TYPE = 20
	EatUnassigned21           EAP_ATTRIBUTE_TYPE = 21
	EatFramedRoute            EAP_ATTRIBUTE_TYPE = 22
	EatFramedIPXNetwork       EAP_ATTRIBUTE_TYPE = 23
	EatState                  EAP_ATTRIBUTE_TYPE = 24
	EatClass                  EAP_ATTRIBUTE_TYPE = 25
	EatVendorSpecific         EAP_ATTRIBUTE_TYPE = 26
	EatSessionTimeout         EAP_ATTRIBUTE_TYPE = 27
	EatIdleTimeout            EAP_ATTRIBUTE_TYPE = 28
	EatTerminationAction      EAP_ATTRIBUTE_TYPE = 29
	EatCalledStationId        EAP_ATTRIBUTE_TYPE = 30
	EatCallingStationId       EAP_ATTRIBUTE_TYPE = 31
	EatNASIdentifier          EAP_ATTRIBUTE_TYPE = 32
	EatProxyState             EAP_ATTRIBUTE_TYPE = 33
	EatLoginLATService        EAP_ATTRIBUTE_TYPE = 34
	EatLoginLATNode           EAP_ATTRIBUTE_TYPE = 35
	EatLoginLATGroup          EAP_ATTRIBUTE_TYPE = 36
	EatFramedAppleTalkLink    EAP_ATTRIBUTE_TYPE = 37
	EatFramedAppleTalkNetwork EAP_ATTRIBUTE_TYPE = 38
	EatFramedAppleTalkZone    EAP_ATTRIBUTE_TYPE = 39
	EatAcctStatusType         EAP_ATTRIBUTE_TYPE = 40
	EatAcctDelayTime          EAP_ATTRIBUTE_TYPE = 41
	EatAcctInputOctets        EAP_ATTRIBUTE_TYPE = 42
	EatAcctOutputOctets       EAP_ATTRIBUTE_TYPE = 43
	EatAcctSessionId          EAP_ATTRIBUTE_TYPE = 44
	EatAcctAuthentic          EAP_ATTRIBUTE_TYPE = 45
	EatAcctSessionTime        EAP_ATTRIBUTE_TYPE = 46
	EatAcctInputPackets       EAP_ATTRIBUTE_TYPE = 47
	EatAcctOutputPackets      EAP_ATTRIBUTE_TYPE = 48
	EatAcctTerminateCause     EAP_ATTRIBUTE_TYPE = 49
	EatAcctMultiSessionId     EAP_ATTRIBUTE_TYPE = 50
	EatAcctLinkCount          EAP_ATTRIBUTE_TYPE = 51
	EatAcctEventTimeStamp     EAP_ATTRIBUTE_TYPE = 55
	EatMD5CHAPChallenge       EAP_ATTRIBUTE_TYPE = 60
	EatNASPortType            EAP_ATTRIBUTE_TYPE = 61
	EatPortLimit              EAP_ATTRIBUTE_TYPE = 62
	EatLoginLATPort           EAP_ATTRIBUTE_TYPE = 63
	EatTunnelType             EAP_ATTRIBUTE_TYPE = 64
	EatTunnelMediumType       EAP_ATTRIBUTE_TYPE = 65
	EatTunnelClientEndpoint   EAP_ATTRIBUTE_TYPE = 66
	EatTunnelServerEndpoint   EAP_ATTRIBUTE_TYPE = 67
	EatARAPPassword           EAP_ATTRIBUTE_TYPE = 70
	EatARAPFeatures           EAP_ATTRIBUTE_TYPE = 71
	EatARAPZoneAccess         EAP_ATTRIBUTE_TYPE = 72
	EatARAPSecurity           EAP_ATTRIBUTE_TYPE = 73
	EatARAPSecurityData       EAP_ATTRIBUTE_TYPE = 74
	EatPasswordRetry          EAP_ATTRIBUTE_TYPE = 75
	EatPrompt                 EAP_ATTRIBUTE_TYPE = 76
	EatConnectInfo            EAP_ATTRIBUTE_TYPE = 77
	EatConfigurationToken     EAP_ATTRIBUTE_TYPE = 78
	EatEAPMessage             EAP_ATTRIBUTE_TYPE = 79
	EatSignature              EAP_ATTRIBUTE_TYPE = 80
	EatARAPChallengeResponse  EAP_ATTRIBUTE_TYPE = 84
	EatAcctInterimInterval    EAP_ATTRIBUTE_TYPE = 85
	EatNASIPv6Address         EAP_ATTRIBUTE_TYPE = 95
	EatFramedInterfaceId      EAP_ATTRIBUTE_TYPE = 96
	EatFramedIPv6Prefix       EAP_ATTRIBUTE_TYPE = 97
	EatLoginIPv6Host          EAP_ATTRIBUTE_TYPE = 98
	EatFramedIPv6Route        EAP_ATTRIBUTE_TYPE = 99
	EatFramedIPv6Pool         EAP_ATTRIBUTE_TYPE = 100
	EatARAPGuestLogon         EAP_ATTRIBUTE_TYPE = 8096
	EatCertificateOID         EAP_ATTRIBUTE_TYPE = 8097
	EatEAPConfiguration       EAP_ATTRIBUTE_TYPE = 8098
	EatPEAPEmbeddedEAPTypeId  EAP_ATTRIBUTE_TYPE = 8099
	EatPEAPFastRoamedSession  EAP_ATTRIBUTE_TYPE = 8100
	EatFastRoamedSession      EAP_ATTRIBUTE_TYPE = 8100
	EatEAPTLV                 EAP_ATTRIBUTE_TYPE = 8102
	EatCredentialsChanged     EAP_ATTRIBUTE_TYPE = 8103
	EatInnerEapMethodType     EAP_ATTRIBUTE_TYPE = 8104
	EatClearTextPassword      EAP_ATTRIBUTE_TYPE = 8107
	EatQuarantineSoH          EAP_ATTRIBUTE_TYPE = 8150
	EatCertificateThumbprint  EAP_ATTRIBUTE_TYPE = 8250
	EatPeerId                 EAP_ATTRIBUTE_TYPE = 9000
	EatServerId               EAP_ATTRIBUTE_TYPE = 9001
	EatMethodId               EAP_ATTRIBUTE_TYPE = 9002
	EatEMSK                   EAP_ATTRIBUTE_TYPE = 9003
	EatSessionId              EAP_ATTRIBUTE_TYPE = 9004
	EatReserved               EAP_ATTRIBUTE_TYPE = -1
)

// EAP_AUTHENTICATOR_SEND_TIMEOUT: https://learn.microsoft.com/windows/win32/api/eapauthenticatortypes/ne-eapauthenticatortypes-eap_authenticator_send_timeout
type EAP_AUTHENTICATOR_SEND_TIMEOUT int32

const (
	EAP_AUTHENTICATOR_SEND_TIMEOUT_NONE        EAP_AUTHENTICATOR_SEND_TIMEOUT = 0
	EAP_AUTHENTICATOR_SEND_TIMEOUT_BASIC       EAP_AUTHENTICATOR_SEND_TIMEOUT = 1
	EAP_AUTHENTICATOR_SEND_TIMEOUT_INTERACTIVE EAP_AUTHENTICATOR_SEND_TIMEOUT = 2
)

// EAP_CONFIG_INPUT_FIELD_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eap_config_input_field_type
type EAP_CONFIG_INPUT_FIELD_TYPE int32

const (
	EapConfigInputUsername        EAP_CONFIG_INPUT_FIELD_TYPE = 0
	EapConfigInputPassword        EAP_CONFIG_INPUT_FIELD_TYPE = 1
	EapConfigInputNetworkUsername EAP_CONFIG_INPUT_FIELD_TYPE = 2
	EapConfigInputNetworkPassword EAP_CONFIG_INPUT_FIELD_TYPE = 3
	EapConfigInputPin             EAP_CONFIG_INPUT_FIELD_TYPE = 4
	EapConfigInputPSK             EAP_CONFIG_INPUT_FIELD_TYPE = 5
	EapConfigInputEdit            EAP_CONFIG_INPUT_FIELD_TYPE = 6
	EapConfigSmartCardUsername    EAP_CONFIG_INPUT_FIELD_TYPE = 7
	EapConfigSmartCardError       EAP_CONFIG_INPUT_FIELD_TYPE = 8
)

// EAP_INTERACTIVE_UI_DATA_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eap_interactive_ui_data_type
type EAP_INTERACTIVE_UI_DATA_TYPE int32

const (
	EapCredReq        EAP_INTERACTIVE_UI_DATA_TYPE = 0
	EapCredResp       EAP_INTERACTIVE_UI_DATA_TYPE = 1
	EapCredExpiryReq  EAP_INTERACTIVE_UI_DATA_TYPE = 2
	EapCredExpiryResp EAP_INTERACTIVE_UI_DATA_TYPE = 3
	EapCredLogonReq   EAP_INTERACTIVE_UI_DATA_TYPE = 4
	EapCredLogonResp  EAP_INTERACTIVE_UI_DATA_TYPE = 5
)

// EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION: https://learn.microsoft.com/windows/win32/api/eapauthenticatoractiondefine/ne-eapauthenticatoractiondefine-eap_method_authenticator_response_action
type EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION int32

const (
	EAP_METHOD_AUTHENTICATOR_RESPONSE_DISCARD         EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 0
	EAP_METHOD_AUTHENTICATOR_RESPONSE_SEND            EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 1
	EAP_METHOD_AUTHENTICATOR_RESPONSE_RESULT          EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 2
	EAP_METHOD_AUTHENTICATOR_RESPONSE_RESPOND         EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 3
	EAP_METHOD_AUTHENTICATOR_RESPONSE_AUTHENTICATE    EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 4
	EAP_METHOD_AUTHENTICATOR_RESPONSE_HANDLE_IDENTITY EAP_METHOD_AUTHENTICATOR_RESPONSE_ACTION = 5
)

// EAP_METHOD_PROPERTY_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eap_method_property_type
type EAP_METHOD_PROPERTY_TYPE int32

const (
	EmptPropCipherSuiteNegotiation     EAP_METHOD_PROPERTY_TYPE = 0
	EmptPropMutualAuth                 EAP_METHOD_PROPERTY_TYPE = 1
	EmptPropIntegrity                  EAP_METHOD_PROPERTY_TYPE = 2
	EmptPropReplayProtection           EAP_METHOD_PROPERTY_TYPE = 3
	EmptPropConfidentiality            EAP_METHOD_PROPERTY_TYPE = 4
	EmptPropKeyDerivation              EAP_METHOD_PROPERTY_TYPE = 5
	EmptPropKeyStrength64              EAP_METHOD_PROPERTY_TYPE = 6
	EmptPropKeyStrength128             EAP_METHOD_PROPERTY_TYPE = 7
	EmptPropKeyStrength256             EAP_METHOD_PROPERTY_TYPE = 8
	EmptPropKeyStrength512             EAP_METHOD_PROPERTY_TYPE = 9
	EmptPropKeyStrength1024            EAP_METHOD_PROPERTY_TYPE = 10
	EmptPropDictionaryAttackResistance EAP_METHOD_PROPERTY_TYPE = 11
	EmptPropFastReconnect              EAP_METHOD_PROPERTY_TYPE = 12
	EmptPropCryptoBinding              EAP_METHOD_PROPERTY_TYPE = 13
	EmptPropSessionIndependence        EAP_METHOD_PROPERTY_TYPE = 14
	EmptPropFragmentation              EAP_METHOD_PROPERTY_TYPE = 15
	EmptPropChannelBinding             EAP_METHOD_PROPERTY_TYPE = 16
	EmptPropNap                        EAP_METHOD_PROPERTY_TYPE = 17
	EmptPropStandalone                 EAP_METHOD_PROPERTY_TYPE = 18
	EmptPropMppeEncryption             EAP_METHOD_PROPERTY_TYPE = 19
	EmptPropTunnelMethod               EAP_METHOD_PROPERTY_TYPE = 20
	EmptPropSupportsConfig             EAP_METHOD_PROPERTY_TYPE = 21
	EmptPropCertifiedMethod            EAP_METHOD_PROPERTY_TYPE = 22
	EmptPropHiddenMethod               EAP_METHOD_PROPERTY_TYPE = 23
	EmptPropMachineAuth                EAP_METHOD_PROPERTY_TYPE = 24
	EmptPropUserAuth                   EAP_METHOD_PROPERTY_TYPE = 25
	EmptPropIdentityPrivacy            EAP_METHOD_PROPERTY_TYPE = 26
	EmptPropMethodChaining             EAP_METHOD_PROPERTY_TYPE = 27
	EmptPropSharedStateEquivalence     EAP_METHOD_PROPERTY_TYPE = 28
	EmptLegacyMethodPropertyFlag       EAP_METHOD_PROPERTY_TYPE = 31
	EmptPropVendorSpecific             EAP_METHOD_PROPERTY_TYPE = 255
)

// EAP_METHOD_PROPERTY_VALUE_TYPE: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eap_method_property_value_type
type EAP_METHOD_PROPERTY_VALUE_TYPE int32

const (
	EmpvtBool   EAP_METHOD_PROPERTY_VALUE_TYPE = 0
	EmpvtDword  EAP_METHOD_PROPERTY_VALUE_TYPE = 1
	EmpvtString EAP_METHOD_PROPERTY_VALUE_TYPE = 2
)

// EapCode: https://learn.microsoft.com/windows/win32/api/eapmethodtypes/ne-eapmethodtypes-eapcode
type EapCode int32

const (
	EapCodeMinimum  EapCode = 1
	EapCodeRequest  EapCode = 1
	EapCodeResponse EapCode = 2
	EapCodeSuccess  EapCode = 3
	EapCodeFailure  EapCode = 4
	EapCodeMaximum  EapCode = 4
)

// EapCredentialType: https://learn.microsoft.com/windows/win32/api/eaptypes/ne-eaptypes-eapcredentialtype
type EapCredentialType int32

const (
	EAP_EMPTY_CREDENTIAL             EapCredentialType = 0
	EAP_USERNAME_PASSWORD_CREDENTIAL EapCredentialType = 1
	EAP_WINLOGON_CREDENTIAL          EapCredentialType = 2
	EAP_CERTIFICATE_CREDENTIAL       EapCredentialType = 3
	EAP_SIM_CREDENTIAL               EapCredentialType = 4
)

// EapHostPeerAuthParams: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ne-eaphostpeertypes-eaphostpeerauthparams
type EapHostPeerAuthParams int32

const (
	EapHostPeerAuthStatus           EapHostPeerAuthParams = 1
	EapHostPeerIdentity             EapHostPeerAuthParams = 2
	EapHostPeerIdentityExtendedInfo EapHostPeerAuthParams = 3
	EapHostNapInfo                  EapHostPeerAuthParams = 4
)

// EapHostPeerMethodResultReason: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ne-eaphostpeertypes-eaphostpeermethodresultreason
type EapHostPeerMethodResultReason int32

const (
	EapHostPeerMethodResultAltSuccessReceived EapHostPeerMethodResultReason = 1
	EapHostPeerMethodResultTimeout            EapHostPeerMethodResultReason = 2
	EapHostPeerMethodResultFromMethod         EapHostPeerMethodResultReason = 3
)

// EapHostPeerResponseAction: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ne-eaphostpeertypes-eaphostpeerresponseaction
type EapHostPeerResponseAction int32

const (
	EapHostPeerResponseDiscard             EapHostPeerResponseAction = 0
	EapHostPeerResponseSend                EapHostPeerResponseAction = 1
	EapHostPeerResponseResult              EapHostPeerResponseAction = 2
	EapHostPeerResponseInvokeUi            EapHostPeerResponseAction = 3
	EapHostPeerResponseRespond             EapHostPeerResponseAction = 4
	EapHostPeerResponseStartAuthentication EapHostPeerResponseAction = 5
	EapHostPeerResponseNone                EapHostPeerResponseAction = 6
)

// EapPeerMethodResponseAction: https://learn.microsoft.com/windows/win32/api/eapauthenticatoractiondefine/ne-eapauthenticatoractiondefine-eappeermethodresponseaction
type EapPeerMethodResponseAction int32

const (
	EapPeerMethodResponseActionDiscard  EapPeerMethodResponseAction = 0
	EapPeerMethodResponseActionSend     EapPeerMethodResponseAction = 1
	EapPeerMethodResponseActionResult   EapPeerMethodResponseAction = 2
	EapPeerMethodResponseActionInvokeUI EapPeerMethodResponseAction = 3
	EapPeerMethodResponseActionRespond  EapPeerMethodResponseAction = 4
	EapPeerMethodResponseActionNone     EapPeerMethodResponseAction = 5
)

// EapPeerMethodResultReason: https://learn.microsoft.com/windows/win32/api/eapauthenticatoractiondefine/ne-eapauthenticatoractiondefine-eappeermethodresultreason
type EapPeerMethodResultReason int32

const (
	EapPeerMethodResultUnknown EapPeerMethodResultReason = 1
	EapPeerMethodResultSuccess EapPeerMethodResultReason = 2
	EapPeerMethodResultFailure EapPeerMethodResultReason = 3
)

// ISOLATION_STATE: https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ne-eaphostpeertypes-isolation_state
type ISOLATION_STATE int32

const (
	ISOLATION_STATE_UNKNOWN           ISOLATION_STATE = 0
	ISOLATION_STATE_NOT_RESTRICTED    ISOLATION_STATE = 1
	ISOLATION_STATE_IN_PROBATION      ISOLATION_STATE = 2
	ISOLATION_STATE_RESTRICTED_ACCESS ISOLATION_STATE = 3
)

// PPP_EAP_ACTION: https://learn.microsoft.com/windows/win32/api/raseapif/ne-raseapif-ppp_eap_action
type PPP_EAP_ACTION int32

const (
	EAPACTION_NoAction                   PPP_EAP_ACTION = 0
	EAPACTION_Authenticate               PPP_EAP_ACTION = 1
	EAPACTION_Done                       PPP_EAP_ACTION = 2
	EAPACTION_SendAndDone                PPP_EAP_ACTION = 3
	EAPACTION_Send                       PPP_EAP_ACTION = 4
	EAPACTION_SendWithTimeout            PPP_EAP_ACTION = 5
	EAPACTION_SendWithTimeoutInteractive PPP_EAP_ACTION = 6
	EAPACTION_IndicateTLV                PPP_EAP_ACTION = 7
	EAPACTION_IndicateIdentity           PPP_EAP_ACTION = 8
)

// RAS_AUTH_ATTRIBUTE_TYPE: https://learn.microsoft.com/windows/win32/api/raseapif/ne-raseapif-ras_auth_attribute_type
type RAS_AUTH_ATTRIBUTE_TYPE int32

const (
	RaatMinimum                RAS_AUTH_ATTRIBUTE_TYPE = 0
	RaatUserName               RAS_AUTH_ATTRIBUTE_TYPE = 1
	RaatUserPassword           RAS_AUTH_ATTRIBUTE_TYPE = 2
	RaatMD5CHAPPassword        RAS_AUTH_ATTRIBUTE_TYPE = 3
	RaatNASIPAddress           RAS_AUTH_ATTRIBUTE_TYPE = 4
	RaatNASPort                RAS_AUTH_ATTRIBUTE_TYPE = 5
	RaatServiceType            RAS_AUTH_ATTRIBUTE_TYPE = 6
	RaatFramedProtocol         RAS_AUTH_ATTRIBUTE_TYPE = 7
	RaatFramedIPAddress        RAS_AUTH_ATTRIBUTE_TYPE = 8
	RaatFramedIPNetmask        RAS_AUTH_ATTRIBUTE_TYPE = 9
	RaatFramedRouting          RAS_AUTH_ATTRIBUTE_TYPE = 10
	RaatFilterId               RAS_AUTH_ATTRIBUTE_TYPE = 11
	RaatFramedMTU              RAS_AUTH_ATTRIBUTE_TYPE = 12
	RaatFramedCompression      RAS_AUTH_ATTRIBUTE_TYPE = 13
	RaatLoginIPHost            RAS_AUTH_ATTRIBUTE_TYPE = 14
	RaatLoginService           RAS_AUTH_ATTRIBUTE_TYPE = 15
	RaatLoginTCPPort           RAS_AUTH_ATTRIBUTE_TYPE = 16
	RaatUnassigned17           RAS_AUTH_ATTRIBUTE_TYPE = 17
	RaatReplyMessage           RAS_AUTH_ATTRIBUTE_TYPE = 18
	RaatCallbackNumber         RAS_AUTH_ATTRIBUTE_TYPE = 19
	RaatCallbackId             RAS_AUTH_ATTRIBUTE_TYPE = 20
	RaatUnassigned21           RAS_AUTH_ATTRIBUTE_TYPE = 21
	RaatFramedRoute            RAS_AUTH_ATTRIBUTE_TYPE = 22
	RaatFramedIPXNetwork       RAS_AUTH_ATTRIBUTE_TYPE = 23
	RaatState                  RAS_AUTH_ATTRIBUTE_TYPE = 24
	RaatClass                  RAS_AUTH_ATTRIBUTE_TYPE = 25
	RaatVendorSpecific         RAS_AUTH_ATTRIBUTE_TYPE = 26
	RaatSessionTimeout         RAS_AUTH_ATTRIBUTE_TYPE = 27
	RaatIdleTimeout            RAS_AUTH_ATTRIBUTE_TYPE = 28
	RaatTerminationAction      RAS_AUTH_ATTRIBUTE_TYPE = 29
	RaatCalledStationId        RAS_AUTH_ATTRIBUTE_TYPE = 30
	RaatCallingStationId       RAS_AUTH_ATTRIBUTE_TYPE = 31
	RaatNASIdentifier          RAS_AUTH_ATTRIBUTE_TYPE = 32
	RaatProxyState             RAS_AUTH_ATTRIBUTE_TYPE = 33
	RaatLoginLATService        RAS_AUTH_ATTRIBUTE_TYPE = 34
	RaatLoginLATNode           RAS_AUTH_ATTRIBUTE_TYPE = 35
	RaatLoginLATGroup          RAS_AUTH_ATTRIBUTE_TYPE = 36
	RaatFramedAppleTalkLink    RAS_AUTH_ATTRIBUTE_TYPE = 37
	RaatFramedAppleTalkNetwork RAS_AUTH_ATTRIBUTE_TYPE = 38
	RaatFramedAppleTalkZone    RAS_AUTH_ATTRIBUTE_TYPE = 39
	RaatAcctStatusType         RAS_AUTH_ATTRIBUTE_TYPE = 40
	RaatAcctDelayTime          RAS_AUTH_ATTRIBUTE_TYPE = 41
	RaatAcctInputOctets        RAS_AUTH_ATTRIBUTE_TYPE = 42
	RaatAcctOutputOctets       RAS_AUTH_ATTRIBUTE_TYPE = 43
	RaatAcctSessionId          RAS_AUTH_ATTRIBUTE_TYPE = 44
	RaatAcctAuthentic          RAS_AUTH_ATTRIBUTE_TYPE = 45
	RaatAcctSessionTime        RAS_AUTH_ATTRIBUTE_TYPE = 46
	RaatAcctInputPackets       RAS_AUTH_ATTRIBUTE_TYPE = 47
	RaatAcctOutputPackets      RAS_AUTH_ATTRIBUTE_TYPE = 48
	RaatAcctTerminateCause     RAS_AUTH_ATTRIBUTE_TYPE = 49
	RaatAcctMultiSessionId     RAS_AUTH_ATTRIBUTE_TYPE = 50
	RaatAcctLinkCount          RAS_AUTH_ATTRIBUTE_TYPE = 51
	RaatAcctEventTimeStamp     RAS_AUTH_ATTRIBUTE_TYPE = 55
	RaatMD5CHAPChallenge       RAS_AUTH_ATTRIBUTE_TYPE = 60
	RaatNASPortType            RAS_AUTH_ATTRIBUTE_TYPE = 61
	RaatPortLimit              RAS_AUTH_ATTRIBUTE_TYPE = 62
	RaatLoginLATPort           RAS_AUTH_ATTRIBUTE_TYPE = 63
	RaatTunnelType             RAS_AUTH_ATTRIBUTE_TYPE = 64
	RaatTunnelMediumType       RAS_AUTH_ATTRIBUTE_TYPE = 65
	RaatTunnelClientEndpoint   RAS_AUTH_ATTRIBUTE_TYPE = 66
	RaatTunnelServerEndpoint   RAS_AUTH_ATTRIBUTE_TYPE = 67
	RaatARAPPassword           RAS_AUTH_ATTRIBUTE_TYPE = 70
	RaatARAPFeatures           RAS_AUTH_ATTRIBUTE_TYPE = 71
	RaatARAPZoneAccess         RAS_AUTH_ATTRIBUTE_TYPE = 72
	RaatARAPSecurity           RAS_AUTH_ATTRIBUTE_TYPE = 73
	RaatARAPSecurityData       RAS_AUTH_ATTRIBUTE_TYPE = 74
	RaatPasswordRetry          RAS_AUTH_ATTRIBUTE_TYPE = 75
	RaatPrompt                 RAS_AUTH_ATTRIBUTE_TYPE = 76
	RaatConnectInfo            RAS_AUTH_ATTRIBUTE_TYPE = 77
	RaatConfigurationToken     RAS_AUTH_ATTRIBUTE_TYPE = 78
	RaatEAPMessage             RAS_AUTH_ATTRIBUTE_TYPE = 79
	RaatSignature              RAS_AUTH_ATTRIBUTE_TYPE = 80
	RaatARAPChallengeResponse  RAS_AUTH_ATTRIBUTE_TYPE = 84
	RaatAcctInterimInterval    RAS_AUTH_ATTRIBUTE_TYPE = 85
	RaatNASIPv6Address         RAS_AUTH_ATTRIBUTE_TYPE = 95
	RaatFramedInterfaceId      RAS_AUTH_ATTRIBUTE_TYPE = 96
	RaatFramedIPv6Prefix       RAS_AUTH_ATTRIBUTE_TYPE = 97
	RaatLoginIPv6Host          RAS_AUTH_ATTRIBUTE_TYPE = 98
	RaatFramedIPv6Route        RAS_AUTH_ATTRIBUTE_TYPE = 99
	RaatFramedIPv6Pool         RAS_AUTH_ATTRIBUTE_TYPE = 100
	RaatARAPGuestLogon         RAS_AUTH_ATTRIBUTE_TYPE = 8096
	RaatCertificateOID         RAS_AUTH_ATTRIBUTE_TYPE = 8097
	RaatEAPConfiguration       RAS_AUTH_ATTRIBUTE_TYPE = 8098
	RaatPEAPEmbeddedEAPTypeId  RAS_AUTH_ATTRIBUTE_TYPE = 8099
	RaatInnerEAPTypeId         RAS_AUTH_ATTRIBUTE_TYPE = 8099
	RaatPEAPFastRoamedSession  RAS_AUTH_ATTRIBUTE_TYPE = 8100
	RaatFastRoamedSession      RAS_AUTH_ATTRIBUTE_TYPE = 8100
	RaatEAPTLV                 RAS_AUTH_ATTRIBUTE_TYPE = 8102
	RaatCredentialsChanged     RAS_AUTH_ATTRIBUTE_TYPE = 8103
	RaatCertificateThumbprint  RAS_AUTH_ATTRIBUTE_TYPE = 8250
	RaatPeerId                 RAS_AUTH_ATTRIBUTE_TYPE = 9000
	RaatServerId               RAS_AUTH_ATTRIBUTE_TYPE = 9001
	RaatMethodId               RAS_AUTH_ATTRIBUTE_TYPE = 9002
	RaatEMSK                   RAS_AUTH_ATTRIBUTE_TYPE = 9003
	RaatSessionId              RAS_AUTH_ATTRIBUTE_TYPE = 9004
	RaatReserved               RAS_AUTH_ATTRIBUTE_TYPE = -1
)
