// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package systeminformation

import (
	systemsysteminformation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/systeminformation"
)

type COMPUTER_NAME_FORMAT = systemsysteminformation.COMPUTER_NAME_FORMAT
type CPU_SET_INFORMATION_TYPE = systemsysteminformation.CPU_SET_INFORMATION_TYPE
type DEP_SYSTEM_POLICY_TYPE = systemsysteminformation.DEP_SYSTEM_POLICY_TYPE
type DEVELOPER_DRIVE_ENABLEMENT_STATE = systemsysteminformation.DEVELOPER_DRIVE_ENABLEMENT_STATE
type DEVICEFAMILYDEVICEFORM = systemsysteminformation.DEVICEFAMILYDEVICEFORM
type DEVICEFAMILYINFOENUM = systemsysteminformation.DEVICEFAMILYINFOENUM
type FIRMWARE_TABLE_PROVIDER = systemsysteminformation.FIRMWARE_TABLE_PROVIDER
type FIRMWARE_TYPE = systemsysteminformation.FIRMWARE_TYPE
type IMAGE_FILE_MACHINE = systemsysteminformation.IMAGE_FILE_MACHINE
type LOGICAL_PROCESSOR_RELATIONSHIP = systemsysteminformation.LOGICAL_PROCESSOR_RELATIONSHIP
type OS_DEPLOYEMENT_STATE_VALUES = systemsysteminformation.OS_DEPLOYEMENT_STATE_VALUES
type OS_PRODUCT_TYPE = systemsysteminformation.OS_PRODUCT_TYPE
type PROCESSOR_ARCHITECTURE = systemsysteminformation.PROCESSOR_ARCHITECTURE
type PROCESSOR_CACHE_TYPE = systemsysteminformation.PROCESSOR_CACHE_TYPE
type RTL_SYSTEM_GLOBAL_DATA_ID = systemsysteminformation.RTL_SYSTEM_GLOBAL_DATA_ID
type USER_CET_ENVIRONMENT = systemsysteminformation.USER_CET_ENVIRONMENT
type VER_FLAGS = systemsysteminformation.VER_FLAGS
