// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package ink

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	systemcom "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/com"
	uiinputink "github.com/deploymenttheory/go-bindings-win32/bindings/win32/ui/input/ink"
	systemcomidiom "github.com/deploymenttheory/go-bindings-win32/opinionated/idiomatic/win32/system/com"
)

// IInkCommitRequestHandler is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkCommitRequestHandler with error-returning methods.
type IInkCommitRequestHandler struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkCommitRequestHandler
}

// WrapIInkCommitRequestHandler wraps a raw uiinputink.IInkCommitRequestHandler pointer.
func WrapIInkCommitRequestHandler(raw *uiinputink.IInkCommitRequestHandler) IInkCommitRequestHandler {
	return IInkCommitRequestHandler{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// OnCommitRequested wraps the raw OnCommitRequested call.
func (self IInkCommitRequestHandler) OnCommitRequested() error {
	return win32.HRESULTError(int32(self.Raw.OnCommitRequested()))
}

// IInkD2DRenderer is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkD2DRenderer with error-returning methods.
type IInkD2DRenderer struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkD2DRenderer
}

// WrapIInkD2DRenderer wraps a raw uiinputink.IInkD2DRenderer pointer.
func WrapIInkD2DRenderer(raw *uiinputink.IInkD2DRenderer) IInkD2DRenderer {
	return IInkD2DRenderer{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Draw wraps the raw Draw call.
func (self IInkD2DRenderer) Draw(pD2D1DeviceContext *systemcom.IUnknown, pInkStrokeIterable *systemcom.IUnknown, fHighContrast bool) error {
	_fHighContrast := foundation.BOOL(win32.Bool32(fHighContrast))
	return win32.HRESULTError(int32(self.Raw.Draw(pD2D1DeviceContext, pInkStrokeIterable, _fHighContrast)))
}

// IInkD2DRenderer2 is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkD2DRenderer2 with error-returning methods.
type IInkD2DRenderer2 struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkD2DRenderer2
}

// WrapIInkD2DRenderer2 wraps a raw uiinputink.IInkD2DRenderer2 pointer.
func WrapIInkD2DRenderer2(raw *uiinputink.IInkD2DRenderer2) IInkD2DRenderer2 {
	return IInkD2DRenderer2{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Draw wraps the raw Draw call.
func (self IInkD2DRenderer2) Draw(pD2D1DeviceContext *systemcom.IUnknown, pInkStrokeIterable *systemcom.IUnknown, highContrastAdjustment uiinputink.INK_HIGH_CONTRAST_ADJUSTMENT) error {
	return win32.HRESULTError(int32(self.Raw.Draw(pD2D1DeviceContext, pInkStrokeIterable, highContrastAdjustment)))
}

// IInkDesktopHost is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkDesktopHost with error-returning methods.
type IInkDesktopHost struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkDesktopHost
}

// WrapIInkDesktopHost wraps a raw uiinputink.IInkDesktopHost pointer.
func WrapIInkDesktopHost(raw *uiinputink.IInkDesktopHost) IInkDesktopHost {
	return IInkDesktopHost{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// QueueWorkItem wraps the raw QueueWorkItem call.
func (self IInkDesktopHost) QueueWorkItem(workItem *uiinputink.IInkHostWorkItem) error {
	return win32.HRESULTError(int32(self.Raw.QueueWorkItem(workItem)))
}

// CreateInkPresenter wraps the raw CreateInkPresenter call.
func (self IInkDesktopHost) CreateInkPresenter(riid *win32.GUID, ppv *unsafe.Pointer) error {
	return win32.HRESULTError(int32(self.Raw.CreateInkPresenter(riid, ppv)))
}

// IInkHostWorkItem is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkHostWorkItem with error-returning methods.
type IInkHostWorkItem struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkHostWorkItem
}

// WrapIInkHostWorkItem wraps a raw uiinputink.IInkHostWorkItem pointer.
func WrapIInkHostWorkItem(raw *uiinputink.IInkHostWorkItem) IInkHostWorkItem {
	return IInkHostWorkItem{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// Invoke wraps the raw Invoke call.
func (self IInkHostWorkItem) Invoke() error {
	return win32.HRESULTError(int32(self.Raw.Invoke()))
}

// IInkPresenterDesktop is an idiomatic wrapper over the raw COM interface UI.Input.Ink.IInkPresenterDesktop with error-returning methods.
type IInkPresenterDesktop struct {
	systemcomidiom.IUnknown
	Raw *uiinputink.IInkPresenterDesktop
}

// WrapIInkPresenterDesktop wraps a raw uiinputink.IInkPresenterDesktop pointer.
func WrapIInkPresenterDesktop(raw *uiinputink.IInkPresenterDesktop) IInkPresenterDesktop {
	return IInkPresenterDesktop{Raw: raw, IUnknown: systemcomidiom.WrapIUnknown(&raw.IUnknown)}
}

// SetRootVisual wraps the raw SetRootVisual call.
func (self IInkPresenterDesktop) SetRootVisual(rootVisual *systemcom.IUnknown, device *systemcom.IUnknown) error {
	return win32.HRESULTError(int32(self.Raw.SetRootVisual(rootVisual, device)))
}

// SetCommitRequestHandler wraps the raw SetCommitRequestHandler call.
func (self IInkPresenterDesktop) SetCommitRequestHandler(handler *uiinputink.IInkCommitRequestHandler) error {
	return win32.HRESULTError(int32(self.Raw.SetCommitRequestHandler(handler)))
}

// GetSize wraps the raw GetSize call.
func (self IInkPresenterDesktop) GetSize(width *float32, height *float32) error {
	return win32.HRESULTError(int32(self.Raw.GetSize(width, height)))
}

// OnHighContrastChanged wraps the raw OnHighContrastChanged call.
func (self IInkPresenterDesktop) OnHighContrastChanged() error {
	return win32.HRESULTError(int32(self.Raw.OnHighContrastChanged()))
}
