// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package input

import (
	uiinput "github.com/deploymenttheory/go-bindings-win32/bindings/win32/ui/input"
)

type HRAWINPUT = uiinput.HRAWINPUT
