// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package abi

import (
	"testing"
	"unsafe"

	securitynetworkaccessprotection "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security/networkaccessprotection"
)

// abiSecurity_NetworkAccessProtection holds the expected C layout of every struct emitted for
// Windows.Win32.Security.NetworkAccessProtection.
var abiSecurity_NetworkAccessProtection = []abiCase{
	{"securitynetworkaccessprotection.CorrelationId size", unsafe.Sizeof(securitynetworkaccessprotection.CorrelationId{}), 24},
	{"securitynetworkaccessprotection.CorrelationId.ConnId", unsafe.Offsetof(securitynetworkaccessprotection.CorrelationId{}.ConnId), 0},
	{"securitynetworkaccessprotection.CorrelationId.TimeStamp", unsafe.Offsetof(securitynetworkaccessprotection.CorrelationId{}.TimeStamp), 16},
	{"securitynetworkaccessprotection.CountedString size", unsafe.Sizeof(securitynetworkaccessprotection.CountedString{}), 16},
	{"securitynetworkaccessprotection.CountedString.Length", unsafe.Offsetof(securitynetworkaccessprotection.CountedString{}.Length), 0},
	{"securitynetworkaccessprotection.CountedString.String", unsafe.Offsetof(securitynetworkaccessprotection.CountedString{}.String), 8},
	{"securitynetworkaccessprotection.FailureCategoryMapping size", unsafe.Sizeof(securitynetworkaccessprotection.FailureCategoryMapping{}), 20},
	{"securitynetworkaccessprotection.FailureCategoryMapping.MappingCompliance", unsafe.Offsetof(securitynetworkaccessprotection.FailureCategoryMapping{}.MappingCompliance), 0},
	{"securitynetworkaccessprotection.FixupInfo size", unsafe.Sizeof(securitynetworkaccessprotection.FixupInfo{}), 32},
	{"securitynetworkaccessprotection.FixupInfo.State", unsafe.Offsetof(securitynetworkaccessprotection.FixupInfo{}.State), 0},
	{"securitynetworkaccessprotection.FixupInfo.Percentage", unsafe.Offsetof(securitynetworkaccessprotection.FixupInfo{}.Percentage), 4},
	{"securitynetworkaccessprotection.FixupInfo.ResultCodes", unsafe.Offsetof(securitynetworkaccessprotection.FixupInfo{}.ResultCodes), 8},
	{"securitynetworkaccessprotection.FixupInfo.FixupMsgId", unsafe.Offsetof(securitynetworkaccessprotection.FixupInfo{}.FixupMsgId), 24},
	{"securitynetworkaccessprotection.Ipv4Address size", unsafe.Sizeof(securitynetworkaccessprotection.Ipv4Address{}), 4},
	{"securitynetworkaccessprotection.Ipv4Address.Addr", unsafe.Offsetof(securitynetworkaccessprotection.Ipv4Address{}.Addr), 0},
	{"securitynetworkaccessprotection.Ipv6Address size", unsafe.Sizeof(securitynetworkaccessprotection.Ipv6Address{}), 16},
	{"securitynetworkaccessprotection.Ipv6Address.Addr", unsafe.Offsetof(securitynetworkaccessprotection.Ipv6Address{}.Addr), 0},
	{"securitynetworkaccessprotection.IsolationInfo size", unsafe.Sizeof(securitynetworkaccessprotection.IsolationInfo{}), 32},
	{"securitynetworkaccessprotection.IsolationInfo.IsolationState", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfo{}.IsolationState), 0},
	{"securitynetworkaccessprotection.IsolationInfo.ProbEndTime", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfo{}.ProbEndTime), 4},
	{"securitynetworkaccessprotection.IsolationInfo.FailureUrl", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfo{}.FailureUrl), 16},
	{"securitynetworkaccessprotection.IsolationInfoEx size", unsafe.Sizeof(securitynetworkaccessprotection.IsolationInfoEx{}), 32},
	{"securitynetworkaccessprotection.IsolationInfoEx.IsolationState", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfoEx{}.IsolationState), 0},
	{"securitynetworkaccessprotection.IsolationInfoEx.ExtendedIsolationState", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfoEx{}.ExtendedIsolationState), 4},
	{"securitynetworkaccessprotection.IsolationInfoEx.ProbEndTime", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfoEx{}.ProbEndTime), 8},
	{"securitynetworkaccessprotection.IsolationInfoEx.FailureUrl", unsafe.Offsetof(securitynetworkaccessprotection.IsolationInfoEx{}.FailureUrl), 16},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo size", unsafe.Sizeof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}), 120},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.Id", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.Id), 0},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.FriendlyName", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.FriendlyName), 8},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.Description", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.Description), 24},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.Version", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.Version), 40},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.VendorName", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.VendorName), 56},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.InfoClsid", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.InfoClsid), 72},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.ConfigClsid", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.ConfigClsid), 88},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.RegistrationDate", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.RegistrationDate), 104},
	{"securitynetworkaccessprotection.NapComponentRegistrationInfo.ComponentType", unsafe.Offsetof(securitynetworkaccessprotection.NapComponentRegistrationInfo{}.ComponentType), 112},
	{"securitynetworkaccessprotection.NetworkSoH size", unsafe.Sizeof(securitynetworkaccessprotection.NetworkSoH{}), 16},
	{"securitynetworkaccessprotection.NetworkSoH.Size", unsafe.Offsetof(securitynetworkaccessprotection.NetworkSoH{}.Size), 0},
	{"securitynetworkaccessprotection.NetworkSoH.Data", unsafe.Offsetof(securitynetworkaccessprotection.NetworkSoH{}.Data), 8},
	{"securitynetworkaccessprotection.PrivateData size", unsafe.Sizeof(securitynetworkaccessprotection.PrivateData{}), 16},
	{"securitynetworkaccessprotection.PrivateData.Size", unsafe.Offsetof(securitynetworkaccessprotection.PrivateData{}.Size), 0},
	{"securitynetworkaccessprotection.PrivateData.Data", unsafe.Offsetof(securitynetworkaccessprotection.PrivateData{}.Data), 8},
	{"securitynetworkaccessprotection.ResultCodes size", unsafe.Sizeof(securitynetworkaccessprotection.ResultCodes{}), 16},
	{"securitynetworkaccessprotection.ResultCodes.Count", unsafe.Offsetof(securitynetworkaccessprotection.ResultCodes{}.Count), 0},
	{"securitynetworkaccessprotection.ResultCodes.Results", unsafe.Offsetof(securitynetworkaccessprotection.ResultCodes{}.Results), 8},
	{"securitynetworkaccessprotection.SoH size", unsafe.Sizeof(securitynetworkaccessprotection.SoH{}), 16},
	{"securitynetworkaccessprotection.SoH.Count", unsafe.Offsetof(securitynetworkaccessprotection.SoH{}.Count), 0},
	{"securitynetworkaccessprotection.SoH.Attributes", unsafe.Offsetof(securitynetworkaccessprotection.SoH{}.Attributes), 8},
	{"securitynetworkaccessprotection.SoHAttribute size", unsafe.Sizeof(securitynetworkaccessprotection.SoHAttribute{}), 16},
	{"securitynetworkaccessprotection.SoHAttribute.Type", unsafe.Offsetof(securitynetworkaccessprotection.SoHAttribute{}.Type), 0},
	{"securitynetworkaccessprotection.SoHAttribute.Size", unsafe.Offsetof(securitynetworkaccessprotection.SoHAttribute{}.Size), 2},
	{"securitynetworkaccessprotection.SoHAttribute.Value", unsafe.Offsetof(securitynetworkaccessprotection.SoHAttribute{}.Value), 8},
	{"securitynetworkaccessprotection.SystemHealthAgentState size", unsafe.Sizeof(securitynetworkaccessprotection.SystemHealthAgentState{}), 64},
	{"securitynetworkaccessprotection.SystemHealthAgentState.Id", unsafe.Offsetof(securitynetworkaccessprotection.SystemHealthAgentState{}.Id), 0},
	{"securitynetworkaccessprotection.SystemHealthAgentState.ShaResultCodes", unsafe.Offsetof(securitynetworkaccessprotection.SystemHealthAgentState{}.ShaResultCodes), 8},
	{"securitynetworkaccessprotection.SystemHealthAgentState.FailureCategory", unsafe.Offsetof(securitynetworkaccessprotection.SystemHealthAgentState{}.FailureCategory), 24},
	{"securitynetworkaccessprotection.SystemHealthAgentState.FixupInfo", unsafe.Offsetof(securitynetworkaccessprotection.SystemHealthAgentState{}.FixupInfo), 32},
}

func TestABI_Security_NetworkAccessProtection(t *testing.T) { checkABI(t, abiSecurity_NetworkAccessProtection) }
