// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package addressbook provides idiomatic Go wrappers over the raw Windows.Win32.System.AddressBook bindings.
package addressbook
