// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package devicemanager

import (
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	systemcomstructuredstorage "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/com/structuredstorage"
)

type MACINFO struct {
	FUsed      foundation.BOOL
	AbMacState [36]byte
}

type MediaDevMgr struct {
}

type MediaDevMgrClassFactory struct {
}

// OPAQUECOMMAND: https://learn.microsoft.com/windows/win32/WMDM/opaquecommand
type OPAQUECOMMAND struct {
	GuidCommand win32.GUID
	DwDataLen   uint32
	PData       *byte
	AbMAC       [20]byte
}

// WMDMDATETIME: https://learn.microsoft.com/windows/win32/WMDM/wmdmdatetime
type WMDMDATETIME struct {
	WYear   uint16
	WMonth  uint16
	WDay    uint16
	WHour   uint16
	WMinute uint16
	WSecond uint16
}

// WMDMDetermineMaxPropStringLen is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type WMDMDetermineMaxPropStringLen struct {
	Data [36]uint16
}

type WMDMDevice struct {
}

type WMDMDeviceEnum struct {
}

// WMDMID: https://learn.microsoft.com/windows/win32/WMDM/wmdmid
type WMDMID struct {
	CbSize             uint32
	DwVendorID         uint32
	PID                [128]byte
	SerialNumberLength uint32
}

type WMDMLogger struct {
}

// WMDMMetadataView: https://learn.microsoft.com/windows/win32/WMDM/wmdmmetadataview
type WMDMMetadataView struct {
	PwszViewName foundation.PWSTR
	NDepth       uint32
	PpwszTags    **uint16
}

// WMDMRIGHTS: https://learn.microsoft.com/windows/win32/WMDM/wmdmrights
type WMDMRIGHTS struct {
	CbSize          uint32
	DwContentType   uint32
	FuFlags         uint32
	FuRights        uint32
	DwAppSec        uint32
	DwPlaybackCount uint32
	ExpirationDate  WMDMDATETIME
}

type WMDMStorage struct {
}

type WMDMStorageEnum struct {
}

type WMDMStorageGlobal struct {
}

// WMDM_FORMAT_CAPABILITY: https://learn.microsoft.com/windows/win32/WMDM/wmdm-format-capability
type WMDM_FORMAT_CAPABILITY struct {
	NPropConfig uint32
	PConfigs    *WMDM_PROP_CONFIG
}

// WMDM_PROP_CONFIG: https://learn.microsoft.com/windows/win32/WMDM/wmdm-prop-config
type WMDM_PROP_CONFIG struct {
	NPreference uint32
	NPropDesc   uint32
	PPropDesc   *WMDM_PROP_DESC
}

// WMDM_PROP_DESC_ValidValues_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type WMDM_PROP_DESC_ValidValues_e__Union struct {
	Data [9]uint64
}

// WMDM_PROP_DESC: https://learn.microsoft.com/windows/win32/WMDM/wmdm-prop-desc
type WMDM_PROP_DESC struct {
	PwszPropName    foundation.PWSTR
	ValidValuesForm WMDM_ENUM_PROP_VALID_VALUES_FORM
	ValidValues     WMDM_PROP_DESC_ValidValues_e__Union
}

// WMDM_PROP_VALUES_ENUM: https://learn.microsoft.com/windows/win32/WMDM/wmdm-prop-values-enum
type WMDM_PROP_VALUES_ENUM struct {
	CEnumValues uint32
	PValues     *systemcomstructuredstorage.PROPVARIANT
}

// WMDM_PROP_VALUES_RANGE: https://learn.microsoft.com/windows/win32/WMDM/wmdm-prop-values-range
type WMDM_PROP_VALUES_RANGE struct {
	RangeMin  systemcomstructuredstorage.PROPVARIANT
	RangeMax  systemcomstructuredstorage.PROPVARIANT
	RangeStep systemcomstructuredstorage.PROPVARIANT
}

// WMFILECAPABILITIES: https://learn.microsoft.com/windows/win32/WMDM/wmfilecapabilities
type WMFILECAPABILITIES struct {
	PwszMimeType foundation.PWSTR
	DwReserved   uint32
}
