// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package speech

// SPNOTIFYCALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(foundation.WPARAM, foundation.LPARAM).
type SPNOTIFYCALLBACK uintptr
