// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package dxcore

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
)

var (
	modDXCORE = win32.NewDLL("DXCORE.dll")
)

var (
	procDXCoreCreateAdapterFactory = modDXCORE.NewProc("DXCoreCreateAdapterFactory")
)

// DXCoreCreateAdapterFactory calls DXCORE!DXCoreCreateAdapterFactory.
// https://learn.microsoft.com/windows/win32/dxcore/dxcore/nf-dxcore-dxcorecreateadapterfactory
func DXCoreCreateAdapterFactory(riid *win32.GUID, ppvFactory **win32.IUnknown) error {
	r1, _, _ := syscall.SyscallN(procDXCoreCreateAdapterFactory.Addr(), uintptr(unsafe.Pointer(riid)), uintptr(unsafe.Pointer(ppvFactory)))
	return win32.ErrIfFailed(int32(r1))
}
