// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package applicationverifier

import (
	systemapplicationverifier "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/applicationverifier"
)

type AVRF_BACKTRACE_INFORMATION = systemapplicationverifier.AVRF_BACKTRACE_INFORMATION
type AVRF_HANDLE_OPERATION = systemapplicationverifier.AVRF_HANDLE_OPERATION
type AVRF_HEAP_ALLOCATION = systemapplicationverifier.AVRF_HEAP_ALLOCATION
