// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package dns

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	networkmanagementdns "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networkmanagement/dns"
)

// DnsAcquireContextHandle_ wraps the raw DnsAcquireContextHandle_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsacquirecontexthandle_w
func DnsAcquireContextHandle_(CredentialFlags uint32, Credentials unsafe.Pointer, pContext *foundation.HANDLE) int32 {
	return networkmanagementdns.DnsAcquireContextHandle_W(CredentialFlags, Credentials, pContext)
}

// DnsConnectionDeleteProxyInfo wraps the raw DnsConnectionDeleteProxyInfo call with idiomatic Go types.
func DnsConnectionDeleteProxyInfo(pwszConnectionName string, Type networkmanagementdns.DNS_CONNECTION_PROXY_TYPE) uint32 {
	_pwszConnectionName := win32.UTF16Ptr(pwszConnectionName)
	return networkmanagementdns.DnsConnectionDeleteProxyInfo(foundation.PWSTR(_pwszConnectionName), Type)
}

// DnsConnectionGetProxyInfo wraps the raw DnsConnectionGetProxyInfo call with idiomatic Go types.
func DnsConnectionGetProxyInfo(pwszConnectionName string, Type networkmanagementdns.DNS_CONNECTION_PROXY_TYPE, pProxyInfo *networkmanagementdns.DNS_CONNECTION_PROXY_INFO) uint32 {
	_pwszConnectionName := win32.UTF16Ptr(pwszConnectionName)
	return networkmanagementdns.DnsConnectionGetProxyInfo(foundation.PWSTR(_pwszConnectionName), Type, pProxyInfo)
}

// DnsConnectionGetProxyInfoForHostUrl wraps the raw DnsConnectionGetProxyInfoForHostUrl call with idiomatic Go types.
func DnsConnectionGetProxyInfoForHostUrl(pwszHostUrl string, pSelectionContext []byte, dwExplicitInterfaceIndex uint32, pProxyInfoEx *networkmanagementdns.DNS_CONNECTION_PROXY_INFO_EX) uint32 {
	_pwszHostUrl := win32.UTF16Ptr(pwszHostUrl)
	var _pSelectionContext *byte
	if len(pSelectionContext) > 0 {
		_pSelectionContext = &pSelectionContext[0]
	}
	return networkmanagementdns.DnsConnectionGetProxyInfoForHostUrl(foundation.PWSTR(_pwszHostUrl), _pSelectionContext, uint32(len(pSelectionContext)), dwExplicitInterfaceIndex, pProxyInfoEx)
}

// DnsConnectionGetProxyInfoForHostUrlEx wraps the raw DnsConnectionGetProxyInfoForHostUrlEx call with idiomatic Go types.
func DnsConnectionGetProxyInfoForHostUrlEx(pwszHostUrl string, pSelectionContext []byte, dwExplicitInterfaceIndex uint32, pwszConnectionName string, pProxyInfoEx *networkmanagementdns.DNS_CONNECTION_PROXY_INFO_EX) uint32 {
	_pwszHostUrl := win32.UTF16Ptr(pwszHostUrl)
	var _pSelectionContext *byte
	if len(pSelectionContext) > 0 {
		_pSelectionContext = &pSelectionContext[0]
	}
	_pwszConnectionName := win32.UTF16Ptr(pwszConnectionName)
	return networkmanagementdns.DnsConnectionGetProxyInfoForHostUrlEx(foundation.PWSTR(_pwszHostUrl), _pSelectionContext, uint32(len(pSelectionContext)), dwExplicitInterfaceIndex, foundation.PWSTR(_pwszConnectionName), pProxyInfoEx)
}

// DnsConnectionGetProxyList wraps the raw DnsConnectionGetProxyList call with idiomatic Go types.
func DnsConnectionGetProxyList(pwszConnectionName string, pProxyList *networkmanagementdns.DNS_CONNECTION_PROXY_LIST) uint32 {
	_pwszConnectionName := win32.UTF16Ptr(pwszConnectionName)
	return networkmanagementdns.DnsConnectionGetProxyList(foundation.PWSTR(_pwszConnectionName), pProxyList)
}

// DnsConnectionSetProxyInfo wraps the raw DnsConnectionSetProxyInfo call with idiomatic Go types.
func DnsConnectionSetProxyInfo(pwszConnectionName string, Type networkmanagementdns.DNS_CONNECTION_PROXY_TYPE, pProxyInfo *networkmanagementdns.DNS_CONNECTION_PROXY_INFO) uint32 {
	_pwszConnectionName := win32.UTF16Ptr(pwszConnectionName)
	return networkmanagementdns.DnsConnectionSetProxyInfo(foundation.PWSTR(_pwszConnectionName), Type, pProxyInfo)
}

// DnsFreeProxyName wraps the raw DnsFreeProxyName call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsfreeproxyname
func DnsFreeProxyName(proxyName string) {
	_proxyName := win32.UTF16Ptr(proxyName)
	networkmanagementdns.DnsFreeProxyName(foundation.PWSTR(_proxyName))
}

// DnsGetProxyInformation wraps the raw DnsGetProxyInformation call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsgetproxyinformation
func DnsGetProxyInformation(hostName string, proxyInformation *networkmanagementdns.DNS_PROXY_INFORMATION, defaultProxyInformation *networkmanagementdns.DNS_PROXY_INFORMATION, completionRoutine networkmanagementdns.DNS_PROXY_COMPLETION_ROUTINE, completionContext unsafe.Pointer) uint32 {
	_hostName := win32.UTF16Ptr(hostName)
	return networkmanagementdns.DnsGetProxyInformation(foundation.PWSTR(_hostName), proxyInformation, defaultProxyInformation, completionRoutine, completionContext)
}

// DnsModifyRecordsInSet_ wraps the raw DnsModifyRecordsInSet_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsmodifyrecordsinset_w
func DnsModifyRecordsInSet_(pAddRecords *networkmanagementdns.DNS_RECORDA, pDeleteRecords *networkmanagementdns.DNS_RECORDA, Options uint32, hCredentials foundation.HANDLE, pExtraList unsafe.Pointer, pReserved unsafe.Pointer) int32 {
	return networkmanagementdns.DnsModifyRecordsInSet_W(pAddRecords, pDeleteRecords, Options, hCredentials, pExtraList, pReserved)
}

// DnsNameCompare_ wraps the raw DnsNameCompare_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsnamecompare_w
func DnsNameCompare_(pName1 string, pName2 string) bool {
	_pName1 := win32.UTF16Ptr(pName1)
	_pName2 := win32.UTF16Ptr(pName2)
	return networkmanagementdns.DnsNameCompare_W(foundation.PWSTR(_pName1), foundation.PWSTR(_pName2)) != 0
}

// DnsNameCompare_A wraps the raw DnsNameCompare_A call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsnamecompare_a
func DnsNameCompare_A(pName1 foundation.PSTR, pName2 foundation.PSTR) bool {
	return networkmanagementdns.DnsNameCompare_A(pName1, pName2) != 0
}

// DnsQueryConfig wraps the raw DnsQueryConfig call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsqueryconfig
func DnsQueryConfig(Config networkmanagementdns.DNS_CONFIG_TYPE, Flag uint32, pwsAdapterName string, pReserved unsafe.Pointer, pBuffer unsafe.Pointer, pBufLen *uint32) int32 {
	_pwsAdapterName := win32.UTF16Ptr(pwsAdapterName)
	return networkmanagementdns.DnsQueryConfig(Config, Flag, foundation.PWSTR(_pwsAdapterName), pReserved, pBuffer, pBufLen)
}

// DnsQuery_ wraps the raw DnsQuery_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsquery_w
func DnsQuery_(pszName string, wType uint16, Options networkmanagementdns.DNS_QUERY_OPTIONS, pExtra unsafe.Pointer, ppQueryResults **networkmanagementdns.DNS_RECORDA, pReserved *unsafe.Pointer) foundation.WIN32_ERROR {
	_pszName := win32.UTF16Ptr(pszName)
	return networkmanagementdns.DnsQuery_W(foundation.PWSTR(_pszName), wType, Options, pExtra, ppQueryResults, pReserved)
}

// DnsRecordCompare wraps the raw DnsRecordCompare call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsrecordcompare
func DnsRecordCompare(pRecord1 *networkmanagementdns.DNS_RECORDA, pRecord2 *networkmanagementdns.DNS_RECORDA) bool {
	return networkmanagementdns.DnsRecordCompare(pRecord1, pRecord2) != 0
}

// DnsRecordSetCompare wraps the raw DnsRecordSetCompare call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsrecordsetcompare
func DnsRecordSetCompare(pRR1 *networkmanagementdns.DNS_RECORDA, pRR2 *networkmanagementdns.DNS_RECORDA, ppDiff1 **networkmanagementdns.DNS_RECORDA, ppDiff2 **networkmanagementdns.DNS_RECORDA) bool {
	return networkmanagementdns.DnsRecordSetCompare(pRR1, pRR2, ppDiff1, ppDiff2) != 0
}

// DnsReplaceRecordSet wraps the raw DnsReplaceRecordSetW call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsreplacerecordsetw
func DnsReplaceRecordSet(pReplaceSet *networkmanagementdns.DNS_RECORDA, Options uint32, hContext foundation.HANDLE, pExtraInfo unsafe.Pointer, pReserved unsafe.Pointer) int32 {
	return networkmanagementdns.DnsReplaceRecordSetW(pReplaceSet, Options, hContext, pExtraInfo, pReserved)
}

// DnsServiceConstructInstance wraps the raw DnsServiceConstructInstance call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsserviceconstructinstance
func DnsServiceConstructInstance(pServiceName string, pHostName string, pIp4 *uint32, pIp6 *networkmanagementdns.IP6_ADDRESS, wPort uint16, wPriority uint16, wWeight uint16, dwPropertiesCount uint32, keys *foundation.PWSTR, values *foundation.PWSTR) *networkmanagementdns.DNS_SERVICE_INSTANCE {
	_pServiceName := win32.UTF16Ptr(pServiceName)
	_pHostName := win32.UTF16Ptr(pHostName)
	return networkmanagementdns.DnsServiceConstructInstance(foundation.PWSTR(_pServiceName), foundation.PWSTR(_pHostName), pIp4, pIp6, wPort, wPriority, wWeight, dwPropertiesCount, keys, values)
}

// DnsSetApplicationSettings wraps the raw DnsSetApplicationSettings call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnssetapplicationsettings
func DnsSetApplicationSettings(pServers []networkmanagementdns.DNS_CUSTOM_SERVER, pSettings *networkmanagementdns.DNS_APPLICATION_SETTINGS) uint32 {
	var _pServers *networkmanagementdns.DNS_CUSTOM_SERVER
	if len(pServers) > 0 {
		_pServers = &pServers[0]
	}
	return networkmanagementdns.DnsSetApplicationSettings(uint32(len(pServers)), _pServers, pSettings)
}

// DnsValidateName_ wraps the raw DnsValidateName_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnsvalidatename_w
func DnsValidateName_(pszName string, Format networkmanagementdns.DNS_NAME_FORMAT) int32 {
	_pszName := win32.UTF16Ptr(pszName)
	return networkmanagementdns.DnsValidateName_W(foundation.PWSTR(_pszName), Format)
}

// DnsWriteQuestionToBuffer_UTF8 wraps the raw DnsWriteQuestionToBuffer_UTF8 call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnswritequestiontobuffer_utf8
func DnsWriteQuestionToBuffer_UTF8(pDnsBuffer *networkmanagementdns.DNS_MESSAGE_BUFFER, pdwBufferSize *uint32, pszName foundation.PSTR, wType uint16, Xid uint16, fRecursionDesired bool) bool {
	_fRecursionDesired := foundation.BOOL(win32.Bool32(fRecursionDesired))
	return networkmanagementdns.DnsWriteQuestionToBuffer_UTF8(pDnsBuffer, pdwBufferSize, pszName, wType, Xid, _fRecursionDesired) != 0
}

// DnsWriteQuestionToBuffer_W wraps the raw DnsWriteQuestionToBuffer_W call with idiomatic Go types.
// https://learn.microsoft.com/windows/win32/api/windns/nf-windns-dnswritequestiontobuffer_w
func DnsWriteQuestionToBuffer_W(pDnsBuffer *networkmanagementdns.DNS_MESSAGE_BUFFER, pdwBufferSize *uint32, pszName string, wType uint16, Xid uint16, fRecursionDesired bool) bool {
	_pszName := win32.UTF16Ptr(pszName)
	_fRecursionDesired := foundation.BOOL(win32.Bool32(fRecursionDesired))
	return networkmanagementdns.DnsWriteQuestionToBuffer_W(pDnsBuffer, pdwBufferSize, foundation.PWSTR(_pszName), wType, Xid, _fRecursionDesired) != 0
}
