// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package isolation

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	systemcom "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/com"
)

// IIsolatedAppLauncher: https://learn.microsoft.com/windows/win32/api/isolatedapplauncher/nn-isolatedapplauncher-iisolatedapplauncher
// IID: f686878f-7b42-4cc4-96fb-f4f3b6e3d24d
type IIsolatedAppLauncher struct {
	systemcom.IUnknown
}

// IID_IIsolatedAppLauncher is the interface identifier for IIsolatedAppLauncher.
var IID_IIsolatedAppLauncher = win32.GUID{Data1: 0xf686878f, Data2: 0x7b42, Data3: 0x4cc4, Data4: [8]byte{0x96, 0xfb, 0xf4, 0xf3, 0xb6, 0xe3, 0xd2, 0x4d}}

// Launch dispatches through IIsolatedAppLauncher's vtable slot 3.
func (self *IIsolatedAppLauncher) Launch(appUserModelId string, arguments string, telemetryParameters *IsolatedAppLauncherTelemetryParameters) error {
	_appUserModelId := win32.UTF16Ptr(appUserModelId)
	_arguments := win32.UTF16Ptr(arguments)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[3], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(_appUserModelId)), uintptr(unsafe.Pointer(_arguments)), uintptr(unsafe.Pointer(telemetryParameters)))
	return win32.HRESULTError(int32(r1))
}

// IID: 1aa24232-9a91-4201-88cb-122f9d6522e0
type IIsolatedProcessLauncher struct {
	systemcom.IUnknown
}

// IID_IIsolatedProcessLauncher is the interface identifier for IIsolatedProcessLauncher.
var IID_IIsolatedProcessLauncher = win32.GUID{Data1: 0x1aa24232, Data2: 0x9a91, Data3: 0x4201, Data4: [8]byte{0x88, 0xcb, 0x12, 0x2f, 0x9d, 0x65, 0x22, 0xe0}}

// LaunchProcess dispatches through IIsolatedProcessLauncher's vtable slot 3.
func (self *IIsolatedProcessLauncher) LaunchProcess(process string, arguments string, workingDirectory string) error {
	_process := win32.UTF16Ptr(process)
	_arguments := win32.UTF16Ptr(arguments)
	_workingDirectory := win32.UTF16Ptr(workingDirectory)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[3], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(_process)), uintptr(unsafe.Pointer(_arguments)), uintptr(unsafe.Pointer(_workingDirectory)))
	return win32.HRESULTError(int32(r1))
}

// ShareDirectory dispatches through IIsolatedProcessLauncher's vtable slot 4.
func (self *IIsolatedProcessLauncher) ShareDirectory(hostPath string, containerPath string, readOnly bool) error {
	_hostPath := win32.UTF16Ptr(hostPath)
	_containerPath := win32.UTF16Ptr(containerPath)
	_readOnly := win32.Bool32(readOnly)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[4], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(_hostPath)), uintptr(unsafe.Pointer(_containerPath)), uintptr(_readOnly))
	return win32.HRESULTError(int32(r1))
}

// GetContainerGuid dispatches through IIsolatedProcessLauncher's vtable slot 5.
func (self *IIsolatedProcessLauncher) GetContainerGuid(guid *win32.GUID) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[5], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(guid)))
	return win32.HRESULTError(int32(r1))
}

// AllowSetForegroundAccess dispatches through IIsolatedProcessLauncher's vtable slot 6.
func (self *IIsolatedProcessLauncher) AllowSetForegroundAccess(pid uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(pid))
	return win32.HRESULTError(int32(r1))
}

// IsContainerRunning dispatches through IIsolatedProcessLauncher's vtable slot 7.
func (self *IIsolatedProcessLauncher) IsContainerRunning(running *foundation.BOOL) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(running)))
	return win32.HRESULTError(int32(r1))
}

// IID: 780e4416-5e72-4123-808e-66dc6479feef
type IIsolatedProcessLauncher2 struct {
	IIsolatedProcessLauncher
}

// IID_IIsolatedProcessLauncher2 is the interface identifier for IIsolatedProcessLauncher2.
var IID_IIsolatedProcessLauncher2 = win32.GUID{Data1: 0x780e4416, Data2: 0x5e72, Data3: 0x4123, Data4: [8]byte{0x80, 0x8e, 0x66, 0xdc, 0x64, 0x79, 0xfe, 0xef}}

// LaunchProcess2 dispatches through IIsolatedProcessLauncher2's vtable slot 8.
func (self *IIsolatedProcessLauncher2) LaunchProcess2(process string, arguments string, workingDirectory string, correlationGuid *win32.GUID) error {
	_process := win32.UTF16Ptr(process)
	_arguments := win32.UTF16Ptr(arguments)
	_workingDirectory := win32.UTF16Ptr(workingDirectory)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(_process)), uintptr(unsafe.Pointer(_arguments)), uintptr(unsafe.Pointer(_workingDirectory)), uintptr(unsafe.Pointer(correlationGuid)))
	return win32.HRESULTError(int32(r1))
}
