// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package systemservices

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	"github.com/deploymenttheory/go-bindings-win32/bindings/win32/security"
)

type ANON_OBJECT_HEADER struct {
	Sig1          uint16
	Sig2          uint16
	Version       uint16
	Machine       uint16
	TimeDateStamp uint32
	ClassID       win32.GUID
	SizeOfData    uint32
}

type ANON_OBJECT_HEADER_BIGOBJ struct {
	Sig1                 uint16
	Sig2                 uint16
	Version              uint16
	Machine              uint16
	TimeDateStamp        uint32
	ClassID              win32.GUID
	SizeOfData           uint32
	Flags                uint32
	MetaDataSize         uint32
	MetaDataOffset       uint32
	NumberOfSections     uint32
	PointerToSymbolTable uint32
	NumberOfSymbols      uint32
}

type ANON_OBJECT_HEADER_V2 struct {
	Sig1           uint16
	Sig2           uint16
	Version        uint16
	Machine        uint16
	TimeDateStamp  uint32
	ClassID        win32.GUID
	SizeOfData     uint32
	Flags          uint32
	MetaDataSize   uint32
	MetaDataOffset uint32
}

type APPLICATIONLAUNCH_SETTING_VALUE struct {
	ActivationTime   int64
	Flags            uint32
	ButtonInstanceID uint32
}

type ATTRIBUTES_AND_SID struct {
	Attributes uint32
	SidStart   uint32
}

type COMPONENT_FILTER struct {
	ComponentFlags uint32
}

// DISPATCHER_CONTEXT_NONVOLREG_ARM64 is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type DISPATCHER_CONTEXT_NONVOLREG_ARM64 struct {
	Data [19]uint64
}

// DRIVER_INFO_ENTRY_Flags_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type DRIVER_INFO_ENTRY_Flags_e__Union struct {
	Data [1]uint16
}

type DRIVER_INFO_ENTRY struct {
	InternalName                     [32]foundation.CHAR
	ImageHashAlgorithm               uint16
	PublisherThumbprintHashAlgorithm uint16
	ImageHashOffset                  uint32
	PublisherThumbprintOffset        uint32
	LoadCount                        uint16
	OemNameSize                      uint16
	OemNameOffset                    uint32
	Flags                            DRIVER_INFO_ENTRY_Flags_e__Union
	Padding                          uint16
}

// DRIVER_RUNTIME_REPORT_Flags_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type DRIVER_RUNTIME_REPORT_Flags_e__Union struct {
	Data [1]uint16
}

type DRIVER_RUNTIME_REPORT struct {
	Header          RUNTIME_REPORT_HEADER
	NumberOfDrivers uint16
	Flags           DRIVER_RUNTIME_REPORT_Flags_e__Union
	DriverEntries   [1]DRIVER_INFO_ENTRY
}

type ENLISTMENT_BASIC_INFORMATION struct {
	EnlistmentId      win32.GUID
	TransactionId     win32.GUID
	ResourceManagerId win32.GUID
}

type ENLISTMENT_CRM_INFORMATION struct {
	CrmTransactionManagerId win32.GUID
	CrmResourceManagerId    win32.GUID
	CrmEnlistmentId         win32.GUID
}

type FILE_CASE_SENSITIVE_INFORMATION struct {
	Flags uint32
}

// FILE_NOTIFY_FULL_INFORMATION_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type FILE_NOTIFY_FULL_INFORMATION_Anonymous_e__Union struct {
	Data [1]uint32
}

type FILE_NOTIFY_FULL_INFORMATION struct {
	NextEntryOffset      uint32
	Action               uint32
	CreationTime         int64
	LastModificationTime int64
	LastChangeTime       int64
	LastAccessTime       int64
	AllocatedLength      int64
	FileSize             int64
	FileAttributes       uint32
	Anonymous            FILE_NOTIFY_FULL_INFORMATION_Anonymous_e__Union
	FileId               int64
	ParentFileId         int64
	FileNameLength       uint16
	FileNameFlags        byte
	Reserved             byte
	FileName             [1]uint16
}

type FILE_STAT_INFORMATION struct {
	FileId          int64
	CreationTime    int64
	LastAccessTime  int64
	LastWriteTime   int64
	ChangeTime      int64
	AllocationSize  int64
	EndOfFile       int64
	FileAttributes  uint32
	ReparseTag      uint32
	NumberOfLinks   uint32
	EffectiveAccess uint32
}

type FILE_STAT_LX_INFORMATION struct {
	FileId          int64
	CreationTime    int64
	LastAccessTime  int64
	LastWriteTime   int64
	ChangeTime      int64
	AllocationSize  int64
	EndOfFile       int64
	FileAttributes  uint32
	ReparseTag      uint32
	NumberOfLinks   uint32
	EffectiveAccess uint32
	LxFlags         uint32
	LxUid           uint32
	LxGid           uint32
	LxMode          uint32
	LxDeviceIdMajor uint32
	LxDeviceIdMinor uint32
}

// GDI_NONREMOTE_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type GDI_NONREMOTE_u_e__Struct struct {
	Data [1]uint64
}

type GDI_NONREMOTE struct {
	FContext int32
	U        GDI_NONREMOTE_u_e__Struct
}

// HEAP_OPTIMIZE_RESOURCES_INFORMATION: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-heap_optimize_resources_information
type HEAP_OPTIMIZE_RESOURCES_INFORMATION struct {
	Version uint32
	Flags   uint32
}

type HIBERFILE_BUCKET struct {
	MaxPhysicalMemory     uint64
	PhysicalMemoryPercent [3]uint32
}

// IMAGE_ALPHA64_RUNTIME_FUNCTION_ENTRY is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_ALPHA64_RUNTIME_FUNCTION_ENTRY struct {
	Data [10]uint32
}

type IMAGE_ALPHA_RUNTIME_FUNCTION_ENTRY struct {
	BeginAddress     uint32
	EndAddress       uint32
	ExceptionHandler uint32
	HandlerData      uint32
	PrologEndAddress uint32
}

type IMAGE_ARCHITECTURE_ENTRY struct {
	FixupInstRVA uint32
	NewInst      uint32
}

type IMAGE_ARCHITECTURE_HEADER struct {
	Bitfield      uint32
	FirstEntryRVA uint32
}

type IMAGE_ARCHIVE_MEMBER_HEADER struct {
	Name      [16]byte
	Date      [12]byte
	UserID    [6]byte
	GroupID   [6]byte
	Mode      [8]byte
	Size      [10]byte
	EndHeader [2]byte
}

// IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA struct {
	Data [1]uint32
}

// IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA_EPILOG_SCOPE is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA_EPILOG_SCOPE struct {
	Data [1]uint32
}

// IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA_EXTENDED is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY_XDATA_EXTENDED struct {
	Data [1]uint32
}

// IMAGE_ARM_RUNTIME_FUNCTION_ENTRY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_ARM_RUNTIME_FUNCTION_ENTRY_Anonymous_e__Union struct {
	Data [1]uint32
}

type IMAGE_ARM_RUNTIME_FUNCTION_ENTRY struct {
	BeginAddress uint32
	Anonymous    IMAGE_ARM_RUNTIME_FUNCTION_ENTRY_Anonymous_e__Union
}

// IMAGE_AUX_SYMBOL is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_AUX_SYMBOL struct {
	Data [9]uint16
}

// IMAGE_AUX_SYMBOL_EX is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_AUX_SYMBOL_EX struct {
	Data [10]uint16
}

// IMAGE_AUX_SYMBOL_TOKEN_DEF is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_AUX_SYMBOL_TOKEN_DEF struct {
	Data [9]uint16
}

type IMAGE_BASE_RELOCATION struct {
	VirtualAddress uint32
	SizeOfBlock    uint32
}

// IMAGE_BDD_DYNAMIC_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_BDD_DYNAMIC_RELOCATION struct {
	Data [8]byte
}

// IMAGE_BDD_INFO is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_BDD_INFO struct {
	Data [8]byte
}

type IMAGE_BOUND_FORWARDER_REF struct {
	TimeDateStamp    uint32
	OffsetModuleName uint16
	Reserved         uint16
}

type IMAGE_BOUND_IMPORT_DESCRIPTOR struct {
	TimeDateStamp               uint32
	OffsetModuleName            uint16
	NumberOfModuleForwarderRefs uint16
}

type IMAGE_CE_RUNTIME_FUNCTION_ENTRY struct {
	FuncStart uint32
	Bitfield  uint32
}

type IMAGE_DEBUG_MISC struct {
	DataType uint32
	Length   uint32
	Unicode  foundation.BOOLEAN
	Reserved [3]byte
	Data     [1]byte
}

// IMAGE_DOS_HEADER is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_DOS_HEADER struct {
	Data [32]uint16
}

// IMAGE_DYNAMIC_RELOCATION32 is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_DYNAMIC_RELOCATION32 struct {
	Data [8]byte
}

// IMAGE_DYNAMIC_RELOCATION32_V2 is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_DYNAMIC_RELOCATION32_V2 struct {
	Data [20]byte
}

// IMAGE_DYNAMIC_RELOCATION64 is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_DYNAMIC_RELOCATION64 struct {
	Data [12]byte
}

// IMAGE_DYNAMIC_RELOCATION64_V2 is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_DYNAMIC_RELOCATION64_V2 struct {
	Data [24]byte
}

type IMAGE_DYNAMIC_RELOCATION_TABLE struct {
	Version uint32
	Size    uint32
}

// IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER struct {
	Data [8]byte
}

type IMAGE_EXPORT_DIRECTORY struct {
	Characteristics       uint32
	TimeDateStamp         uint32
	MajorVersion          uint16
	MinorVersion          uint16
	Name                  uint32
	Base                  uint32
	NumberOfFunctions     uint32
	NumberOfNames         uint32
	AddressOfFunctions    uint32
	AddressOfNames        uint32
	AddressOfNameOrdinals uint32
}

// IMAGE_FUNCTION_OVERRIDE_DYNAMIC_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_FUNCTION_OVERRIDE_DYNAMIC_RELOCATION struct {
	Data [16]byte
}

// IMAGE_FUNCTION_OVERRIDE_HEADER is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_FUNCTION_OVERRIDE_HEADER struct {
	Data [4]byte
}

type IMAGE_HOT_PATCH_BASE struct {
	SequenceNumber        uint32
	Flags                 uint32
	OriginalTimeDateStamp uint32
	OriginalCheckSum      uint32
	CodeIntegrityInfo     uint32
	CodeIntegritySize     uint32
	PatchTable            uint32
	BufferOffset          uint32
}

type IMAGE_HOT_PATCH_HASHES struct {
	SHA256 [32]byte
	SHA1   [20]byte
}

type IMAGE_HOT_PATCH_INFO struct {
	Version           uint32
	Size              uint32
	SequenceNumber    uint32
	BaseImageList     uint32
	BaseImageCount    uint32
	BufferOffset      uint32
	ExtraPatchSize    uint32
	MinSequenceNumber uint32
	Flags             uint32
}

type IMAGE_HOT_PATCH_MACHINE_Anonymous_e__Struct struct {
	Bitfield uint32
}

type IMAGE_HOT_PATCH_MACHINE struct {
	Anonymous IMAGE_HOT_PATCH_MACHINE_Anonymous_e__Struct
}

type IMAGE_IMPORT_BY_NAME struct {
	Hint uint16
	Name [1]foundation.CHAR
}

// IMAGE_IMPORT_CONTROL_TRANSFER_ARM64_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_IMPORT_CONTROL_TRANSFER_ARM64_RELOCATION struct {
	Data [4]byte
}

// IMAGE_IMPORT_CONTROL_TRANSFER_DYNAMIC_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_IMPORT_CONTROL_TRANSFER_DYNAMIC_RELOCATION struct {
	Data [4]byte
}

// IMAGE_IMPORT_DESCRIPTOR_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_IMPORT_DESCRIPTOR_Anonymous_e__Union struct {
	Data [1]uint32
}

type IMAGE_IMPORT_DESCRIPTOR struct {
	Anonymous      IMAGE_IMPORT_DESCRIPTOR_Anonymous_e__Union
	TimeDateStamp  uint32
	ForwarderChain uint32
	Name           uint32
	FirstThunk     uint32
}

// IMAGE_INDIR_CONTROL_TRANSFER_DYNAMIC_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_INDIR_CONTROL_TRANSFER_DYNAMIC_RELOCATION struct {
	Data [2]byte
}

// IMAGE_LINENUMBER_Type_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_LINENUMBER_Type_e__Union struct {
	Data [2]uint16
}

type IMAGE_LINENUMBER struct {
	Type       IMAGE_LINENUMBER_Type_e__Union
	Linenumber uint16
}

// IMAGE_OS2_HEADER is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_OS2_HEADER struct {
	Data [32]uint16
}

// IMAGE_POLICY_ENTRY_u_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_POLICY_ENTRY_u_e__Union struct {
	Data [1]uint64
}

type IMAGE_POLICY_ENTRY struct {
	Type     IMAGE_POLICY_ENTRY_TYPE
	PolicyId IMAGE_POLICY_ID
	U        IMAGE_POLICY_ENTRY_u_e__Union
}

type IMAGE_POLICY_METADATA struct {
	Version       byte
	Reserved0     [7]byte
	ApplicationId uint64
	Policies      [1]IMAGE_POLICY_ENTRY
}

type IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER struct {
	PrologueByteCount byte
}

// IMAGE_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_RELOCATION struct {
	Data [5]uint16
}

type IMAGE_RESOURCE_DATA_ENTRY struct {
	OffsetToData uint32
	Size         uint32
	CodePage     uint32
	Reserved     uint32
}

type IMAGE_RESOURCE_DIRECTORY struct {
	Characteristics      uint32
	TimeDateStamp        uint32
	MajorVersion         uint16
	MinorVersion         uint16
	NumberOfNamedEntries uint16
	NumberOfIdEntries    uint16
}

// IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous1_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous1_e__Union struct {
	Data [1]uint32
}

// IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous2_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous2_e__Union struct {
	Data [1]uint32
}

type IMAGE_RESOURCE_DIRECTORY_ENTRY struct {
	Anonymous1 IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous1_e__Union
	Anonymous2 IMAGE_RESOURCE_DIRECTORY_ENTRY_Anonymous2_e__Union
}

type IMAGE_RESOURCE_DIRECTORY_STRING struct {
	Length     uint16
	NameString [1]foundation.CHAR
}

type IMAGE_RESOURCE_DIR_STRING_U struct {
	Length     uint16
	NameString [1]uint16
}

type IMAGE_SEPARATE_DEBUG_HEADER struct {
	Signature          uint16
	Flags              uint16
	Machine            uint16
	Characteristics    uint16
	TimeDateStamp      uint32
	CheckSum           uint32
	ImageBase          uint32
	SizeOfImage        uint32
	NumberOfSections   uint32
	ExportedNamesSize  uint32
	DebugDirectorySize uint32
	SectionAlignment   uint32
	Reserved           [2]uint32
}

// IMAGE_SWITCHTABLE_BRANCH_DYNAMIC_RELOCATION is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_SWITCHTABLE_BRANCH_DYNAMIC_RELOCATION struct {
	Data [2]byte
}

// IMAGE_SYMBOL is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_SYMBOL struct {
	Data [9]uint16
}

// IMAGE_SYMBOL_EX is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_SYMBOL_EX struct {
	Data [10]uint16
}

// IMAGE_TLS_DIRECTORY32_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMAGE_TLS_DIRECTORY32_Anonymous_e__Union struct {
	Data [1]uint32
}

type IMAGE_TLS_DIRECTORY32 struct {
	StartAddressOfRawData uint32
	EndAddressOfRawData   uint32
	AddressOfIndex        uint32
	AddressOfCallBacks    uint32
	SizeOfZeroFill        uint32
	Anonymous             IMAGE_TLS_DIRECTORY32_Anonymous_e__Union
}

// IMAGE_TLS_DIRECTORY64 is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_TLS_DIRECTORY64 struct {
	Data [10]uint32
}

// IMAGE_VXD_HEADER is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type IMAGE_VXD_HEADER struct {
	Data [98]uint16
}

// IMPORT_OBJECT_HEADER_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IMPORT_OBJECT_HEADER_Anonymous_e__Union struct {
	Data [1]uint16
}

type IMPORT_OBJECT_HEADER struct {
	Sig1          uint16
	Sig2          uint16
	Version       uint16
	Machine       uint16
	TimeDateStamp uint32
	SizeOfData    uint32
	Anonymous     IMPORT_OBJECT_HEADER_Anonymous_e__Union
	Bitfield      uint16
}

type JOBOBJECT_NETWORK_ACCOUNTING_INFORMATION struct {
	DataBytesIn  uint64
	DataBytesOut uint64
}

// KERNEL_CET_CONTEXT_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type KERNEL_CET_CONTEXT_Anonymous_e__Union struct {
	Data [1]uint16
}

type KERNEL_CET_CONTEXT struct {
	Ssp       uint64
	Rip       uint64
	SegCs     uint16
	Anonymous KERNEL_CET_CONTEXT_Anonymous_e__Union
	Fill      [2]uint16
}

type KTMOBJECT_CURSOR struct {
	LastQuery     win32.GUID
	ObjectIdCount uint32
	ObjectIds     [1]win32.GUID
}

type MAXVERSIONTESTED_INFO struct {
	MaxVersionTested uint64
}

type NETWORK_APP_INSTANCE_EA struct {
	AppInstanceID win32.GUID
	CsvFlags      uint32
}

// NON_PAGED_DEBUG_INFO is a packed C struct (non-default field alignment), exposed as
// correctly sized and aligned opaque backing storage; read or write a specific
// field through an unsafe.Pointer cast.
type NON_PAGED_DEBUG_INFO struct {
	Data [8]uint32
}

type NOTIFY_USER_POWER_SETTING struct {
	Guid win32.GUID
}

// NT_TIB32_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NT_TIB32_Anonymous_e__Union struct {
	Data [1]uint32
}

type NT_TIB32 struct {
	ExceptionList        uint32
	StackBase            uint32
	StackLimit           uint32
	SubSystemTib         uint32
	Anonymous            NT_TIB32_Anonymous_e__Union
	ArbitraryUserPointer uint32
	Self                 uint32
}

// NT_TIB64_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NT_TIB64_Anonymous_e__Union struct {
	Data [1]uint64
}

type NT_TIB64 struct {
	ExceptionList        uint64
	StackBase            uint64
	StackLimit           uint64
	SubSystemTib         uint64
	Anonymous            NT_TIB64_Anonymous_e__Union
	ArbitraryUserPointer uint64
	Self                 uint64
}

type PACKEDEVENTINFO struct {
	UlSize                uint32
	UlNumEventsForLogFile uint32
	UlOffsets             [1]uint32
}

// POWER_LIMIT_ATTRIBUTES_Flags_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type POWER_LIMIT_ATTRIBUTES_Flags_e__Union struct {
	Data [1]uint32
}

type POWER_LIMIT_ATTRIBUTES struct {
	Type             POWER_LIMIT_TYPES
	DomainId         uint32
	MaxValue         uint32
	MinValue         uint32
	MinTimeParameter uint32
	MaxTimeParameter uint32
	DefaultACValue   uint32
	DefaultDCValue   uint32
	Flags            POWER_LIMIT_ATTRIBUTES_Flags_e__Union
}

type POWER_LIMIT_VALUE struct {
	Type          POWER_LIMIT_TYPES
	DomainId      uint32
	TargetValue   uint32
	TimeParameter uint32
}

type PROCESSOR_IDLESTATE_INFO struct {
	TimeCheck      uint32
	DemotePercent  byte
	PromotePercent byte
	Spare          [2]byte
}

// PROCESSOR_IDLESTATE_POLICY_Flags_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESSOR_IDLESTATE_POLICY_Flags_e__Union struct {
	Data [1]uint16
}

type PROCESSOR_IDLESTATE_POLICY struct {
	Revision    uint16
	Flags       PROCESSOR_IDLESTATE_POLICY_Flags_e__Union
	PolicyCount uint32
	Policy      [3]PROCESSOR_IDLESTATE_INFO
}

// PROCESSOR_PERFSTATE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESSOR_PERFSTATE_POLICY_Anonymous_e__Union struct {
	Data [1]byte
}

type PROCESSOR_PERFSTATE_POLICY struct {
	Revision         uint32
	MaxThrottle      byte
	MinThrottle      byte
	BusyAdjThreshold byte
	Anonymous        PROCESSOR_PERFSTATE_POLICY_Anonymous_e__Union
	TimeCheck        uint32
	IncreaseTime     uint32
	DecreaseTime     uint32
	IncreasePercent  uint32
	DecreasePercent  uint32
}

// PROCESS_MITIGATION_ASLR_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_ASLR_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_ASLR_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_aslr_policy
type PROCESS_MITIGATION_ASLR_POLICY struct {
	Anonymous PROCESS_MITIGATION_ASLR_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_binary_signature_policy
type PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY struct {
	Anonymous PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_CHILD_PROCESS_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_CHILD_PROCESS_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

type PROCESS_MITIGATION_CHILD_PROCESS_POLICY struct {
	Anonymous PROCESS_MITIGATION_CHILD_PROCESS_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_control_flow_guard_policy
type PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY struct {
	Anonymous PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_DEP_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_DEP_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_DEP_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_dep_policy
type PROCESS_MITIGATION_DEP_POLICY struct {
	Anonymous PROCESS_MITIGATION_DEP_POLICY_Anonymous_e__Union
	Permanent foundation.BOOLEAN
}

// PROCESS_MITIGATION_DYNAMIC_CODE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_DYNAMIC_CODE_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_DYNAMIC_CODE_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_dynamic_code_policy
type PROCESS_MITIGATION_DYNAMIC_CODE_POLICY struct {
	Anonymous PROCESS_MITIGATION_DYNAMIC_CODE_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_extension_point_disable_policy
type PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY struct {
	Anonymous PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_FONT_DISABLE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_FONT_DISABLE_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_FONT_DISABLE_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_font_disable_policy
type PROCESS_MITIGATION_FONT_DISABLE_POLICY struct {
	Anonymous PROCESS_MITIGATION_FONT_DISABLE_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_IMAGE_LOAD_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_IMAGE_LOAD_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_IMAGE_LOAD_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_image_load_policy
type PROCESS_MITIGATION_IMAGE_LOAD_POLICY struct {
	Anonymous PROCESS_MITIGATION_IMAGE_LOAD_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_PAYLOAD_RESTRICTION_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_PAYLOAD_RESTRICTION_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

type PROCESS_MITIGATION_PAYLOAD_RESTRICTION_POLICY struct {
	Anonymous PROCESS_MITIGATION_PAYLOAD_RESTRICTION_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process-mitigation-redirection-trust-policy
type PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY struct {
	Anonymous PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_SEHOP_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_SEHOP_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

type PROCESS_MITIGATION_SEHOP_POLICY struct {
	Anonymous PROCESS_MITIGATION_SEHOP_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_SIDE_CHANNEL_ISOLATION_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_SIDE_CHANNEL_ISOLATION_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_SIDE_CHANNEL_ISOLATION_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_side_channel_isolation_policy
type PROCESS_MITIGATION_SIDE_CHANNEL_ISOLATION_POLICY struct {
	Anonymous PROCESS_MITIGATION_SIDE_CHANNEL_ISOLATION_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_STRICT_HANDLE_CHECK_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_STRICT_HANDLE_CHECK_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_STRICT_HANDLE_CHECK_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_strict_handle_check_policy
type PROCESS_MITIGATION_STRICT_HANDLE_CHECK_POLICY struct {
	Anonymous PROCESS_MITIGATION_STRICT_HANDLE_CHECK_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_SYSTEM_CALL_DISABLE_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_SYSTEM_CALL_DISABLE_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_SYSTEM_CALL_DISABLE_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_system_call_disable_policy
type PROCESS_MITIGATION_SYSTEM_CALL_DISABLE_POLICY struct {
	Anonymous PROCESS_MITIGATION_SYSTEM_CALL_DISABLE_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_SYSTEM_CALL_FILTER_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_SYSTEM_CALL_FILTER_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

type PROCESS_MITIGATION_SYSTEM_CALL_FILTER_POLICY struct {
	Anonymous PROCESS_MITIGATION_SYSTEM_CALL_FILTER_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

type PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY struct {
	Anonymous PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY_Anonymous_e__Union
}

// PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY_Anonymous_e__Union struct {
	Data [1]uint32
}

// PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-process_mitigation_user_shadow_stack_policy
type PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY struct {
	Anonymous PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY_Anonymous_e__Union
}

type PROCESS_NETWORK_COUNTERS struct {
	BytesIn  uint64
	BytesOut uint64
}

type QUOTA_LIMITS_EX struct {
	PagedPoolLimit        uintptr
	NonPagedPoolLimit     uintptr
	MinimumWorkingSetSize uintptr
	MaximumWorkingSetSize uintptr
	PagefileLimit         uintptr
	TimeLimit             int64
	WorkingSetLimit       uintptr
	Reserved2             uintptr
	Reserved3             uintptr
	Reserved4             uintptr
	Flags                 uint32
	CpuRateLimit          RATE_QUOTA_LIMIT
}

// RATE_QUOTA_LIMIT is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type RATE_QUOTA_LIMIT struct {
	Data [1]uint32
}

type REARRANGE_FILE_DATA struct {
	SourceStartingOffset uint64
	TargetOffset         uint64
	SourceFileHandle     foundation.HANDLE
	Length               uint32
	Flags                uint32
}

type REARRANGE_FILE_DATA32 struct {
	SourceStartingOffset uint64
	TargetOffset         uint64
	SourceFileHandle     uint32
	Length               uint32
	Flags                uint32
}

type REDBOOK_DIGITAL_AUDIO_EXTRACTION_INFO struct {
	Version       uint32
	Accurate      uint32
	Supported     uint32
	AccurateMask0 uint32
}

type RESOURCEMANAGER_BASIC_INFORMATION struct {
	ResourceManagerId win32.GUID
	DescriptionLength uint32
	Description       [1]uint16
}

type RESOURCEMANAGER_COMPLETION_INFORMATION struct {
	IoCompletionPortHandle foundation.HANDLE
	CompletionKey          uintptr
}

type RUNTIME_REPORT_DIGEST_HEADER struct {
	ReportType   uint16
	Reserved     uint16
	ReportDigest [64]byte
}

type RUNTIME_REPORT_HEADER struct {
	ReportType uint16
	Reserved   uint16
	ReportSize uint32
}

type RUNTIME_REPORT_PACKAGE_HEADER struct {
	Magic                         uint32
	PackageVersion                uint16
	NumberOfReports               uint16
	ReportTypesBitmap             uint64
	PackageSize                   uint32
	ReportDigestType              uint16
	TotalReportDigestsSize        uint16
	Reserved                      uint16
	SignatureScheme               uint16
	SignatureSize                 uint32
	TotalAuthenticatedReportsSize uint32
}

type RemHBITMAP struct {
	CbData uint32
	Data   [1]byte
}

type RemHBRUSH struct {
	CbData uint32
	Data   [1]byte
}

type RemHENHMETAFILE struct {
	CbData uint32
	Data   [1]byte
}

type RemHGLOBAL struct {
	FNullHGlobal int32
	CbData       uint32
	Data         [1]byte
}

type RemHMETAFILEPICT struct {
	Mm     int32
	XExt   int32
	YExt   int32
	CbData uint32
	Data   [1]byte
}

type RemHPALETTE struct {
	CbData uint32
	Data   [1]byte
}

// RemotableHandle_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type RemotableHandle_u_e__Struct struct {
	Data [1]uint32
}

type RemotableHandle struct {
	FContext int32
	U        RemotableHandle_u_e__Struct
}

type SCOPE_TABLE_AMD64_Anonymous_e__Struct struct {
	BeginAddress   uint32
	EndAddress     uint32
	HandlerAddress uint32
	JumpTarget     uint32
}

type SCOPE_TABLE_AMD64 struct {
	Count       uint32
	ScopeRecord [1]SCOPE_TABLE_AMD64_Anonymous_e__Struct
}

type SCOPE_TABLE_ARM_Anonymous_e__Struct struct {
	BeginAddress   uint32
	EndAddress     uint32
	HandlerAddress uint32
	JumpTarget     uint32
}

type SCOPE_TABLE_ARM struct {
	Count       uint32
	ScopeRecord [1]SCOPE_TABLE_ARM_Anonymous_e__Struct
}

type SCOPE_TABLE_ARM64_Anonymous_e__Struct struct {
	BeginAddress   uint32
	EndAddress     uint32
	HandlerAddress uint32
	JumpTarget     uint32
}

type SCOPE_TABLE_ARM64 struct {
	Count       uint32
	ScopeRecord [1]SCOPE_TABLE_ARM64_Anonymous_e__Struct
}

type SCRUB_DATA_INPUT struct {
	Size               uint32
	Flags              uint32
	MaximumIos         uint32
	ObjectId           [4]uint32
	StartingByteOffset uint64
	ByteCount          uint64
	Reserved           [36]uint32
	ResumeContext      [1040]byte
}

type SCRUB_DATA_OUTPUT struct {
	Size                                               uint32
	Flags                                              uint32
	Status                                             uint32
	ErrorFileOffset                                    uint64
	ErrorLength                                        uint64
	NumberOfBytesRepaired                              uint64
	NumberOfBytesFailed                                uint64
	InternalFileReference                              uint64
	ResumeContextLength                                uint16
	ParityExtentDataOffset                             uint16
	NextStartingByteOffset                             uint64
	ValidDataLength                                    uint64
	Reserved                                           [4]uint32
	NumberOfMetadataBytesProcessed                     uint64
	NumberOfDataBytesProcessed                         uint64
	TotalNumberOfMetadataBytesInUse                    uint64
	TotalNumberOfDataBytesInUse                        uint64
	DataBytesSkippedDueToNoAllocation                  uint64
	DataBytesSkippedDueToInvalidRun                    uint64
	DataBytesSkippedDueToIntegrityStream               uint64
	DataBytesSkippedDueToRegionBeingClean              uint64
	DataBytesSkippedDueToLockConflict                  uint64
	DataBytesSkippedDueToNoScrubDataFlag               uint64
	DataBytesSkippedDueToNoScrubNonIntegrityStreamFlag uint64
	DataBytesScrubbed                                  uint64
	ResumeContext                                      [1040]byte
}

type SCRUB_PARITY_EXTENT struct {
	Offset int64
	Length uint64
}

type SCRUB_PARITY_EXTENT_DATA struct {
	Size                         uint16
	Flags                        uint16
	NumberOfParityExtents        uint16
	MaximumNumberOfParityExtents uint16
	ParityExtents                [1]SCRUB_PARITY_EXTENT
}

type SECURITY_OBJECT_AI_PARAMS struct {
	Size           uint32
	ConstraintMask uint32
}

type SERVERSILO_BASIC_INFORMATION struct {
	ServiceSessionId     uint32
	State                SERVERSILO_STATE
	ExitStatus           uint32
	Reserved             foundation.BOOLEAN
	ApiSetSchema         unsafe.Pointer
	HostApiSetSchema     unsafe.Pointer
	ContainerBuildNumber uint32
	HostBuildNumber      uint32
}

type SERVERSILO_DIAGNOSTIC_INFORMATION struct {
	ReportId            win32.GUID
	ExitStatus          uint32
	CriticalProcessName [15]uint16
}

// SE_TOKEN_USER_Anonymous1_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type SE_TOKEN_USER_Anonymous1_e__Union struct {
	Data [2]uint64
}

// SE_TOKEN_USER_Anonymous2_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type SE_TOKEN_USER_Anonymous2_e__Union struct {
	Data [17]uint32
}

type SE_TOKEN_USER struct {
	Anonymous1 SE_TOKEN_USER_Anonymous1_e__Union
	Anonymous2 SE_TOKEN_USER_Anonymous2_e__Union
}

type SHARED_VIRTUAL_DISK_SUPPORT struct {
	SharedVirtualDiskSupport SharedVirtualDiskSupportType
	HandleState              SharedVirtualDiskHandleState
}

type SHUFFLE_FILE_DATA struct {
	StartingOffset int64
	Length         int64
	Flags          uint32
}

type SILOOBJECT_BASIC_INFORMATION struct {
	SiloId            uint32
	SiloParentId      uint32
	NumberOfProcesses uint32
	IsInServerSilo    foundation.BOOLEAN
	Reserved          [3]byte
}

type SUPPORTED_OS_INFO struct {
	MajorVersion uint16
	MinorVersion uint16
}

type SYSTEM_POWER_SOURCE_STATE struct {
	BatteryState            [8]uint32
	InstantaneousPeakPower  uint32
	InstantaneousPeakPeriod uint32
	SustainablePeakPower    uint32
	SustainablePeakPeriod   uint32
	PeakPower               uint32
	MaxOutputPower          uint32
	MaxInputPower           uint32
	BatteryRateInCurrent    int32
	BatteryVoltage          uint32
}

type TAPE_CREATE_PARTITION struct {
	Method uint32
	Count  uint32
	Size   uint32
}

// TAPE_GET_DRIVE_PARAMETERS: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-tape_get_drive_parameters
type TAPE_GET_DRIVE_PARAMETERS struct {
	ECC                   foundation.BOOLEAN
	Compression           foundation.BOOLEAN
	DataPadding           foundation.BOOLEAN
	ReportSetmarks        foundation.BOOLEAN
	DefaultBlockSize      uint32
	MaximumBlockSize      uint32
	MinimumBlockSize      uint32
	MaximumPartitionCount uint32
	FeaturesLow           uint32
	FeaturesHigh          TAPE_GET_DRIVE_PARAMETERS_FEATURES_HIGH
	EOTWarningZoneSize    uint32
}

// TAPE_GET_MEDIA_PARAMETERS: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-tape_get_media_parameters
type TAPE_GET_MEDIA_PARAMETERS struct {
	Capacity       int64
	Remaining      int64
	BlockSize      uint32
	PartitionCount uint32
	WriteProtected foundation.BOOLEAN
}

// TAPE_SET_DRIVE_PARAMETERS: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-tape_set_drive_parameters
type TAPE_SET_DRIVE_PARAMETERS struct {
	ECC                foundation.BOOLEAN
	Compression        foundation.BOOLEAN
	DataPadding        foundation.BOOLEAN
	ReportSetmarks     foundation.BOOLEAN
	EOTWarningZoneSize uint32
}

// TAPE_SET_MEDIA_PARAMETERS: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-tape_set_media_parameters
type TAPE_SET_MEDIA_PARAMETERS struct {
	BlockSize uint32
}

type TAPE_WMI_OPERATIONS struct {
	Method         uint32
	DataBufferSize uint32
	DataBuffer     unsafe.Pointer
}

type TOKEN_BNO_ISOLATION_INFORMATION struct {
	IsolationPrefix  foundation.PWSTR
	IsolationEnabled foundation.BOOLEAN
}

type TOKEN_LOGGING_INFORMATION struct {
	TokenType          security.TOKEN_TYPE
	TokenElevation     security.TOKEN_ELEVATION
	TokenElevationType security.TOKEN_ELEVATION_TYPE
	ImpersonationLevel security.SECURITY_IMPERSONATION_LEVEL
	IntegrityLevel     uint32
	User               security.SID_AND_ATTRIBUTES
	TrustLevelSid      security.PSID
	SessionId          uint32
	AppContainerNumber uint32
	AuthenticationId   foundation.LUID
	GroupCount         uint32
	GroupsLength       uint32
	Groups             *security.SID_AND_ATTRIBUTES
}

type TOKEN_SID_INFORMATION struct {
	Sid security.PSID
}

type TRANSACTIONMANAGER_BASIC_INFORMATION struct {
	TmIdentity   win32.GUID
	VirtualClock int64
}

type TRANSACTIONMANAGER_LOGPATH_INFORMATION struct {
	LogPathLength uint32
	LogPath       [1]uint16
}

type TRANSACTIONMANAGER_LOG_INFORMATION struct {
	LogIdentity win32.GUID
}

type TRANSACTIONMANAGER_OLDEST_INFORMATION struct {
	OldestTransactionGuid win32.GUID
}

type TRANSACTIONMANAGER_RECOVERY_INFORMATION struct {
	LastRecoveredLsn uint64
}

type TRANSACTION_BASIC_INFORMATION struct {
	TransactionId win32.GUID
	State         uint32
	Outcome       uint32
}

type TRANSACTION_BIND_INFORMATION struct {
	TmHandle foundation.HANDLE
}

type TRANSACTION_ENLISTMENTS_INFORMATION struct {
	NumberOfEnlistments uint32
	EnlistmentPair      [1]TRANSACTION_ENLISTMENT_PAIR
}

type TRANSACTION_ENLISTMENT_PAIR struct {
	EnlistmentId      win32.GUID
	ResourceManagerId win32.GUID
}

type TRANSACTION_LIST_ENTRY struct {
	UOW win32.GUID
}

type TRANSACTION_LIST_INFORMATION struct {
	NumberOfTransactions   uint32
	TransactionInformation [1]TRANSACTION_LIST_ENTRY
}

type TRANSACTION_PROPERTIES_INFORMATION struct {
	IsolationLevel    uint32
	IsolationFlags    uint32
	Timeout           int64
	Outcome           uint32
	DescriptionLength uint32
	Description       [1]uint16
}

type TRANSACTION_SUPERIOR_ENLISTMENT_INFORMATION struct {
	SuperiorEnlistmentPair TRANSACTION_ENLISTMENT_PAIR
}

// UMS_CREATE_THREAD_ATTRIBUTES: https://learn.microsoft.com/windows/win32/api/winnt/ns-winnt-ums_create_thread_attributes
type UMS_CREATE_THREAD_ATTRIBUTES struct {
	UmsVersion        uint32
	UmsContext        unsafe.Pointer
	UmsCompletionList unsafe.Pointer
}

type XSAVE_ARM64_SVE_HEADER struct {
	VectorLength            uint32
	VectorRegisterOffset    uint32
	PredicateRegisterOffset uint32
	Reserved                [5]uint32
}

type XSAVE_CET_U_FORMAT struct {
	Ia32CetUMsr   uint64
	Ia32Pl3SspMsr uint64
}

type RemoteMETAFILEPICT struct {
	Mm   int32
	XExt int32
	YExt int32
	HMF  *UserHMETAFILE
}

type UserBITMAP struct {
	BmType       int32
	BmWidth      int32
	BmHeight     int32
	BmWidthBytes int32
	BmPlanes     uint16
	BmBitsPixel  uint16
	CbSize       uint32
	PBuffer      [1]byte
}

// UserCLIPFORMAT_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserCLIPFORMAT_u_e__Struct struct {
	Data [1]uint64
}

type UserCLIPFORMAT struct {
	FContext int32
	U        UserCLIPFORMAT_u_e__Struct
}

// UserHBITMAP_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHBITMAP_u_e__Struct struct {
	Data [1]uint64
}

type UserHBITMAP struct {
	FContext int32
	U        UserHBITMAP_u_e__Struct
}

// UserHENHMETAFILE_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHENHMETAFILE_u_e__Struct struct {
	Data [1]uint64
}

type UserHENHMETAFILE struct {
	FContext int32
	U        UserHENHMETAFILE_u_e__Struct
}

// UserHGLOBAL_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHGLOBAL_u_e__Struct struct {
	Data [1]uint64
}

type UserHGLOBAL struct {
	FContext int32
	U        UserHGLOBAL_u_e__Struct
}

// UserHMETAFILE_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHMETAFILE_u_e__Struct struct {
	Data [1]uint64
}

type UserHMETAFILE struct {
	FContext int32
	U        UserHMETAFILE_u_e__Struct
}

// UserHMETAFILEPICT_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHMETAFILEPICT_u_e__Struct struct {
	Data [1]uint64
}

type UserHMETAFILEPICT struct {
	FContext int32
	U        UserHMETAFILEPICT_u_e__Struct
}

// UserHPALETTE_u_e__Struct is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type UserHPALETTE_u_e__Struct struct {
	Data [1]uint64
}

type UserHPALETTE struct {
	FContext int32
	U        UserHPALETTE_u_e__Struct
}
