// Code generated by go-bindings-win32-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package netshell binds the Windows.Win32.NetworkManagement.NetShell API surface.
package netshell
